# Generated by ryoku-install during an ISO installation.
#
# This file contains the machine-specific choices used by the otherwise
# reusable configuration files in this directory. It is intentionally small so
# the rest of /etc/nixos stays pleasant to read and edit.
{
  hostname = "ryoku";
  username = "ryoku";

  firmware = "uefi";
  installDisk = "/dev/sda";
  gpuVendors = [ ];

  timeZone = "UTC";
  locale = "en_US.UTF-8";
  keyboardLayout = "us";

  compositor = "hyprland";
  browser = "chromium";
  shell = "fish";
  optionalApps = [
    "prompt"
    "fastfetch"
    "yazi"
    "cli-tools"
    "pavucontrol"
    "songrec"
    "openrgb"
    "upscale"
    "gamescope"
    "gamemode"
    "mangohud"
    "vm"
    "docker"
    "mise"
  ];

  ryokuSource = "github:aethctl/Ryoku-on-NixOS/main";
  nixpkgsSource = "github:NixOS/nixpkgs/nixos-unstable";
}
