package doctor

import (
	"errors"
	"strings"
	"testing"
)

const pinnedSettings = `-- Generated by Ryoku Settings (Super + ,).
hl.config({
  general = { ["col.active_border"] = "rgb(e0563b)", ["col.inactive_border"] = "rgb(313a4d)" },
})
`

func TestPlanBorderPin(t *testing.T) {
	noRepair := func() error { t.Fatal("repair must not run"); return nil }

	t.Run("fixed colours keep their pin", func(t *testing.T) {
		r := planBorderPin(borderPinState{paletteDriven: false, settingsLua: pinnedSettings, providerReady: true}, true, noRepair)
		if r.status != recOK {
			t.Fatalf("status = %v, want ok", r.status)
		}
	})

	t.Run("clean generated file passes", func(t *testing.T) {
		r := planBorderPin(borderPinState{paletteDriven: true, settingsLua: "hl.config({ general = { gaps_in = 4 } })\n", providerReady: true}, true, noRepair)
		if r.status != recOK {
			t.Fatalf("status = %v, want ok", r.status)
		}
	})

	t.Run("absent file passes", func(t *testing.T) {
		r := planBorderPin(borderPinState{paletteDriven: true, providerReady: true}, true, noRepair)
		if r.status != recOK {
			t.Fatalf("status = %v, want ok", r.status)
		}
	})

	t.Run("stale pin reports in check mode", func(t *testing.T) {
		r := planBorderPin(borderPinState{paletteDriven: true, settingsLua: pinnedSettings, providerReady: true}, true, noRepair)
		if r.status != recWouldFix || !strings.Contains(r.detail, "col.active_border") {
			t.Fatalf("result = %v %q", r.status, r.detail)
		}
	})

	t.Run("stale pin repairs in apply mode", func(t *testing.T) {
		ran := false
		r := planBorderPin(borderPinState{paletteDriven: true, settingsLua: pinnedSettings, providerReady: true}, false, func() error { ran = true; return nil })
		if !ran || r.status != recFixed {
			t.Fatalf("ran=%v status=%v", ran, r.status)
		}
	})

	t.Run("failed repair says so", func(t *testing.T) {
		r := planBorderPin(borderPinState{paletteDriven: true, settingsLua: pinnedSettings, providerReady: true}, false, func() error { return errors.New("no provider") })
		if r.status != recFailed {
			t.Fatalf("status = %v, want failed", r.status)
		}
	})

	t.Run("missing provider warns", func(t *testing.T) {
		r := planBorderPin(borderPinState{paletteDriven: true, settingsLua: pinnedSettings, providerReady: false}, false, noRepair)
		if r.status != recWarn {
			t.Fatalf("status = %v, want warn", r.status)
		}
	})
}
