package main

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// The settings.conf generator and the ini formatting helpers the block writers
// share. mango's config is `key=value` lines, `#` comments, colours as
// 0xrrggbbaa, booleans as 0/1. The store types live in config_store.go; the
// block writers in this file, config_binds.go and config_rules.go.

const confHeader = "# Generated by Ryoku Settings (Super + ,). Edit in the GUI, not here.\n\n"

// confBool renders 0/1.
func confBool(v bool) string {
	if v {
		return "1"
	}
	return "0"
}

// mangoColor normalises a stored #rrggbb (or bare rrggbbaa) to mango's
// 0xrrggbbaa spelling. Empty stays empty so the caller omits the line.
func mangoColor(hex string) string {
	h := strings.TrimSpace(hex)
	if h == "" {
		return ""
	}
	h = strings.TrimPrefix(h, "#")
	switch len(h) {
	case 6:
		h += "ff"
	case 8:
	default:
		return ""
	}
	for _, r := range h {
		if !strings.ContainsRune("0123456789abcdefABCDEF", r) {
			return ""
		}
	}
	return "0x" + strings.ToLower(h)
}

// confEnum drops the "default" sentinel: a string enum left at mango's own
// baseline writes no line, so mango's compiled default stands for it.
func confEnum(v string) string {
	if v == "default" {
		return ""
	}
	return v
}

// confNum formats a float plainly: mango parses %g output.
func confNum(f float64) string {
	return strconv.FormatFloat(f, 'g', -1, 64)
}

// line writes one key=value.
func line(b *strings.Builder, key, val string) {
	if val == "" {
		return
	}
	b.WriteString(key)
	b.WriteString("=")
	b.WriteString(val)
	b.WriteString("\n")
}

// genSettings renders settings.conf from the full effective store: the whole
// Ryoku look in mango's own key names. Additive blocks (env, autostart, rules)
// appear only when the store holds them, the same discipline niri's generator
// uses. The generated file is always written, empty included: the shipped entry
// sources it and apply must leave a complete, validating tree on disk.
func genSettings(s mangoStore) []byte {
	var b strings.Builder
	b.WriteString(confHeader)
	writeBehaviour(&b, s)
	writeAppearance(&b, s)
	writeAnimations(&b, s)
	writeInput(&b, s)
	writeCursor(&b, s.Cursor)
	writeLayout(&b, s)
	writeOverview(&b, s.Mango)
	writeScratchpad(&b, s.Mango)
	writeEnvironment(&b, s.Env)
	writeAutostart(&b, s.Autostart)
	writeWindowRules(&b, s)
	writeLayerRules(&b, s.Mango.LayerRules)
	return []byte(b.String())
}

// writeBehaviour emits the focus and window-management scalars with no neutral
// home: the wm.mango.* leaves the other providers do not have.
func writeBehaviour(b *strings.Builder, s mangoStore) {
	m := s.Mango
	line(b, "tag_num", strconv.Itoa(m.TagNum))
	line(b, "focus_on_activate", confBool(m.FocusOnActivate))
	line(b, "focus_cross_monitor", confBool(m.FocusCrossMonitor))
	line(b, "focus_cross_tag", confBool(m.FocusCrossTag))
	line(b, "warpcursor", confBool(m.WarpCursor))
	line(b, "view_current_to_back", confBool(m.ViewCurrentToBack))
	line(b, "allow_tearing", m.AllowTearing)
	line(b, "idleinhibit_ignore_visible", confBool(m.IdleInhibitIgnoreVisible))
	line(b, "idleinhibit_when_fullscreen", confBool(m.IdleInhibitWhenFullscreen))
	line(b, "xwayland_ignore_scale", confBool(m.XWaylandIgnoreScale))
	line(b, "xwayland_persistence", confBool(m.XWaylandPersistence))
	line(b, "syncobj_enable", confBool(m.SyncobjEnable))
	line(b, "allow_lock_transparent", confBool(m.AllowLockTransparent))
	line(b, "allow_shortcuts_inhibit", m.AllowShortcutsInhibit)
	line(b, "tag_gather", confBool(m.TagGather))
	line(b, "tag_carousel", confBool(m.TagCarousel))
	line(b, "exchange_cross_monitor", confBool(m.ExchangeCrossMonitor))
	line(b, "focusdir_only_zone_overlap", confBool(m.FocusdirOnlyZoneOverlap))
	line(b, "float_full_to_top", confBool(m.FloatFullToTop))
	line(b, "drag_tile_to_tile", confBool(m.DragTileToTile))
	line(b, "drag_tile_small", confBool(m.DragTileSmall))
	line(b, "drag_warp_cursor", confBool(m.DragWarpCursor))
	line(b, "drag_corner", m.DragCorner)
	line(b, "enable_floating_snap", confBool(m.EnableFloatingSnap))
	line(b, "snap_distance", strconv.Itoa(m.SnapDistance))
	line(b, "axis_bind_apply_timeout", strconv.Itoa(m.AxisBindApplyTimeout))
	b.WriteString("\n")
}

// writeAppearance emits the frame, gaps, opacity, dim, shadow and blur block
// from the neutral desktop.appearance leaves.
func writeAppearance(b *strings.Builder, s mangoStore) {
	a := s.Appearance
	m := s.Mango
	line(b, "gappih", strconv.Itoa(a.GapsIn))
	line(b, "gappiv", strconv.Itoa(a.GapsIn))
	line(b, "gappoh", strconv.Itoa(a.GapsOut))
	line(b, "gappov", strconv.Itoa(a.GapsOut))
	line(b, "smartgaps", confBool(m.SmartGaps))
	line(b, "borderpx", strconv.Itoa(a.BorderSize))
	line(b, "border_radius", strconv.Itoa(a.Rounding))
	line(b, "no_border_when_single", confBool(m.NoBorderWhenSingle))
	line(b, "no_radius_when_single", confBool(m.NoRadiusWhenSingle))
	line(b, "focuscolor", mangoColor(a.ActiveBorder))
	line(b, "bordercolor", mangoColor(a.InactiveBorder))
	line(b, "urgentcolor", mangoColor(m.UrgentColor))
	line(b, "rootcolor", mangoColor(m.RootColor))
	line(b, "dropcolor", mangoColor(m.DropColor))
	line(b, "splitcolor", mangoColor(m.SplitColor))
	line(b, "maximizescreencolor", mangoColor(m.MaximizeColor))
	line(b, "scratchpadcolor", mangoColor(m.ScratchpadColor))
	line(b, "globalcolor", mangoColor(m.GlobalColor))
	line(b, "overlaycolor", mangoColor(m.OverlayColor))
	line(b, "focused_opacity", confNum(a.ActiveOpacity))
	line(b, "unfocused_opacity", confNum(a.InactiveOpacity))
	// The neutral dim model maps to mango's unfocused dim colour: strength
	// becomes the alpha of dim_unfocused_color, on when dimInactive is on.
	if a.DimInactive {
		line(b, "dim_enable", "1")
		line(b, "dim_focused_color", "0x00000000")
		line(b, "dim_unfocused_color", dimAlpha(a.DimStrength))
	} else {
		line(b, "dim_enable", "0")
		line(b, "dim_focused_color", "0x00000000")
		line(b, "dim_unfocused_color", "0x00000000")
	}
	if a.ShadowEnabled {
		line(b, "shadows", "1")
		line(b, "layer_shadows", "1")
		line(b, "shadow_only_floating", "0")
		line(b, "shadows_size", strconv.Itoa(a.ShadowRange))
		line(b, "shadows_blur", strconv.Itoa(maxInt(a.ShadowSpread*2, 1)))
		line(b, "shadows_position_x", strconv.Itoa(a.ShadowOffsetX))
		line(b, "shadows_position_y", strconv.Itoa(a.ShadowOffsetY))
		line(b, "shadowscolor", mangoColor(a.ShadowColor))
	} else {
		line(b, "shadows", "0")
		line(b, "layer_shadows", "0")
		line(b, "shadow_only_floating", "1")
	}
	if a.BlurEnabled {
		line(b, "blur", "1")
		line(b, "blur_layer", "1")
		line(b, "blur_optimized", "1")
		line(b, "blur_params_radius", strconv.Itoa(a.BlurSize))
		line(b, "blur_params_num_passes", strconv.Itoa(a.BlurPasses))
		line(b, "blur_params_noise", confNum(a.BlurNoise))
		line(b, "blur_params_saturation", confNum(a.BlurVibrancy))
		line(b, "blur_params_brightness", "0.9")
		line(b, "blur_params_contrast", "0.9")
	} else {
		line(b, "blur", "0")
		line(b, "blur_layer", "0")
	}
	b.WriteString("\n")
}

// dimAlpha turns the neutral 0..1 dim strength into mango's 0x000000AA colour:
// only the alpha channel matters for the dim node.
func dimAlpha(strength float64) string {
	if strength < 0 {
		strength = 0
	}
	if strength > 1 {
		strength = 1
	}
	a := int(strength*255 + 0.5)
	return "0x000000" + hexByte(a)
}

func hexByte(n int) string {
	const digits = "0123456789abcdef"
	return string([]byte{digits[(n>>4)&0xf], digits[n&0xf]})
}

// writeAnimations emits the animation master switch and the per-event type,
// duration and curve block from the wm.mango.anim tree. Mode "default" emits
// nothing for that event so mango's own baseline stands; "off" zeroes the
// duration, which mango reads as no animation for the event.
func writeAnimations(b *strings.Builder, s mangoStore) {
	a := s.Appearance
	m := s.Mango
	line(b, "animations", confBool(a.Animations))
	line(b, "layer_animations", confBool(a.Animations))
	writeAnim(b, "open", m.Anim.Open)
	writeAnim(b, "close", m.Anim.Close)
	writeAnim(b, "move", m.Anim.Move)
	writeAnim(b, "tag", m.Anim.Tag)
	line(b, "animation_fade_in", confBool(a.Animations))
	line(b, "animation_fade_out", confBool(a.Animations))
	line(b, "fadein_begin_opacity", confNum(m.FadeinBeginOpacity))
	line(b, "fadeout_begin_opacity", confNum(m.FadeoutBeginOpacity))
	line(b, "zoom_initial_ratio", confNum(m.ZoomInitialRatio))
	line(b, "zoom_end_ratio", confNum(m.ZoomEndRatio))
	line(b, "tag_animation_direction", m.TagAnimationDirection)
	line(b, "layer_animation_type_open", confEnum(m.LayerAnimationTypeOpen))
	line(b, "layer_animation_type_close", confEnum(m.LayerAnimationTypeClose))
	b.WriteString("\n")
}

func writeAnim(b *strings.Builder, event string, spec AnimSpec) {
	if spec.Mode == "default" || spec.Mode == "" {
		return
	}
	if spec.Mode == "off" {
		line(b, "animation_duration_"+event, "0")
		return
	}
	if spec.Type != "" {
		line(b, "animation_type_"+event, spec.Type)
	}
	if spec.DurationMs > 0 {
		line(b, "animation_duration_"+event, strconv.Itoa(spec.DurationMs))
	}
	if spec.Curve != "" {
		line(b, "animation_curve_"+event, spec.Curve)
	}
}

func writeInput(b *strings.Builder, s mangoStore) {
	in := s.Input
	m := s.Mango
	line(b, "repeat_rate", strconv.Itoa(in.RepeatRate))
	line(b, "repeat_delay", strconv.Itoa(in.RepeatDelay))
	line(b, "numlockon", confBool(in.NumlockByDefault))
	line(b, "xkb_rules_layout", in.KbLayout)
	if in.KbVariant != "" {
		line(b, "xkb_rules_variant", in.KbVariant)
	}
	if in.KbOptions != "" {
		line(b, "xkb_rules_options", in.KbOptions)
	}
	line(b, "sloppyfocus", confBool(in.FollowMouse == 1))
	line(b, "axis_scroll_factor", confNum(in.MouseScrollFactor))
	line(b, "mouse_natural_scrolling", confBool(in.MouseNaturalScroll))
	line(b, "mouse_accel_profile", accelProfile(in.AccelProfile))
	line(b, "mouse_accel_speed", confNum(in.Sensitivity))
	line(b, "mouse_left_handed", confBool(in.LeftHanded))
	line(b, "mouse_click_method", clickMethod(in.Clickfinger))
	line(b, "mouse_middle_button_emulation", confBool(in.MiddleEmulation))
	line(b, "trackpad_disable_while_typing", confBool(in.DisableWhileTyping))
	line(b, "tap_to_click", confBool(in.TapToClick))
	line(b, "tap_and_drag", confBool(in.TapAndDrag))
	line(b, "drag_lock", confBool(in.TapAndDrag))
	line(b, "trackpad_natural_scrolling", confBool(in.NaturalScroll))
	line(b, "trackpad_scroll_factor", confNum(in.TouchScrollFactor))
	line(b, "trackpad_accel_profile", accelProfile(in.AccelProfile))
	line(b, "trackpad_accel_speed", confNum(in.Sensitivity))
	line(b, "trackpad_click_method", clickMethod(in.Clickfinger))
	line(b, "trackpad_left_handed", confBool(in.LeftHanded))
	line(b, "trackpad_middle_button_emulation", confBool(in.MiddleEmulation))
	line(b, "touch_enable", confBool(m.TouchEnable))
	line(b, "touch_enable_mouse_emulation", confBool(m.TouchMouseEmulation))
	line(b, "swipe_min_threshold", strconv.Itoa(m.SwipeMinThreshold))
	line(b, "gesture_live", confBool(m.GestureLive))
	line(b, "gesture_swipe_distance", strconv.Itoa(m.GestureSwipeDistance))
	line(b, "gesture_swipe_cancel_ratio", confNum(m.GestureSwipeCancelRatio))
	line(b, "gesture_swipe_min_speed_to_force", strconv.Itoa(m.GestureSwipeMinSpeedForce))
	line(b, "mouse_scroll_method", m.MouseScrollMethod)
	line(b, "mouse_scroll_button", strconv.Itoa(m.MouseScrollButton))
	line(b, "mouse_send_events_mode", m.MouseSendEventsMode)
	line(b, "trackpad_scroll_method", m.TrackpadScrollMethod)
	line(b, "trackpad_scroll_button", strconv.Itoa(m.TrackpadScrollButton))
	line(b, "trackpad_send_events_mode", m.TrackpadSendEventsMode)
	line(b, "button_map", m.ButtonMap)
	// The touchpad FN lock lives in a state file (mango answers no query), and
	// writeInput re-emits it here so the lock survives a reload and a login.
	if touchpadDisabled() {
		line(b, "disable_trackpad", "1")
	}
	b.WriteString("\n")
}

// accelProfile maps the neutral "flat"|"none" onto mango's 0/1/2. Empty means
// the device default, which is adaptive (2) on mango's own default.
func accelProfile(p string) string {
	switch p {
	case "flat":
		return "1"
	case "none":
		return "0"
	default:
		return "2"
	}
}

// clickMethod maps the neutral clickfinger flag onto mango's 1/2.
func clickMethod(clickfinger bool) string {
	if clickfinger {
		return "2"
	}
	return "1"
}

// writeCursor emits the theme and size the compositor renders cursor-shape
// requests from, plus the hide knobs.
func writeCursor(b *strings.Builder, c Cursor) {
	line(b, "cursor_theme", c.Theme)
	line(b, "cursor_size", strconv.Itoa(c.Size))
	line(b, "cursor_hide_timeout", strconv.Itoa(c.InactiveTimeout))
	line(b, "cursor_hide_on_keypress", confBool(c.HideOnKeyPress))
	b.WriteString("\n")
}

// writeLayout emits the master/stack and scroller tuning plus the per-tag
// layout rules the Ryoku look expands: one tagrule per tag at the default
// layout, the same spelling the shipped mango default uses.
func writeLayout(b *strings.Builder, s mangoStore) {
	m := s.Mango
	line(b, "default_mfact", confNum(m.DefaultMFact))
	line(b, "default_nmaster", strconv.Itoa(m.DefaultNMaster))
	line(b, "new_is_master", confBool(m.NewIsMaster))
	line(b, "center_master_overspread", confBool(m.CenterMasterOverspread))
	line(b, "center_when_single_stack", confBool(m.CenterWhenSingleStack))
	line(b, "dwindle_smart_split", confBool(m.DwindleSmartSplit))
	line(b, "dwindle_smart_resize", confBool(m.DwindleSmartResize))
	line(b, "dwindle_manual_split", confBool(m.DwindleManualSplit))
	line(b, "dwindle_preserve_split", confBool(m.DwindlePreserveSplit))
	line(b, "dwindle_drop_simple_split", confBool(m.DwindleDropSimpleSplit))
	line(b, "dwindle_hsplit", m.DwindleHSplit)
	line(b, "dwindle_vsplit", m.DwindleVSplit)
	line(b, "dwindle_split_ratio", confNum(m.DwindleSplitRatio))
	line(b, "scroller_structs", strconv.Itoa(m.ScrollerStructs))
	line(b, "scroller_default_proportion", confNum(m.ScrollerDefaultProportion))
	line(b, "scroller_focus_center", confBool(m.ScrollerFocusCenter))
	line(b, "scroller_prefer_center", confBool(m.ScrollerPreferCenter))
	line(b, "scroller_prefer_overspread", confBool(m.ScrollerPreferOverspread))
	line(b, "scroller_ignore_proportion_single", confBool(m.ScrollerIgnoreProportionSingle))
	line(b, "scroller_default_proportion_single", confNum(m.ScrollerDefaultProportionSingle))
	line(b, "edge_scroller_pointer_focus", confBool(m.EdgeScrollerPointerFocus))
	line(b, "edge_scroller_focus_allow_speed", confNum(m.EdgeScrollerFocusAllowSpeed))
	if len(m.ScrollerProportionPreset) > 0 {
		parts := make([]string, 0, len(m.ScrollerProportionPreset))
		for _, v := range m.ScrollerProportionPreset {
			parts = append(parts, confNum(v))
		}
		line(b, "scroller_proportion_preset", strings.Join(parts, ","))
	}
	for i := 1; i <= m.TagNum; i++ {
		b.WriteString("tagrule=id:" + strconv.Itoa(i) + ",layout_name:" + m.DefaultLayout + "\n")
	}
	b.WriteString("\n")
}

// writeOverview emits the hycov-style overview tuning.
func writeOverview(b *strings.Builder, m Mango) {
	line(b, "enable_hotarea", confBool(m.EnableHotarea))
	line(b, "hotarea_size", strconv.Itoa(m.HotareaSize))
	line(b, "hotarea_corner", m.HotareaCorner)
	line(b, "hotarea_disable_on_fullscreen", confBool(m.HotareaDisableOnFullscreen))
	line(b, "overviewgappi", strconv.Itoa(m.OverviewGapIn))
	line(b, "overviewgappo", strconv.Itoa(m.OverviewGapOut))
	line(b, "overcircle_center_ratio", confNum(m.OvercircleCenterRatio))
	b.WriteString("\n")
}

func writeScratchpad(b *strings.Builder, m Mango) {
	line(b, "scratchpad_width_ratio", confNum(m.ScratchpadWidthRatio))
	line(b, "scratchpad_height_ratio", confNum(m.ScratchpadHeightRatio))
	line(b, "single_scratchpad", confBool(m.SingleScratchpad))
	line(b, "scratchpad_cross_monitor", confBool(m.ScratchpadCrossMonitor))
	line(b, "special_dim", confNum(m.SpecialDim))
	line(b, "special_gappih", strconv.Itoa(m.SpecialGapsIn))
	line(b, "special_gappiv", strconv.Itoa(m.SpecialGapsIn))
	line(b, "special_gappoh", strconv.Itoa(m.SpecialGapsOut))
	line(b, "special_gappov", strconv.Itoa(m.SpecialGapsOut))
	b.WriteString("\n")
}

// writeEnvironment emits the store's env= lines. mango's env values reset on
// reload, so they live in the generated file (which reload re-sources) rather
// than only in the seed: one writer, and the value survives every reload.
func writeEnvironment(b *strings.Builder, env []EnvVar) {
	if len(env) == 0 {
		return
	}
	for _, e := range env {
		if e.Key == "" {
			continue
		}
		line(b, "env", e.Key+","+e.Value)
	}
	b.WriteString("\n")
}

// writeAutostart emits the store's autostart commands as exec-once lines. The
// shipped session bootstrap lives in autostart.conf; these are the user's own
// additions from the Hub, so they are additive and only appear when set.
func writeAutostart(b *strings.Builder, cmds []Autostart) {
	if len(cmds) == 0 {
		return
	}
	for _, a := range cmds {
		if strings.TrimSpace(a.Command) == "" {
			continue
		}
		line(b, "exec-once", a.Command)
	}
	b.WriteString("\n")
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}

// seededLayouts is the loaded keyboard-layout list for the bar indicator. mango's
// IPC answers only the ACTIVE layout name, never the set, so the set comes from
// the generated tree (xkb_rules_layout, comma-separated).
func seededLayouts() []string {
	for _, name := range []string{"settings.conf", "keyboard.conf"} {
		b, err := os.ReadFile(filepath.Join(mangoConfigDir(), name))
		if err != nil {
			continue
		}
		for _, raw := range strings.Split(string(b), "\n") {
			k, v, ok := strings.Cut(strings.TrimSpace(raw), "=")
			if !ok || k != "xkb_rules_layout" {
				continue
			}
			var out []string
			for _, tok := range strings.Split(v, ",") {
				if t := strings.TrimSpace(tok); t != "" {
					out = append(out, strings.TrimSpace(t))
				}
			}
			if len(out) > 0 {
				return out
			}
		}
	}
	return nil
}

// configScalarInt reads one integer scalar from the live generated config,
// falling back to def when the file or key is absent. mango answers no getter
// over IPC, so the tree on disk is the record of the current value.
func configScalarInt(key string, def int) int {
	b, err := os.ReadFile(filepath.Join(mangoConfigDir(), "settings.conf"))
	if err != nil {
		return def
	}
	for _, raw := range strings.Split(string(b), "\n") {
		k, v, ok := strings.Cut(strings.TrimSpace(raw), "=")
		if !ok || k != key {
			continue
		}
		if n, err := strconv.Atoi(strings.TrimSpace(v)); err == nil {
			return n
		}
		return def
	}
	return def
}

// rewriteTagLayout pins one tag's layout by regenerating settings.conf with the
// tag's tagrule rewritten, then reloading the running session. The tagrule set
// is generated in full every apply, so this edits the tree, not the store.
func rewriteTagLayout(ws, layout string) error {
	dir := mangoConfigDir()
	b, err := os.ReadFile(filepath.Join(dir, "settings.conf"))
	if err != nil {
		return err
	}
	want := "tagrule=id:" + ws + ","
	out := make([]string, 0, 48)
	hit := false
	for _, raw := range strings.Split(string(b), "\n") {
		trimmed := strings.TrimSpace(raw)
		if strings.HasPrefix(trimmed, want) && strings.Contains(trimmed, "layout_name:") {
			fields := strings.Split(trimmed[len(want):], ",")
			edited := false
			for i, f := range fields {
				if strings.HasPrefix(f, "layout_name:") {
					fields[i] = "layout_name:" + layout
					edited = true
				}
			}
			if !edited {
				fields = append(fields, "layout_name:"+layout)
			}
			out = append(out, want+strings.Join(fields, ","))
			hit = true
			continue
		}
		out = append(out, raw)
	}
	if !hit {
		out = append(out, want+"layout_name:"+layout)
	}
	body := []byte(strings.Join(out, "\n"))
	if err := atomicWrite(filepath.Join(userEditsMangoDir(), "settings.conf"), body, 0o644); err != nil {
		return err
	}
	if err := atomicWrite(filepath.Join(dir, "settings.conf"), body, 0o644); err != nil {
		return err
	}
	return dispatch("reload_config")
}
