add_newline = false
palette = "mythos"
format = """
$directory$git_branch
$character"""
right_format = "$cmd_duration"

[palettes.mythos]
dir_bg = "#23252E"
git_bg = "#1A272D"
time_bg = "#2B1E22"
dir_fg = "#ECA75B"
git_fg = "#70C2A3"
time_fg = "#E27B75"
crimson = "#E64553"

[directory]
style = "bold fg:dir_fg"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"
read_only_style = "bold fg:crimson"
format = "[󰉋  $path]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = "󰊢 "
style = "fg:git_fg"
format = "[  $symbol$branch]($style)"

[cmd_duration]
min_time = 500
style = "fg:time_fg"
format = "[󰔚 $duration]($style)"

[character]
success_symbol = "[❯](bold fg:dir_fg) "
error_symbol = "[❯](bold fg:crimson) "
vimcmd_symbol = "[❮](bold fg:git_fg) "

[package]
disabled = true
