package main

import (
	"fmt"
	"sort"
	"strings"
)

// Keybind, unbind and rebind emission for the generated Hyprland config.

func genKeybind(k Keybind) string {
	if strings.TrimSpace(k.Keys) == "" {
		return ""
	}
	var dsp string
	switch k.Action {
	case "exec", "":
		if strings.TrimSpace(k.Value) == "" {
			return ""
		}
		dsp = fmt.Sprintf("hl.dsp.exec_cmd(%s)", luaStr(k.Value))
	case "close":
		dsp = "hl.dsp.window.close()"
	case "fullscreen":
		dsp = "hl.dsp.window.fullscreen()"
	case "togglefloating":
		dsp = "hl.dsp.window.float({ action = \"toggle\" })"
	default:
		return ""
	}
	if k.Release {
		return fmt.Sprintf("hl.bind(%s, %s, { release = true })\n", luaStr(k.Keys), dsp)
	}
	return fmt.Sprintf("hl.bind(%s, %s)\n", luaStr(k.Keys), dsp)
}

// genUnbinds drops the shipped chords a config import must release so an imported
// bind that shadows a shipped one wins. Emitted before the binds, so after
// binds.lua registered the shipped chord and before the imported bind re-adds it.
func genUnbinds(o Overrides) string {
	var b strings.Builder
	for _, c := range o.Unbinds {
		if c = strings.TrimSpace(c); c == "" {
			continue
		}
		fmt.Fprintf(&b, "hl.unbind(%s)\n", luaStr(c))
	}
	return b.String()
}

// renderRebinds is the K() lookup binds.lua consults: one [default chord] =
// chosen chord per rebind. Always a full table (return {} when empty) so
// clearing the last rebind leaves no stale entry behind.
func renderRebinds(o Overrides) []byte {
	keys := make([]string, 0, len(o.KeybindRebinds))
	for k := range o.KeybindRebinds {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("-- Generated by Ryoku Settings (Keybinds page); change it in the GUI, not here.\nreturn {\n")
	for _, from := range keys {
		to := strings.TrimSpace(o.KeybindRebinds[from])
		from = strings.TrimSpace(from)
		if from == "" || to == "" || from == to {
			continue
		}
		fmt.Fprintf(&b, "\t[%s] = %s,\n", luaStr(from), luaStr(to))
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

// runBinds prints Hyprland's compositor-exclusive binds, the seam's binds verb.
// Hyprland's shipped set IS the shared Ryoku legend (binds.lua), so it adds none
// of its own: an empty list, which the Hub reads as no compositor section. The
// store path apply and niri take is accepted and ignored, so the seam call is
// identical across providers.
func runBinds(_ []string) error {
	_, err := stdout.Write([]byte("[]\n"))
	return err
}
