import QtQuick
import Ryoku.Ui.Singletons

FolioTabData {
    tabKey: "automation"
    title: I18n.tr("Automation")
    note: I18n.tr("Run schedules and commands around wallpaper changes.")
    sections: [
        {
            title: I18n.tr("Random rotation"),
            subtitle: "",
            controls: [
                { id: "general.randomRotate",
                  key: "general.randomRotate",
                  kind: "toggle",
                  label: I18n.tr("Rotate automatically"),
                  help: I18n.tr("Apply a random wallpaper from the pool below whenever the interval expires. The interval does nothing while this is off."),
                  search: ["general.randomRotate", "rotate", "automatically", "toggle"] },
                { id: "general.randomInterval",
                  key: "general.randomInterval",
                  kind: "number",
                  label: I18n.tr("Interval"),
                  help: I18n.tr("Seconds between random rotations (minimum 10)."),
                  unit: I18n.tr("s"),
                  search: ["general.randomInterval", "interval", "s", "number"] },
                { id: "general.randomIncludeStatic",
                  key: "general.randomIncludeStatic",
                  kind: "toggle",
                  label: I18n.tr("Include images"),
                  help: I18n.tr("Allow static wallpapers in the random pool."),
                  search: ["general.randomIncludeStatic", "include", "images", "toggle"] },
                { id: "general.randomIncludeVideo",
                  key: "general.randomIncludeVideo",
                  kind: "toggle",
                  label: I18n.tr("Include video"),
                  help: I18n.tr("Allow video wallpapers in the random pool."),
                  search: ["general.randomIncludeVideo", "include", "video", "toggle"] },
                { id: "general.randomIncludeWE",
                  key: "general.randomIncludeWE",
                  kind: "toggle",
                  label: I18n.tr("Include Wallpaper Engine"),
                  help: I18n.tr("Allow Wallpaper Engine items in the random pool."),
                  search: ["general.randomIncludeWE", "include", "wallpaper", "engine", "we", "toggle"] },
                { id: "general.randomIncludeFavourites",
                  key: "general.randomIncludeFavourites",
                  kind: "toggle",
                  label: I18n.tr("Favourites only"),
                  help: I18n.tr("Restrict the random pool to favourited wallpapers."),
                  search: ["general.randomIncludeFavourites", "favourites", "only", "toggle"] }
            ]
        },
        {
            title: I18n.tr("Schedule"),
            subtitle: "",
            controls: [
                { id: "schedule.enabled",
                  key: "schedule.enabled",
                  kind: "toggle",
                  label: I18n.tr("Enable schedule"),
                  help: I18n.tr("Turn every schedule rule on or off without deleting the rules."),
                  search: ["schedule.enabled", "enable", "schedule", "toggle"] },
                { id: "schedule.applyOnStart",
                  key: "schedule.applyOnStart",
                  kind: "toggle",
                  label: I18n.tr("Apply on startup"),
                  help: I18n.tr("Apply the first matching rule when the service starts. A wallpaper picked manually this session still wins."),
                  search: ["schedule.applyOnStart", "apply", "startup", "toggle"] },
                { id: "schedule.editor.action",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Schedule editor"),
                  help: I18n.tr("Build rules from condition blocks and drag to set priority; the first match wins. Legacy day and night settings become two rules on first open."),
                  action: "OpenScheduleEditor",
                  search: ["schedule", "editor", "open", "action"] }
            ]
        },
        {
            title: I18n.tr("Location & weather"),
            subtitle: "",
            controls: [
                { id: "schedule.latitude",
                  key: "schedule.latitude",
                  kind: "text",
                  label: I18n.tr("Latitude"),
                  help: I18n.tr("Decimal degrees, north positive (e.g. 59.33)."),
                  placeholder: I18n.tr("59.33"),
                  search: ["schedule.latitude", "latitude", "text"] },
                { id: "schedule.longitude",
                  key: "schedule.longitude",
                  kind: "text",
                  label: I18n.tr("Longitude"),
                  help: I18n.tr("Decimal degrees, east positive (e.g. 18.06)."),
                  placeholder: I18n.tr("18.06"),
                  search: ["schedule.longitude", "longitude", "text"] },
                { id: "general.weatherMatch",
                  key: "general.weatherMatch",
                  kind: "toggle",
                  label: I18n.tr("Match current weather"),
                  help: I18n.tr("Fetch the weather from Open-Meteo when the picker opens and show wallpapers with matching weather tags. Off shows every wallpaper."),
                  search: ["general.weatherMatch", "match", "current", "weather", "toggle"] },
                { id: "general.locale",
                  key: "general.locale",
                  kind: "text",
                  label: I18n.tr("Location"),
                  help: I18n.tr("City name looked up for current weather (e.g. London). Leave empty to use the latitude/longitude from the Schedule tab instead."),
                  placeholder: I18n.tr("e.g. London"),
                  search: ["general.locale", "location", "text"] }
            ]
        },
        {
            title: I18n.tr("Startup & notifications"),
            subtitle: "",
            controls: [
                { id: "general.notifyOnWallpaperChange",
                  key: "general.notifyOnWallpaperChange",
                  kind: "toggle",
                  label: I18n.tr("Notify on wallpaper change"),
                  help: I18n.tr("Send a system notification each time the wallpaper changes."),
                  search: ["general.notifyOnWallpaperChange", "notify", "wallpaper", "change", "toggle"] },
                { id: "restoreOnStartup",
                  key: "restoreOnStartup",
                  kind: "toggle",
                  label: I18n.tr("Restore wallpaper on startup"),
                  help: I18n.tr("Re-apply the last wallpaper when the daemon starts."),
                  search: ["restoreOnStartup", "restore", "wallpaper", "startup", "toggle"] }
            ]
        },
        {
            title: I18n.tr("Post-apply behaviour"),
            subtitle: "",
            controls: [
                { id: "pickOnlyMode",
                  key: "pickOnlyMode",
                  kind: "toggle",
                  label: I18n.tr("Disable internal wallpaper application"),
                  help: I18n.tr("When enabled, Ryogami will not apply wallpapers itself. Use the post-processing commands below to drive your own setter."),
                  search: ["pickOnlyMode", "disable", "internal", "wallpaper", "application", "toggle"] },
                { id: "postProcessOnRestore",
                  key: "postProcessOnRestore",
                  kind: "toggle",
                  label: I18n.tr("Run on startup restore"),
                  help: I18n.tr("Re-run the post-processing commands when the daemon restores the last wallpaper at startup."),
                  search: ["postProcessOnRestore", "run", "startup", "restore", "toggle"] }
            ]
        },
        {
            title: I18n.tr("Post-apply commands"),
            subtitle: "",
            controls: [
                { id: "postProcessing.N.type",
                  key: "postProcessing.N.type",
                  kind: "chips",
                  label: I18n.tr("Runs for"),
                  help: "",
                  options: [{ value: "all", label: I18n.tr("All") }, { value: "static", label: I18n.tr("Img") }, { value: "video", label: I18n.tr("Vid") }, { value: "we", label: I18n.tr("WE") }],
                  search: ["postProcessing.N.type", "runs", "for", "all", "img", "vid", "we", "chips"] },
                { id: "postProcessing.N.command",
                  key: "postProcessing.N.command",
                  kind: "text",
                  label: I18n.tr("Command %1"),
                  help: "",
                  args: ["index"],
                  placeholder: I18n.tr("Shell command"),
                  search: ["postProcessing.N.command", "command", "shell", "text"] },
                { id: "postProcessing.N.remove.action",
                  key: null,
                  kind: "action",
                  label: "",
                  help: I18n.tr("Remove this command."),
                  action: "RemovePostCommand(idx)",
                  search: ["remove", "action"] },
                { id: "postProcessing.add.action",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Add command"),
                  help: I18n.tr("Add an empty command, then choose which wallpaper types run it."),
                  action: "AddPostCommand",
                  search: ["add", "command", "action"] }
            ]
        }
    ]
}
