import QtQuick
import Ryoku.Ui.Singletons

FolioTabData {
    tabKey: "filter"
    title: I18n.tr("Filter & Search")
    note: I18n.tr("Choose filters, search options, semantic models, and which panels stay visible.")
    sections: [
        {
            title: I18n.tr("Appearance"),
            subtitle: "",
            controls: [
                { id: "filterBar.visualStyle",
                  key: "filterBar.visualStyle",
                  kind: "dropdown",
                  label: I18n.tr("Visual style"),
                  help: I18n.tr("Match picker uses the skewed bar in Slices and Sandy, the geometric bar in Geometric, and the straight bar in Wall."),
                  options: [{ value: "match", label: I18n.tr("Match picker") }, { value: "slices", label: I18n.tr("Slices") }, { value: "hex", label: I18n.tr("Geometric") }, { value: "wall", label: I18n.tr("Wall") }],
                  search: ["filterBar.visualStyle", "visual", "style", "match", "picker", "slices", "hex", "geometric", "wall", "dropdown"] },
                { id: "filterBar.orientation",
                  key: "filterBar.orientation",
                  kind: "dropdown",
                  label: I18n.tr("Orientation"),
                  help: I18n.tr("Place the filter controls above the picker or in a vertical rail beside it."),
                  options: [{ value: "horizontal", label: I18n.tr("Horizontal") }, { value: "vertical", label: I18n.tr("Vertical") }],
                  search: ["filterBar.orientation", "orientation", "horizontal", "vertical", "dropdown"] }
            ]
        },
        {
            title: I18n.tr("Buttons"),
            subtitle: "",
            controls: [
                { id: "filterBar.show.type.all",
                  key: "filterBar.show.type.all",
                  kind: "toggle",
                  label: I18n.tr("All"),
                  help: "",
                  search: ["filterBar.show.type.all", "all", "toggle"] },
                { id: "filterBar.show.type.static",
                  key: "filterBar.show.type.static",
                  kind: "toggle",
                  label: I18n.tr("Images"),
                  help: "",
                  search: ["filterBar.show.type.static", "images", "toggle"] },
                { id: "filterBar.show.type.video",
                  key: "filterBar.show.type.video",
                  kind: "toggle",
                  label: I18n.tr("Videos"),
                  help: "",
                  search: ["filterBar.show.type.video", "videos", "toggle"] },
                { id: "filterBar.show.type.we",
                  key: "filterBar.show.type.we",
                  kind: "toggle",
                  label: I18n.tr("Wallpaper Engine"),
                  help: "",
                  search: ["filterBar.show.type.we", "wallpaper", "engine", "toggle"] },
                { id: "filterBar.show.sort.date",
                  key: "filterBar.show.sort.date",
                  kind: "toggle",
                  label: I18n.tr("Newest"),
                  help: "",
                  search: ["filterBar.show.sort.date", "newest", "toggle"] },
                { id: "filterBar.show.sort.recent",
                  key: "filterBar.show.sort.recent",
                  kind: "toggle",
                  label: I18n.tr("Recently applied"),
                  help: "",
                  search: ["filterBar.show.sort.recent", "recently", "applied", "toggle"] },
                { id: "filterBar.show.sort.color",
                  key: "filterBar.show.sort.color",
                  kind: "toggle",
                  label: I18n.tr("Default (by colour)"),
                  help: "",
                  search: ["filterBar.show.sort.color", "default", "by", "colour", "toggle"] },
                { id: "filterBar.show.sort.pop",
                  key: "filterBar.show.sort.pop",
                  kind: "toggle",
                  label: I18n.tr("Colour pop"),
                  help: "",
                  search: ["filterBar.show.sort.pop", "colour", "pop", "toggle"] },
                { id: "filterBar.show.sort.richness",
                  key: "filterBar.show.sort.richness",
                  kind: "toggle",
                  label: I18n.tr("Colourful"),
                  help: "",
                  search: ["filterBar.show.sort.richness", "colourful", "toggle"] },
                { id: "filterBar.show.sort.minimalist",
                  key: "filterBar.show.sort.minimalist",
                  kind: "toggle",
                  label: I18n.tr("Minimalist"),
                  help: "",
                  search: ["filterBar.show.sort.minimalist", "minimalist", "toggle"] },
                { id: "filterBar.show.sort.res",
                  key: "filterBar.show.sort.res",
                  kind: "toggle",
                  label: I18n.tr("Highest resolution"),
                  help: "",
                  search: ["filterBar.show.sort.res", "highest", "resolution", "toggle"] },
                { id: "filterBar.show.folder",
                  key: "filterBar.show.folder",
                  kind: "toggle",
                  label: I18n.tr("Folder filter"),
                  help: I18n.tr("Show a folder dropdown when the wallpaper folder contains subfolders."),
                  search: ["filterBar.show.folder", "folder", "filter", "toggle"] },
                { id: "filterBar.show.favourites",
                  key: "filterBar.show.favourites",
                  kind: "toggle",
                  label: I18n.tr("Favourites"),
                  help: I18n.tr("Show the button that limits results to favourites."),
                  search: ["filterBar.show.favourites", "favourites", "toggle"] },
                { id: "filterBar.show.random",
                  key: "filterBar.show.random",
                  kind: "toggle",
                  label: I18n.tr("Random rotation"),
                  help: I18n.tr("Show the button that starts or stops random rotation."),
                  search: ["filterBar.show.random", "random", "rotation", "toggle"] },
                { id: "filterBar.show.colors",
                  key: "filterBar.show.colors",
                  kind: "toggle",
                  label: I18n.tr("Colour filters"),
                  help: I18n.tr("Show the colour swatches used to filter wallpapers by their dominant colour."),
                  search: ["filterBar.show.colors", "colour", "filters", "toggle"] },
                { id: "filterBar.show.theme",
                  key: "filterBar.show.theme",
                  kind: "toggle",
                  label: I18n.tr("Theme toggle"),
                  help: I18n.tr("Show the light and dark theme buttons."),
                  search: ["filterBar.show.theme", "theme", "toggle"] },
                { id: "filterBar.show.tagcloud",
                  key: "filterBar.show.tagcloud",
                  kind: "toggle",
                  label: I18n.tr("Search button"),
                  help: I18n.tr("Show the button that opens tag and description search."),
                  search: ["filterBar.show.tagcloud", "search", "button", "toggle"] },
                { id: "filterBar.show.orient",
                  key: "filterBar.show.orient",
                  kind: "toggle",
                  label: I18n.tr("Shape filter"),
                  help: I18n.tr("Show the button that filters wallpapers by shape."),
                  search: ["filterBar.show.orient", "shape", "filter", "toggle"] },
                { id: "filterBar.show.playlists",
                  key: "filterBar.show.playlists",
                  kind: "toggle",
                  label: I18n.tr("Playlist button"),
                  help: I18n.tr("Show the button that opens playlists."),
                  search: ["filterBar.show.playlists", "playlist", "button", "toggle"] },
                { id: "filterBar.show.download",
                  key: "filterBar.show.download",
                  kind: "toggle",
                  label: I18n.tr("Download button"),
                  help: I18n.tr("Show the button that opens wallpaper downloads when a source is enabled."),
                  search: ["filterBar.show.download", "download", "button", "toggle"] },
                { id: "filterBar.show.resolution",
                  key: "filterBar.show.resolution",
                  kind: "toggle",
                  label: I18n.tr("Resolution filter"),
                  help: I18n.tr("Show the cycling resolution-range button when presets exist."),
                  search: ["filterBar.show.resolution", "resolution", "filter", "toggle"] }
            ]
        },
        {
            title: I18n.tr("Resolution presets"),
            subtitle: "",
            controls: [
                { id: "filterBar.resolutionPresets.add",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Add a size band"),
                  help: I18n.tr("Choose a size to add a ready-to-use preset. Expand it to change orientation, rename it, or set a custom range."),
                  options: [{ value: "fhd", label: I18n.tr("1080p") }, { value: "qhd", label: I18n.tr("1440p") }, { value: "4k", label: I18n.tr("4K") }, { value: "5k", label: I18n.tr("5K") }, { value: "8k", label: I18n.tr("8K+") }, { value: "custom", label: I18n.tr("Custom range") }],
                  action: ["CreateResolutionPresetBand(fhd)", "CreateResolutionPresetBand(qhd)", "CreateResolutionPresetBand(4k)", "CreateResolutionPresetBand(5k)", "CreateResolutionPresetBand(8k)", "CreateResolutionPresetBand(custom)"],
                  search: ["filterBar.resolutionPresets.add", "add", "size", "band", "fhd", "1080p", "qhd", "1440p", "4k", "5k", "8k", "custom", "range", "action"] },
                { id: "filterBar.resolutionPresets.N",
                  key: "filterBar.resolutionPresets.N",
                  kind: "list",
                  label: I18n.tr("Preset %1"),
                  searchTitle: I18n.tr("Resolution preset"),
                  help: I18n.tr("Expand to edit the label and resolution range."),
                  args: ["index"],
                  search: ["filterBar.resolutionPresets.N", "preset", "index", "list"] },
                { id: "filterBar.resolutionPresets.N.label",
                  key: "filterBar.resolutionPresets.N.label",
                  kind: "text",
                  label: I18n.tr("Label in Size button"),
                  help: I18n.tr("The short label shown in the filter bar, for example FHD, 2K, or 4K."),
                  placeholder: I18n.tr("e.g. 4K"),
                  details: "filterBar.resolutionPresets.N",
                  search: ["filterBar.resolutionPresets.N.label", "label", "in", "size", "button", "text"] },
                { id: "filterBar.resolutionPresets.N.orientation",
                  key: "filterBar.resolutionPresets.N.orientation",
                  kind: "chips",
                  label: I18n.tr("Orientation"),
                  help: I18n.tr("Show this preset only for wide or tall wallpapers."),
                  options: [{ value: "wide", label: I18n.tr("Wide") }, { value: "tall", label: I18n.tr("Tall") }],
                  details: "filterBar.resolutionPresets.N",
                  search: ["filterBar.resolutionPresets.N.orientation", "orientation", "wide", "tall", "chips"] },
                { id: "filterBar.resolutionPresets.N.custom",
                  key: "filterBar.resolutionPresets.N.custom",
                  kind: "list",
                  label: I18n.tr("Custom range"),
                  help: I18n.tr("Set the minimum and maximum dimensions in pixels. Both dimensions must fall within the range."),
                  details: "filterBar.resolutionPresets.N",
                  search: ["filterBar.resolutionPresets.N.custom", "custom", "range", "list"] },
                { id: "filterBar.resolutionPresets.N.from",
                  key: "filterBar.resolutionPresets.N.from",
                  kind: "number",
                  label: I18n.tr("Minimum size"),
                  help: I18n.tr("Smallest width and height included in this preset."),
                  placeholder: I18n.tr("Width / Height"),
                  details: "filterBar.resolutionPresets.N.custom",
                  search: ["filterBar.resolutionPresets.N.from", "minimum", "size", "number"] },
                { id: "filterBar.resolutionPresets.N.to",
                  key: "filterBar.resolutionPresets.N.to",
                  kind: "number",
                  label: I18n.tr("Maximum size"),
                  help: I18n.tr("Largest width and height included. Leave both fields empty for no upper limit."),
                  placeholder: I18n.tr("Width / Height"),
                  details: "filterBar.resolutionPresets.N.custom",
                  search: ["filterBar.resolutionPresets.N.to", "maximum", "size", "number"] },
                { id: "filterBar.resolutionPresets.N.remove",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Remove"),
                  help: I18n.tr("Remove this resolution preset."),
                  action: "RemoveResolutionPreset(idx)",
                  details: "filterBar.resolutionPresets.N",
                  search: ["filterBar.resolutionPresets.N.remove", "remove", "action"] }
            ]
        },
        {
            title: I18n.tr("Defaults"),
            subtitle: "",
            controls: [
                { id: "filterBar.defaultFolder",
                  key: "filterBar.defaultFolder",
                  kind: "dropdown",
                  label: I18n.tr("Folder"),
                  help: I18n.tr("All folders shows everything; pick one to filter by default."),
                  options: [{ value: "*", label: I18n.tr("All folders") }, { value: "", label: I18n.tr("Main") }],
                  dynamic: "folders",
                  search: ["filterBar.defaultFolder", "folder", "*", "all", "folders", "main", "dropdown"] },
                { id: "filterBar.sticky",
                  key: "filterBar.sticky",
                  kind: "toggle",
                  label: I18n.tr("Sticky filters"),
                  help: I18n.tr("Keep type, folder, colour, sort, and favourite filters after the picker closes. A remembered folder overrides the default above."),
                  search: ["filterBar.sticky", "sticky", "filters", "toggle"] }
            ]
        },
        {
            title: I18n.tr("Visibility"),
            subtitle: "",
            controls: [
                { id: "general.filterBarAlwaysVisible",
                  key: "general.filterBarAlwaysVisible",
                  kind: "toggle",
                  label: I18n.tr("Always show filter bar"),
                  help: I18n.tr("Keep the filter bar pinned visible instead of auto-hiding."),
                  search: ["general.filterBarAlwaysVisible", "always", "show", "filter", "bar", "toggle"] }
            ]
        },
        {
            title: I18n.tr("Search"),
            subtitle: "",
            controls: [
                { id: "semantic.enabled",
                  key: "semantic.enabled",
                  kind: "toggle",
                  label: I18n.tr("Enable semantic search"),
                  help: I18n.tr("Search by describing a wallpaper. Turning this off stops model loading and background indexing. Tags and tag filters stay available."),
                  enabledWhen: "available.lens",
                  details: "search.discovery",
                  search: ["semantic.enabled", "enable", "semantic", "search", "toggle"] },
                { id: "tagging.defaultSearchMode",
                  key: "tagging.defaultSearchMode",
                  kind: "dropdown",
                  label: I18n.tr("Open with"),
                  help: I18n.tr("Choose which search field opens first. You can still switch modes from the search panel."),
                  options: [{ value: "tags", label: I18n.tr("Tags") }, { value: "describe", label: I18n.tr("Describe") }],
                  enabledWhen: "available.lens",
                  details: "search.discovery",
                  search: ["tagging.defaultSearchMode", "open", "with", "tags", "describe", "dropdown"] },
                { id: "settings.tagging.describeInfo",
                  key: null,
                  kind: "static",
                  label: I18n.tr("Describe search"),
                  help: I18n.tr("Lens builds the visual index locally. The search model runs only while Describe search is open."),
                  details: "search.discovery",
                  search: ["settings.tagging.describeInfo", "describe", "search", "static"] }
            ]
        },
        {
            title: I18n.tr("Semantic models"),
            subtitle: "",
            visibleWhen: "available.lens",
            controls: [
                { id: "semantic.models.import",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Import model pack"),
                  help: I18n.tr("Choose a semantic-pack.json or .skwdmodel archive. Ryogami validates the pack, installs it, and selects it."),
                  action: "ImportSemanticModel",
                  search: ["semantic.models.import", "import", "model", "pack", "action"] },
                { id: "semantic.manifest",
                  key: "semantic.manifest",
                  kind: "dropdown",
                  label: I18n.tr("Active model"),
                  help: I18n.tr("Changing models switches to a separate index. Search becomes available when the background index task finishes."),
                  options: [{ value: "", label: I18n.tr("SigLIP2 B/16 (default)") }],
                  dynamic: "semanticModels",
                  search: ["semantic.manifest", "active", "model", "siglip2", "16", "default", "dropdown"] },
                { id: "semantic.models.deleteActive",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Delete model"),
                  help: I18n.tr("Delete this model's files from disk. Deleting the selected model also turns off semantic search. Tags are kept."),
                  visibleWhen: "available.lens",
                  action: "DeleteActiveSemanticModel",
                  search: ["semantic.models.deleteActive", "delete", "model", "action"] },
                { id: "semantic.indexProfile",
                  key: "semantic.indexProfile",
                  kind: "chips",
                  label: I18n.tr("Image views"),
                  help: I18n.tr("Full image indexes the whole composition. Composition and crops also indexes a centre crop and both thirds for ultrawide images."),
                  options: [{ value: "full", label: I18n.tr("Full image") }, { value: "multiview", label: I18n.tr("Composition and crops") }],
                  search: ["semantic.indexProfile", "image", "views", "full", "multiview", "composition", "and", "crops", "chips"] },
                { id: "settings.tagging.localIndexing",
                  key: null,
                  kind: "static",
                  label: I18n.tr("Local indexing"),
                  help: I18n.tr("Imported packs are copied into the local model library, with a separate index per model and image-view choice."),
                  search: ["settings.tagging.localIndexing", "local", "indexing", "static"] },
                { id: "semantic.models.N",
                  key: "semantic.models.N",
                  kind: "list",
                  label: I18n.tr("Model %1"),
                  searchTitle: I18n.tr("Semantic search model"),
                  help: I18n.tr("A local Lens model pack available to Describe search."),
                  args: ["index"],
                  search: ["semantic.models.N", "model", "index", "list"] },
                { id: "semantic.models.N.name",
                  key: "semantic.models.N.name",
                  kind: "text",
                  label: I18n.tr("Name"),
                  help: I18n.tr("Choose the name shown in the active-model list."),
                  placeholder: I18n.tr("PE-Core L14 336"),
                  details: "semantic.models.N",
                  search: ["semantic.models.N.name", "name", "text"] },
                { id: "semantic.models.N.manifest",
                  key: "semantic.models.N.manifest",
                  kind: "text",
                  label: I18n.tr("Model manifest"),
                  help: I18n.tr("Enter the full path to this pack's semantic-pack.json file. The pack is referenced in place and is not copied."),
                  placeholder: I18n.tr("/path/to/semantic-pack.json"),
                  details: "semantic.models.N",
                  search: ["semantic.models.N.manifest", "model", "manifest", "text"] },
                { id: "semantic.models.N.delete",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Delete model"),
                  searchTitle: I18n.tr("Delete a listed model"),
                  help: I18n.tr("Delete this model's files from disk. Deleting the selected model also turns off semantic search. Tags are kept."),
                  action: "DeleteSemanticModel(idx)",
                  details: "semantic.models.N",
                  search: ["semantic.models.N.delete", "delete", "model", "action"] },
                { id: "semantic.models.N.forget",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Forget model"),
                  help: I18n.tr("Remove this reference from the model list. The model files and built index are kept."),
                  action: "RemoveSemanticModel(idx)",
                  details: "semantic.models.N",
                  search: ["semantic.models.N.forget", "forget", "model", "action"] },
                { id: "semantic.models.addManual",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Add manifest manually"),
                  help: I18n.tr("Advanced: reference a semantic-pack.json in place without copying or validating it first."),
                  action: "AddSemanticModel",
                  search: ["semantic.models.addManual", "add", "manifest", "manually", "action"] }
            ]
        }
    ]
}
