import QtQuick
import Ryoku.Ui.Singletons

FolioTabData {
    tabKey: "motion"
    title: I18n.tr("Motion")
    note: I18n.tr("Set shared motion speeds and wallpaper transition timing.")
    sections: [
        {
            title: I18n.tr("Shared speeds"),
            subtitle: "",
            controls: [
                { id: "motion.weights",
                  key: null,
                  kind: "motion",
                  label: I18n.tr("Motion weights"),
                  help: I18n.tr("Fast is used for immediate feedback, Standard for normal movement, and Slow for larger layout changes."),
                  unit: I18n.tr("ms"),
                  search: ["motion.weights", "motion", "fast", "standard", "slow", "weights", "ms"] }
            ]
        },
        {
            title: I18n.tr("Launch"),
            subtitle: "",
            controls: [
                { id: "launch.animation",
                  key: "launch.animation",
                  kind: "dropdown",
                  label: I18n.tr("Animation"),
                  help: I18n.tr("None shows the picker as soon as it exists and is fastest. Fade changes opacity only; Rise and Zoom add movement."),
                  options: [{ value: "none", label: I18n.tr("None") }, { value: "fade", label: I18n.tr("Fade") }, { value: "rise", label: I18n.tr("Rise") }, { value: "zoom", label: I18n.tr("Zoom") }],
                  search: ["launch.animation", "launch", "animation", "none", "fade", "rise", "zoom", "dropdown"] },
                { id: "motion.launchSpeed",
                  key: "motion.launchSpeed",
                  kind: "dropdown",
                  label: I18n.tr("Motion"),
                  help: I18n.tr("The shared picker UI pace. Change the Fast, Standard, and Slow weights in Motion settings."),
                  options: [{ value: "fast", label: I18n.tr("Fast") }, { value: "standard", label: I18n.tr("Standard") }, { value: "slow", label: I18n.tr("Slow") }],
                  search: ["motion.launchSpeed", "launch", "motion", "speed", "fast", "standard", "slow", "dropdown"] },
                { id: "general.openFadeFrom",
                  key: "general.openFadeFrom",
                  kind: "number",
                  label: I18n.tr("Fade from"),
                  help: I18n.tr("Opacity the entrance starts from, in percent. 0 rises from fully transparent."),
                  unit: I18n.tr("%"),
                  search: ["general.openFadeFrom", "launch", "fade", "from", "opacity", "number"] }
            ]
        },
        {
            title: I18n.tr("Picker motion"),
            subtitle: "",
            controls: [
                { id: "motion.filterSwapSpeed",
                  key: "motion.filterSwapSpeed",
                  kind: "dropdown",
                  label: I18n.tr("Filter motion"),
                  help: I18n.tr("How quickly the roll runs when filter results change. The three shared weights live in Motion settings."),
                  options: [{ value: "fast", label: I18n.tr("Fast") }, { value: "standard", label: I18n.tr("Standard") }, { value: "slow", label: I18n.tr("Slow") }],
                  search: ["motion.filterSwapSpeed", "filter", "motion", "fast", "standard", "slow", "dropdown"] },
                { id: "components.wallpaperSelector.flipEffect",
                  key: "components.wallpaperSelector.flipEffect",
                  kind: "dropdown",
                  label: I18n.tr("Effect"),
                  help: I18n.tr("The thumbnail shader used during the first phase."),
                  options: [{ value: "Ignite", label: I18n.tr("Ignite") }, { value: "Edge Fracture", label: I18n.tr("Edge Fracture") }, { value: "Tonal Wipe", label: I18n.tr("Tonal Wipe") }, { value: "Ash", label: I18n.tr("Ash") }, { value: "Depth Parallax", label: I18n.tr("Depth Parallax") }, { value: "Bokeh Bloom", label: I18n.tr("Bokeh Bloom") }, { value: "Light Streaks", label: I18n.tr("Light Streaks") }, { value: "Voxel Extrude", label: I18n.tr("Voxel Extrude") }, { value: "Pixel Sort", label: I18n.tr("Pixel Sort") }, { value: "Rack Focus", label: I18n.tr("Rack Focus") }, { value: "Topographic", label: I18n.tr("Topographic") }, { value: "Tonal Layers", label: I18n.tr("Tonal Layers") }],
                  search: ["components.wallpaperSelector.flipEffect", "effect", "ignite", "edge", "fracture", "tonal", "wipe", "ash", "depth", "parallax", "bokeh", "bloom", "light", "streaks", "voxel", "extrude", "pixel", "sort", "rack", "focus", "topographic", "layers", "dropdown"] },
                { id: "components.wallpaperSelector.flipShader",
                  key: "components.wallpaperSelector.flipShader",
                  kind: "toggle",
                  label: I18n.tr("Thumbnail shader"),
                  help: I18n.tr("Turn off to skip the thumbnail effect and reveal the back directly."),
                  search: ["components.wallpaperSelector.flipShader", "thumbnail", "shader", "toggle"] },
                { id: "components.wallpaperSelector.flipBackReveal",
                  key: "components.wallpaperSelector.flipBackReveal",
                  kind: "toggle",
                  label: I18n.tr("Back reveal"),
                  help: I18n.tr("Turn off to snap the back panel in after the thumbnail effect finishes."),
                  search: ["components.wallpaperSelector.flipBackReveal", "back", "reveal", "toggle"] },
                { id: "components.wallpaperSelector.flipDurationMs",
                  key: "components.wallpaperSelector.flipDurationMs",
                  kind: "number",
                  label: I18n.tr("Duration override"),
                  help: I18n.tr("Total card-flip time. This intentionally overrides the shared UI motion weights."),
                  unit: I18n.tr("ms"),
                  search: ["components.wallpaperSelector.flipDurationMs", "duration", "override", "ms", "number"] }
            ]
        },
        {
            title: I18n.tr("Wallpaper transitions"),
            subtitle: "",
            controls: [
                { id: "transition.enabled",
                  key: "transition.enabled",
                  kind: "toggle",
                  label: I18n.tr("Enable transitions"),
                  help: I18n.tr("Off cuts straight to the new wallpaper."),
                  search: ["transition.enabled", "enable", "transitions", "toggle"] },
                { id: "transition.durationMs",
                  key: "transition.durationMs",
                  kind: "number",
                  label: I18n.tr("Duration"),
                  help: I18n.tr("Set the total transition time in milliseconds. Sand transitions need at least 4000 ms for the grain movement to remain visible."),
                  unit: I18n.tr("ms"),
                  visibleWhen: "transition.enabled == true",
                  search: ["transition.durationMs", "duration", "milliseconds", "number"] },
                { id: "transition.fps",
                  key: "transition.fps",
                  kind: "number",
                  label: I18n.tr("Transition FPS"),
                  help: I18n.tr("Limit animation frames per second without changing wallpaper playback. Leave empty or enter 0 for each display's refresh rate."),
                  unit: I18n.tr("fps"),
                  visibleWhen: "transition.enabled == true",
                  search: ["transition.fps", "transition", "fps", "rate", "number"] },
                { id: "transition.family",
                  key: "transition.family",
                  kind: "chips",
                  label: I18n.tr("Family"),
                  help: I18n.tr("(dynamic — one of) A different transition every time. | Dissolves and blends, no geometry. | A shape or edge sweeps across the screen. | The image bends, stretches or ripples. | The image shatters, pixelates or smears. | Every pixel becomes a grain and flies into a shape."),
                  options: [{ value: "random", label: I18n.tr("Random") }, { value: "fade", label: I18n.tr("Fade") }, { value: "wipe", label: I18n.tr("Wipe") }, { value: "warp", label: I18n.tr("Warp") }, { value: "break", label: I18n.tr("Break up") }, { value: "sand", label: I18n.tr("Sand") }],
                  visibleWhen: "transition.enabled == true",
                  search: ["transition.family", "family", "random", "fade", "wipe", "warp", "break", "sand", "chips"] },
                { id: "transition.shader",
                  key: "transition.shader",
                  kind: "dropdown",
                  label: I18n.tr("Transition"),
                  help: I18n.tr("%1 in this family. (template — dynamic count of shaders in the selected family)"),
                  args: ["count"],
                  dynamic: "transitions",
                  visibleWhen: "transition.enabled == true && transition.family != random",
                  search: ["transition.shader", "transition", "shader", "family", "dropdown"] },
                { id: "transition.preview",
                  key: "transition.preview",
                  kind: "toggle",
                  label: I18n.tr("Show preview"),
                  help: I18n.tr("Run the transition renderer while this tab is open. Turn it off to stop its CPU and GPU use."),
                  visibleWhen: "transition.enabled == true",
                  search: ["transition.preview", "show", "preview", "renderer", "toggle"] },
                { id: "transition.previewFps",
                  key: "transition.previewFps",
                  kind: "number",
                  label: I18n.tr("Preview frame rate"),
                  help: I18n.tr("The whole picker repaints every preview frame. 30 is smooth; 120 spends about four times the CPU for no visible gain. Capped at Max FPS."),
                  unit: I18n.tr("fps"),
                  visibleWhen: "transition.enabled == true && transition.preview == true",
                  search: ["transition.previewFps", "preview", "frame", "rate", "fps", "number"] },
                { id: "transition.preview.view",
                  key: null,
                  kind: "preview",
                  label: "",
                  help: "",
                  visibleWhen: "transition.enabled == true && transition.preview == true",
                  search: ["transition", "preview"] }
            ]
        },
        {
            title: I18n.tr("Transition performance"),
            subtitle: "",
            controls: [
                { id: "transition.sandPrimary",
                  key: "transition.sandPrimary",
                  kind: "text",
                  label: I18n.tr("Primary monitor"),
                  help: I18n.tr("Output that animates when a shader is set to Primary, e.g. DP-2. Empty uses the first available output."),
                  placeholder: I18n.tr("DP-1"),
                  dynamic: "outputs",
                  visibleWhen: "transition.enabled == true",
                  search: ["transition.sandPrimary", "primary", "monitor", "output", "text"] },
                { id: "transition.shaderScopes.{shader}",
                  key: "transition.shaderScopes.{shader}",
                  kind: "dropdown",
                  label: I18n.tr("(dynamic) pretty(shader) — per shader in the selected family"),
                  help: I18n.tr("All animates this shader on every updated monitor. Primary animates it once and changes the other monitors immediately."),
                  options: [{ value: "all", label: I18n.tr("All monitors") }, { value: "primary", label: I18n.tr("Primary only") }],
                  visibleWhen: "transition.enabled == true",
                  search: ["transition.shaderScopes", "scope", "all", "primary", "monitor", "shader", "dropdown"] },
                { id: "transition.sandQuality",
                  key: "transition.sandQuality",
                  kind: "dropdown",
                  label: I18n.tr("Quality"),
                  help: I18n.tr("Auto runs full resolution at 60 fps on discrete GPUs and Low on integrated. Full is uncapped; Low caps at 30 fps at reduced resolution, about 4.5x cheaper."),
                  options: [{ value: "auto", label: I18n.tr("Auto") }, { value: "full", label: I18n.tr("Full") }, { value: "low", label: I18n.tr("Low") }],
                  visibleWhen: "transition.enabled == true && transition.family == sand",
                  search: ["transition.sandQuality", "quality", "auto", "full", "low", "sand", "dropdown"] },
                { id: "transition.sandSharp",
                  key: "transition.sandSharp",
                  kind: "toggle",
                  label: I18n.tr("Sharpen reduced sand"),
                  help: I18n.tr("FSR1-style sharpen on the lower-resolution sand. Slightly more GPU; only active while quality reduces resolution."),
                  visibleWhen: "transition.enabled == true && transition.family == sand",
                  search: ["transition.sandSharp", "sharpen", "sand", "fsr", "toggle"] }
            ]
        },
        {
            title: I18n.tr("Sandy motion"),
            subtitle: "",
            controls: [
                { id: "components.wallpaperSelector.sandyDuration",
                  key: "components.wallpaperSelector.sandyDuration",
                  kind: "number",
                  label: I18n.tr("Duration"),
                  help: I18n.tr("Total time from the old image starting to leave until the new image finishes assembling."),
                  unit: I18n.tr("ms"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyDuration", "duration", "ms", "number"] },
                { id: "components.wallpaperSelector.sandyBlend",
                  key: "components.wallpaperSelector.sandyBlend",
                  kind: "number",
                  label: I18n.tr("Blend"),
                  help: I18n.tr("Colour sweep length; ring fades run at half this."),
                  unit: I18n.tr("ms"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyBlend", "blend", "ms", "number"] },
                { id: "components.wallpaperSelector.sandyStrands",
                  key: "components.wallpaperSelector.sandyStrands",
                  kind: "number",
                  label: I18n.tr("Ribbons"),
                  help: I18n.tr("Split the grains into more or fewer visible streams."),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyStrands", "ribbons", "strands", "number"] },
                { id: "components.wallpaperSelector.sandyTwist",
                  key: "components.wallpaperSelector.sandyTwist",
                  kind: "number",
                  label: I18n.tr("Twist"),
                  help: I18n.tr("Corkscrew intensity along each ribbon."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyTwist", "twist", "number"] },
                { id: "components.wallpaperSelector.sandyOrbit",
                  key: "components.wallpaperSelector.sandyOrbit",
                  kind: "number",
                  label: I18n.tr("Orbit"),
                  help: I18n.tr("How wide grains spiral around their ribbon."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyOrbit", "orbit", "number"] },
                { id: "components.wallpaperSelector.sandyTurbulence",
                  key: "components.wallpaperSelector.sandyTurbulence",
                  kind: "number",
                  label: I18n.tr("Turbulence"),
                  help: I18n.tr("Random twisting of the ribbon paths."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyTurbulence", "turbulence", "number"] },
                { id: "components.wallpaperSelector.sandyWaist",
                  key: "components.wallpaperSelector.sandyWaist",
                  kind: "number",
                  label: I18n.tr("Waist"),
                  help: I18n.tr("Mid-flight pinch of the streams; lower = tighter throat."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyWaist", "waist", "number"] },
                { id: "components.wallpaperSelector.sandyFront",
                  key: "components.wallpaperSelector.sandyFront",
                  kind: "number",
                  label: I18n.tr("Front"),
                  help: I18n.tr("Stagger when different parts of the old image leave. Higher values keep later regions in place longer."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyFront", "front", "number"] },
                { id: "components.wallpaperSelector.sandyFan",
                  key: "components.wallpaperSelector.sandyFan",
                  kind: "number",
                  label: I18n.tr("Fan"),
                  help: I18n.tr("Stream spread at the edges, or swirl in vortex mode."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyFan", "fan", "number"] },
                { id: "components.wallpaperSelector.sandySwapStyle",
                  key: "components.wallpaperSelector.sandySwapStyle",
                  kind: "dropdown",
                  label: I18n.tr("Swap style"),
                  help: I18n.tr("Choose the path grains follow between the old and new images."),
                  options: [{ value: "vortex", label: I18n.tr("Vortex") }, { value: "hourglass", label: I18n.tr("Hourglass") }, { value: "castle", label: I18n.tr("Sandcastle") }, { value: "saltation", label: I18n.tr("Saltation") }, { value: "pour", label: I18n.tr("Glass pour") }, { value: "orbit", label: I18n.tr("Maelstrom") }, { value: "burst", label: I18n.tr("Burst") }, { value: "weave", label: I18n.tr("Weave") }, { value: "bloom", label: I18n.tr("Bloom") }, { value: "flock", label: I18n.tr("Murmuration") }, { value: "ring", label: I18n.tr("Ring") }],
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandySwapStyle", "swap", "style", "vortex", "hourglass", "sandcastle", "saltation", "glass", "pour", "maelstrom", "burst", "weave", "bloom", "murmuration", "ring", "dropdown"] },
                { id: "components.wallpaperSelector.sandyArc",
                  key: "components.wallpaperSelector.sandyArc",
                  kind: "number",
                  label: I18n.tr("Arc"),
                  help: I18n.tr("Loop size when the corner-loop swap is enabled."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyArc", "arc", "number"] },
                { id: "components.wallpaperSelector.sandySwapLoop",
                  key: "components.wallpaperSelector.sandySwapLoop",
                  kind: "toggle",
                  label: I18n.tr("Corner loop swap"),
                  help: I18n.tr("Interrupting picks loop grains through the top corner instead of lifting into the spinning ring."),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandySwapLoop", "corner", "loop", "swap", "toggle"] },
                { id: "components.wallpaperSelector.sandyOutgoingLive",
                  key: "components.wallpaperSelector.sandyOutgoingLive",
                  kind: "toggle",
                  label: I18n.tr("Outgoing video stays live"),
                  help: I18n.tr("Keep the old video playing while it turns to sand. Video-to-video changes run a second decoder until the transition ends; off carries a frozen frame at no extra cost."),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyOutgoingLive", "outgoing", "video", "live", "toggle"] },
                { id: "components.wallpaperSelector.sandyRingSize",
                  key: "components.wallpaperSelector.sandyRingSize",
                  kind: "number",
                  label: I18n.tr("Size"),
                  help: I18n.tr("Orbit diameter relative to the hero. The ring still follows the hero's aspect ratio; 100 preserves the designed size."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyRingSize", "ring", "size", "number"] },
                { id: "components.wallpaperSelector.sandyRingSpin",
                  key: "components.wallpaperSelector.sandyRingSpin",
                  kind: "number",
                  label: I18n.tr("Spin"),
                  help: I18n.tr("Orbit speed of the band."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyRingSpin", "ring", "spin", "number"] },
                { id: "components.wallpaperSelector.sandyRingWave",
                  key: "components.wallpaperSelector.sandyRingWave",
                  kind: "number",
                  label: I18n.tr("Wave"),
                  help: I18n.tr("Radial waviness rippling through the band."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyRingWave", "ring", "wave", "number"] },
                { id: "components.wallpaperSelector.sandyRingSoft",
                  key: "components.wallpaperSelector.sandyRingSoft",
                  kind: "number",
                  label: I18n.tr("Softness"),
                  help: I18n.tr("Higher values use larger, fainter grains and make the ring less sharply defined."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyRingSoft", "ring", "softness", "number"] },
                { id: "components.wallpaperSelector.sandyRingBlend",
                  key: "components.wallpaperSelector.sandyRingBlend",
                  kind: "number",
                  label: I18n.tr("Ring blend"),
                  help: I18n.tr("Colour sweep length while ringed."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyRingBlend", "ring", "blend", "number"] },
                { id: "components.wallpaperSelector.sandyRingHold",
                  key: "components.wallpaperSelector.sandyRingHold",
                  kind: "number",
                  label: I18n.tr("Settle delay"),
                  help: I18n.tr("How long after the last pick before the ring commits to the hero."),
                  unit: I18n.tr("ms"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyRingHold", "settle", "delay", "hold", "ms", "number"] }
            ]
        }
    ]
}
