import QtQuick
import Ryoku.Ui.Singletons

FolioTabData {
    tabKey: "picker"
    title: I18n.tr("Picker")
    note: I18n.tr("Choose how the wallpaper library opens and how cards are arranged.")
    sections: [
        {
            title: I18n.tr("General"),
            subtitle: "",
            controls: [
                { id: "monitor",
                  key: "monitor",
                  kind: "chips",
                  label: I18n.tr("Picker monitor"),
                  help: I18n.tr("Choose a display, or use whichever monitor is focused when the picker opens. Close and reopen the picker after changing this."),
                  options: [{ value: "", label: I18n.tr("Focused monitor") }],
                  dynamic: "outputs",
                  search: ["monitor", "focused", "chips"] },
                { id: "general.applyOnPickerMonitor",
                  key: "general.applyOnPickerMonitor",
                  kind: "toggle",
                  label: I18n.tr("Apply only on the picker monitor"),
                  help: I18n.tr("Apply wallpapers to the monitor where this picker opened. Choose displays can still target other monitors."),
                  search: ["general.applyOnPickerMonitor", "apply", "only", "picker", "monitor", "toggle"] },
                { id: "general.uiScale",
                  key: "general.uiScale",
                  kind: "number",
                  label: I18n.tr("UI scale"),
                  help: I18n.tr("Scale the entire picker interface. The range is 0.5 to 2.0."),
                  unit: I18n.tr("x"),
                  search: ["general.uiScale", "ui", "scale", "x", "number"] },
                { id: "general.closeOnSelection",
                  key: "general.closeOnSelection",
                  kind: "toggle",
                  label: I18n.tr("Close on selection"),
                  help: I18n.tr("Hide the selector immediately after applying a wallpaper."),
                  search: ["general.closeOnSelection", "close", "on", "selection", "toggle"] },
                { id: "components.wallpaperSelector.startPosition",
                  key: "components.wallpaperSelector.startPosition",
                  kind: "dropdown",
                  label: I18n.tr("Start position"),
                  help: I18n.tr("Open at the beginning, at the last wallpaper you applied, or where you stopped browsing. Uses the current filters."),
                  options: [{ value: "beginning", label: I18n.tr("Beginning") }, { value: "applied", label: I18n.tr("Last applied wallpaper") }, { value: "browsing", label: I18n.tr("Last browsing position") }],
                  search: ["components.wallpaperSelector.startPosition", "start", "position", "beginning", "applied", "browsing", "dropdown"] },
                { id: "general.selectorBackdropOpacity",
                  key: "general.selectorBackdropOpacity",
                  kind: "number",
                  label: I18n.tr("Backdrop dim"),
                  help: I18n.tr("How much the desktop darkens behind the picker."),
                  unit: I18n.tr("%"),
                  search: ["backdrop", "dim", "darken"] }
            ]
        },
        {
            title: I18n.tr("Layout & presets"),
            subtitle: "",
            controls: [
                { id: "components.wallpaperSelector.displayMode",
                  key: "components.wallpaperSelector.displayMode",
                  kind: "chips",
                  label: I18n.tr("Display mode"),
                  help: I18n.tr("Choose how wallpaper cards are arranged in the picker."),
                  options: [{ value: "slices", label: I18n.tr("Slices") }, { value: "depth", label: I18n.tr("Depth") }, { value: "hex", label: I18n.tr("Geometric") }, { value: "wall", label: I18n.tr("Wall") }, { value: "sandy", label: I18n.tr("Sandy") }, { value: "hand", label: I18n.tr("Card hand") }, { value: "collection", label: I18n.tr("Collection") }],
                  search: ["components.wallpaperSelector.displayMode", "display", "mode", "slices", "depth", "hex", "geometric", "wall", "sandy", "hand", "collection", "chips"] },
                { id: "components.wallpaperSelector.presetDraftName",
                  key: "components.wallpaperSelector.presetDraftName",
                  kind: "text",
                  label: I18n.tr("Name"),
                  help: I18n.tr("Rename the selected preset. Save current creates a new preset with an automatic name."),
                  placeholder: I18n.tr("Style name"),
                  enabledWhen: "components.wallpaperSelector.presets",
                  disabledReason: I18n.tr("Save a style first to rename it."),
                  search: ["components.wallpaperSelector.presetDraftName", "preset", "name", "style", "text"] },
                { id: "components.wallpaperSelector.presets",
                  key: null,
                  kind: "presets",
                  label: "",
                  help: "",
                  search: ["components.wallpaperSelector.presets", "presets", "saved", "styles"] },
                { id: "components.wallpaperSelector.hexParallax",
                  key: "components.wallpaperSelector.hexParallax",
                  kind: "toggle",
                  label: I18n.tr("Image parallax"),
                  help: I18n.tr("Shift artwork inside each card as it moves across the view. The image keeps moving through the visible edges."),
                  visibleWhen: "components.wallpaperSelector.displayMode == hex",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexParallax", "image", "parallax", "toggle"] },
                { id: "components.wallpaperSelector.hexCurve",
                  key: "components.wallpaperSelector.hexCurve",
                  kind: "chips",
                  label: I18n.tr("Geometric mode"),
                  help: I18n.tr("Choose whether the whole field stays flat or bends into an arc, wave, S shape, or cylinder."),
                  options: [{ value: "flat", label: I18n.tr("Plane") }, { value: "arc", label: I18n.tr("Bow") }, { value: "wave", label: I18n.tr("Ribbon") }, { value: "s", label: I18n.tr("S sweep") }, { value: "cylinder", label: I18n.tr("Cylinder") }],
                  visibleWhen: "components.wallpaperSelector.displayMode == hex",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexCurve", "geometric", "mode", "flat", "plane", "arc", "bow", "wave", "ribbon", "s", "sweep", "cylinder", "chips"] },
                { id: "components.wallpaperSelector.hexShape",
                  key: "components.wallpaperSelector.hexShape",
                  kind: "chips",
                  label: I18n.tr("Tile family"),
                  help: I18n.tr("Choose a tessellating tile. Diamond and Rhombus wrap one wallpaper in vertical or horizontal geometry."),
                  options: [{ value: "triangle", label: I18n.tr("Triangle") }, { value: "hexagon", label: I18n.tr("Hexagon") }, { value: "diamond", label: I18n.tr("Diamond") }, { value: "rhombus", label: I18n.tr("Rhombus") }],
                  visibleWhen: "components.wallpaperSelector.displayMode == hex",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexShape", "tile", "family", "triangle", "hexagon", "diamond", "rhombus", "chips"] },
                { id: "components.wallpaperSelector.hexArcIntensityX10",
                  key: "components.wallpaperSelector.hexArcIntensityX10",
                  kind: "number",
                  label: I18n.tr("Bend strength"),
                  help: I18n.tr("Move right to make the selected field shape bend more strongly."),
                  visibleWhen: "components.wallpaperSelector.displayMode == hex && hexCurve != flat",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexArcIntensityX10", "bend", "strength", "number"] },
                { id: "components.wallpaperSelector.hexCurveFrequency",
                  key: "components.wallpaperSelector.hexCurveFrequency",
                  kind: "number",
                  label: I18n.tr("Waves"),
                  help: I18n.tr("How many ribbon waves cross the field."),
                  unit: I18n.tr("x"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hex && hexCurve == wave",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexCurveFrequency", "waves", "x", "number"] },
                { id: "components.wallpaperSelector.hexOrbitRadius",
                  key: "components.wallpaperSelector.hexOrbitRadius",
                  kind: "number",
                  label: I18n.tr("Cylinder radius"),
                  help: I18n.tr("Smaller values wrap the field more tightly."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hex && hexCurve == cylinder",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexOrbitRadius", "cylinder", "radius", "px", "number"] },
                { id: "components.wallpaperSelector.hexRows",
                  key: "components.wallpaperSelector.hexRows",
                  kind: "number",
                  label: I18n.tr("Rows"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == hex",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexRows", "rows", "number"] },
                { id: "components.wallpaperSelector.hexCols",
                  key: "components.wallpaperSelector.hexCols",
                  kind: "number",
                  label: I18n.tr("Columns"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == hex",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexCols", "columns", "number"] },
                { id: "components.wallpaperSelector.hexRadius",
                  key: "components.wallpaperSelector.hexRadius",
                  kind: "number",
                  label: I18n.tr("Cell size"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hex",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexRadius", "cell", "size", "px", "number"] },
                { id: "components.wallpaperSelector.hexGapX",
                  key: "components.wallpaperSelector.hexGapX",
                  kind: "number",
                  label: I18n.tr("Horizontal spacing"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hex",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexGapX", "horizontal", "spacing", "px", "number"] },
                { id: "components.wallpaperSelector.hexGapY",
                  key: "components.wallpaperSelector.hexGapY",
                  kind: "number",
                  label: I18n.tr("Vertical spacing"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hex",
                  perMode: true,
                  search: ["components.wallpaperSelector.hexGapY", "vertical", "spacing", "px", "number"] },
                { id: "components.wallpaperSelector.gridLayout",
                  key: "components.wallpaperSelector.gridLayout",
                  kind: "chips",
                  label: I18n.tr("Wall mode"),
                  help: I18n.tr("Choose how Wall arranges cards. Each mode uses different row sizing and scrolling behaviour."),
                  options: [{ value: "uniform", label: I18n.tr("Uniform") }, { value: "brick", label: I18n.tr("Brick") }, { value: "masonry", label: I18n.tr("Masonry") }, { value: "justified", label: I18n.tr("Justified") }, { value: "editorial", label: I18n.tr("Editorial") }, { value: "cylinder", label: I18n.tr("Cylinder") }],
                  visibleWhen: "components.wallpaperSelector.displayMode == wall",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridLayout", "wall", "mode", "uniform", "brick", "masonry", "justified", "editorial", "cylinder", "chips"] },
                { id: "components.wallpaperSelector.gridColumns",
                  key: "components.wallpaperSelector.gridColumns",
                  kind: "number",
                  label: I18n.tr("Columns"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == wall",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridColumns", "columns", "number"] },
                { id: "components.wallpaperSelector.gridRows",
                  key: "components.wallpaperSelector.gridRows",
                  kind: "number",
                  label: I18n.tr("Rows"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == wall",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridRows", "rows", "number"] },
                { id: "components.wallpaperSelector.gridStagger",
                  key: "components.wallpaperSelector.gridStagger",
                  kind: "number",
                  label: I18n.tr("Balance"),
                  help: I18n.tr("Change alternating row offset, or the lead-card size in Editorial mode."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == wall && (gridLayout == brick || gridLayout == editorial)",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridStagger", "balance", "stagger", "number"] },
                { id: "components.wallpaperSelector.gridCylinderBend",
                  key: "components.wallpaperSelector.gridCylinderBend",
                  kind: "number",
                  label: I18n.tr("Curvature"),
                  help: I18n.tr("Positive wraps away; negative bows toward you."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == wall && gridLayout == cylinder",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridCylinderBend", "curvature", "bend", "number"] },
                { id: "components.wallpaperSelector.gridCylinderRadius",
                  key: "components.wallpaperSelector.gridCylinderRadius",
                  kind: "number",
                  label: I18n.tr("Cylinder radius"),
                  help: I18n.tr("Smaller values make the wrap tighter."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == wall && gridLayout == cylinder",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridCylinderRadius", "cylinder", "radius", "px", "number"] },
                { id: "components.wallpaperSelector.gridThumbWidth",
                  key: "components.wallpaperSelector.gridThumbWidth",
                  kind: "number",
                  label: I18n.tr("Card width"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == wall",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridThumbWidth", "card", "width", "px", "number"] },
                { id: "components.wallpaperSelector.gridThumbHeight",
                  key: "components.wallpaperSelector.gridThumbHeight",
                  kind: "number",
                  label: I18n.tr("Card height"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == wall",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridThumbHeight", "card", "height", "px", "number"] },
                { id: "components.wallpaperSelector.gridGapX",
                  key: "components.wallpaperSelector.gridGapX",
                  kind: "number",
                  label: I18n.tr("Horizontal spacing"),
                  help: I18n.tr("Visible edge-to-edge space between columns."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == wall",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridGapX", "horizontal", "spacing", "px", "number"] },
                { id: "components.wallpaperSelector.gridGapY",
                  key: "components.wallpaperSelector.gridGapY",
                  kind: "number",
                  label: I18n.tr("Vertical spacing"),
                  help: I18n.tr("Visible edge-to-edge space between rows."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == wall",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridGapY", "vertical", "spacing", "px", "number"] },
                { id: "components.wallpaperSelector.gridRoundCorners",
                  key: "components.wallpaperSelector.gridRoundCorners",
                  kind: "toggle",
                  label: I18n.tr("Rounded corners"),
                  help: I18n.tr("Off uses straight corners for every Wall card."),
                  visibleWhen: "components.wallpaperSelector.displayMode == wall",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridRoundCorners", "rounded", "corners", "toggle"] },
                { id: "components.wallpaperSelector.gridCornerRadius",
                  key: "components.wallpaperSelector.gridCornerRadius",
                  kind: "number",
                  label: I18n.tr("Corner radius"),
                  help: I18n.tr("Roundness used while rounded corners are enabled."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == wall",
                  perMode: true,
                  search: ["components.wallpaperSelector.gridCornerRadius", "corner", "radius", "px", "number"] },
                { id: "components.wallpaperSelector.sandMeter",
                  key: null,
                  kind: "static",
                  label: I18n.tr("%1 grains/frame  ·  %2"),
                  help: I18n.tr("Grain %1 at a typical centre image · %2 (%3) · %4"),
                  args: ["count", "load", "grain", "card", "tier", "note"],
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["sand", "meter", "grains", "frame", "load", "static"] },
                { id: "components.wallpaperSelector.sandyGrain",
                  key: "components.wallpaperSelector.sandyGrain",
                  kind: "number",
                  label: I18n.tr("Grain size"),
                  help: I18n.tr("Grain size in pixels. 1 means one grain per image pixel and is the heaviest; larger grains look chunkier but cost much less."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyGrain", "grain", "size", "px", "number"] },
                { id: "components.wallpaperSelector.sandyResScale",
                  key: "components.wallpaperSelector.sandyResScale",
                  kind: "number",
                  label: I18n.tr("Render scale"),
                  help: I18n.tr("Render sand at a lower resolution and upscale. Saves less than grain size, because grains are geometry rather than pixels."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyResScale", "render", "scale", "number"] },
                { id: "components.wallpaperSelector.sandyLodAuto",
                  key: "components.wallpaperSelector.sandyLodAuto",
                  kind: "toggle",
                  label: I18n.tr("Auto motion detail"),
                  help: I18n.tr("Increase grain size while scrolling fast. On by default on integrated GPUs, where it cuts motion cost about 3.5x."),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyLodAuto", "auto", "motion", "detail", "lod", "toggle"] },
                { id: "components.wallpaperSelector.sandyLod",
                  key: "components.wallpaperSelector.sandyLod",
                  kind: "number",
                  label: I18n.tr("Motion detail strength"),
                  help: I18n.tr("Max grain multiplier at full scroll speed when motion detail runs."),
                  unit: I18n.tr("x"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyLod", "motion", "detail", "strength", "lod", "number"] },
                { id: "components.wallpaperSelector.sandyCenter",
                  key: "components.wallpaperSelector.sandyCenter",
                  kind: "number",
                  label: I18n.tr("Centre height"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyCenter", "centre", "height", "px", "number"] },
                { id: "components.wallpaperSelector.sandySliceHeight",
                  key: "components.wallpaperSelector.sandySliceHeight",
                  kind: "number",
                  label: I18n.tr("Slice height"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandySliceHeight", "slice", "height", "px", "number"] },
                { id: "components.wallpaperSelector.sandySliceWidth",
                  key: "components.wallpaperSelector.sandySliceWidth",
                  kind: "number",
                  label: I18n.tr("Slice width"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandySliceWidth", "slice", "width", "px", "number"] },
                { id: "components.wallpaperSelector.sandySpacing",
                  key: "components.wallpaperSelector.sandySpacing",
                  kind: "number",
                  label: I18n.tr("Gap"),
                  help: I18n.tr("Gap between skewed slices at their vertical midpoint. 0 makes edges touch; negative values overlap."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandySpacing", "gap", "px", "number"] },
                { id: "components.wallpaperSelector.sandySkew",
                  key: "components.wallpaperSelector.sandySkew",
                  kind: "number",
                  label: I18n.tr("Skew"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandySkew", "skew", "number"] },
                { id: "components.wallpaperSelector.sandyEdgeSpeed",
                  key: "components.wallpaperSelector.sandyEdgeSpeed",
                  kind: "number",
                  label: I18n.tr("Edge scroll"),
                  help: I18n.tr("Carousel pan speed at the screen edges, 100 = default."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == sandy",
                  perMode: true,
                  search: ["components.wallpaperSelector.sandyEdgeSpeed", "edge", "scroll", "number"] },
                { id: "components.wallpaperSelector.handMove",
                  key: "components.wallpaperSelector.handMove",
                  kind: "chips",
                  label: I18n.tr("Deal move"),
                  help: I18n.tr("How cards fly out and the next hand flies in. Cycle walks the enabled moves in order; Random picks one of them each deal. Switch moves off below to leave them out."),
                  options: [{ value: "cycle", label: I18n.tr("Cycle") }, { value: "random", label: I18n.tr("Random") }],
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handMove", "deal", "move", "cycle", "random", "chips"] },
                { id: "components.wallpaperSelector.handMoveCorkscrew",
                  key: "components.wallpaperSelector.handMoveCorkscrew",
                  kind: "toggle",
                  label: I18n.tr("Corkscrew"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handMoveCorkscrew", "corkscrew", "toggle"] },
                { id: "components.wallpaperSelector.handMoveCascade",
                  key: "components.wallpaperSelector.handMoveCascade",
                  kind: "toggle",
                  label: I18n.tr("Cascade"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handMoveCascade", "cascade", "toggle"] },
                { id: "components.wallpaperSelector.handMoveShuffle",
                  key: "components.wallpaperSelector.handMoveShuffle",
                  kind: "toggle",
                  label: I18n.tr("Shuffle"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handMoveShuffle", "shuffle", "toggle"] },
                { id: "components.wallpaperSelector.handMoveRibbon",
                  key: "components.wallpaperSelector.handMoveRibbon",
                  kind: "toggle",
                  label: I18n.tr("Ribbon"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handMoveRibbon", "ribbon", "toggle"] },
                { id: "components.wallpaperSelector.handMoveSpiral",
                  key: "components.wallpaperSelector.handMoveSpiral",
                  kind: "toggle",
                  label: I18n.tr("Spiral"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handMoveSpiral", "spiral", "toggle"] },
                { id: "components.wallpaperSelector.handCount",
                  key: "components.wallpaperSelector.handCount",
                  kind: "number",
                  label: I18n.tr("Cards in hand"),
                  help: I18n.tr("Cards shown at once, 3 to 9."),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handCount", "cards", "hand", "number"] },
                { id: "components.wallpaperSelector.handCardWidth",
                  key: "components.wallpaperSelector.handCardWidth",
                  kind: "number",
                  label: I18n.tr("Card width"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handCardWidth", "card", "width", "px", "number"] },
                { id: "components.wallpaperSelector.handCardHeight",
                  key: "components.wallpaperSelector.handCardHeight",
                  kind: "number",
                  label: I18n.tr("Card height"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handCardHeight", "card", "height", "px", "number"] },
                { id: "components.wallpaperSelector.handSpread",
                  key: "components.wallpaperSelector.handSpread",
                  kind: "number",
                  label: I18n.tr("Fan spread"),
                  help: I18n.tr("Horizontal distance between neighbouring cards. Sizes are design pixels on a 1440 x 900 stage and scale with the screen."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handSpread", "fan", "spread", "px", "number"] },
                { id: "components.wallpaperSelector.handFanAngle",
                  key: "components.wallpaperSelector.handFanAngle",
                  kind: "number",
                  label: I18n.tr("Fan angle"),
                  help: I18n.tr("Yaw added per card away from the centre. 0 keeps every card facing you."),
                  unit: I18n.tr("deg"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handFanAngle", "fan", "angle", "deg", "number"] },
                { id: "components.wallpaperSelector.handFanRoll",
                  key: "components.wallpaperSelector.handFanRoll",
                  kind: "number",
                  label: I18n.tr("Fan roll"),
                  help: I18n.tr("Tilt added per card, like cards splayed in a hand. 0 keeps them upright."),
                  unit: I18n.tr("deg"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handFanRoll", "fan", "roll", "deg", "number"] },
                { id: "components.wallpaperSelector.handArch",
                  key: "components.wallpaperSelector.handArch",
                  kind: "number",
                  label: I18n.tr("Arch"),
                  help: I18n.tr("How far outer cards drop below the centre card."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handArch", "arch", "px", "number"] },
                { id: "components.wallpaperSelector.handCornerRadius",
                  key: "components.wallpaperSelector.handCornerRadius",
                  kind: "number",
                  label: I18n.tr("Corner radius"),
                  help: "",
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handCornerRadius", "corner", "radius", "px", "number"] },
                { id: "components.wallpaperSelector.handSkew",
                  key: "components.wallpaperSelector.handSkew",
                  kind: "number",
                  label: I18n.tr("Skew"),
                  help: I18n.tr("Shear the card outline into a parallelogram, in pixels of horizontal offset."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handSkew", "skew", "px", "number"] },
                { id: "components.wallpaperSelector.handPerspective",
                  key: "components.wallpaperSelector.handPerspective",
                  kind: "number",
                  label: I18n.tr("Perspective"),
                  help: I18n.tr("Camera distance. Lower values exaggerate depth."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handPerspective", "perspective", "px", "number"] },
                { id: "components.wallpaperSelector.handTilt",
                  key: "components.wallpaperSelector.handTilt",
                  kind: "number",
                  label: I18n.tr("Pointer tilt"),
                  help: I18n.tr("How far the whole hand leans toward the pointer. 0 disables the tilt."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handTilt", "pointer", "tilt", "number"] },
                { id: "components.wallpaperSelector.handSpeed",
                  key: "components.wallpaperSelector.handSpeed",
                  kind: "number",
                  label: I18n.tr("Speed"),
                  help: I18n.tr("Deal and flip speed, 100 = default."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handSpeed", "speed", "number"] },
                { id: "components.wallpaperSelector.depthHeight",
                  key: "components.wallpaperSelector.depthHeight",
                  kind: "number",
                  label: I18n.tr("Card height"),
                  help: I18n.tr("Height of the centre card. Large cards shrink to fit the screen."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == depth",
                  perMode: true,
                  search: ["components.wallpaperSelector.depthHeight", "card", "height", "px", "number"] },
                { id: "components.wallpaperSelector.depthWidthPx",
                  key: "components.wallpaperSelector.depthWidthPx",
                  kind: "number",
                  label: I18n.tr("Card width"),
                  help: I18n.tr("Width of the centre card in pixels."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == depth",
                  perMode: true,
                  search: ["components.wallpaperSelector.depthWidthPx", "card", "width", "px", "number"] },
                { id: "components.wallpaperSelector.depthSpacingPx",
                  key: "components.wallpaperSelector.depthSpacingPx",
                  kind: "number",
                  label: I18n.tr("Card spacing"),
                  help: I18n.tr("Distance between card centres in pixels before depth falloff."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == depth",
                  perMode: true,
                  search: ["components.wallpaperSelector.depthSpacingPx", "card", "spacing", "px", "number"] },
                { id: "components.wallpaperSelector.depthCount",
                  key: "components.wallpaperSelector.depthCount",
                  kind: "number",
                  label: I18n.tr("Visible cards"),
                  help: I18n.tr("Maximum number of cards around the current selection."),
                  visibleWhen: "components.wallpaperSelector.displayMode == depth",
                  perMode: true,
                  search: ["components.wallpaperSelector.depthCount", "visible", "cards", "number"] },
                { id: "components.wallpaperSelector.depthFalloffFactor",
                  key: "components.wallpaperSelector.depthFalloffFactor",
                  kind: "number",
                  label: I18n.tr("Depth falloff"),
                  help: I18n.tr("Scale reduction per card away from the centre, from 0 to 1. Zero keeps their sizes equal."),
                  visibleWhen: "components.wallpaperSelector.displayMode == depth",
                  perMode: true,
                  search: ["components.wallpaperSelector.depthFalloffFactor", "depth", "falloff", "number"] },
                { id: "components.wallpaperSelector.depthCorners",
                  key: "components.wallpaperSelector.depthCorners",
                  kind: "number",
                  label: I18n.tr("Corner radius"),
                  help: I18n.tr("Round the card corners. Zero keeps square corners."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == depth",
                  perMode: true,
                  search: ["components.wallpaperSelector.depthCorners", "corner", "radius", "px", "number"] },
                { id: "components.wallpaperSelector.depthSkew",
                  key: "components.wallpaperSelector.depthSkew",
                  kind: "number",
                  label: I18n.tr("Card skew"),
                  help: I18n.tr("Slant the card edges. Zero keeps them upright."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == depth",
                  perMode: true,
                  search: ["components.wallpaperSelector.depthSkew", "card", "skew", "px", "number"] },
                { id: "components.wallpaperSelector.depthNavigationMs",
                  key: "components.wallpaperSelector.depthNavigationMs",
                  kind: "number",
                  label: I18n.tr("Navigation duration"),
                  help: I18n.tr("Time for a navigation movement in milliseconds. Lower values move faster."),
                  unit: I18n.tr("ms"),
                  visibleWhen: "components.wallpaperSelector.displayMode == depth",
                  perMode: true,
                  search: ["components.wallpaperSelector.depthNavigationMs", "navigation", "duration", "ms", "number"] },
                { id: "components.wallpaperSelector.depthSelectionFrame",
                  key: "components.wallpaperSelector.depthSelectionFrame",
                  kind: "toggle",
                  label: I18n.tr("Selection frame"),
                  help: I18n.tr("Draw a highlighted border around the selected card."),
                  visibleWhen: "components.wallpaperSelector.displayMode == depth",
                  perMode: true,
                  search: ["components.wallpaperSelector.depthSelectionFrame", "selection", "frame", "toggle"] },
                { id: "components.wallpaperSelector.depthShadows",
                  key: "components.wallpaperSelector.depthShadows",
                  kind: "toggle",
                  label: I18n.tr("Card shadows"),
                  help: I18n.tr("Draw a shadow behind each card."),
                  visibleWhen: "components.wallpaperSelector.displayMode == depth",
                  perMode: true,
                  search: ["components.wallpaperSelector.depthShadows", "card", "shadows", "toggle"] },
                { id: "components.wallpaperSelector.collectionSize",
                  key: "components.wallpaperSelector.collectionSize",
                  kind: "number",
                  label: I18n.tr("Card size"),
                  help: I18n.tr("Card width as a percentage of screen height."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == collection",
                  perMode: true,
                  search: ["components.wallpaperSelector.collectionSize", "card", "size", "number"] },
                { id: "components.wallpaperSelector.collectionSpacing",
                  key: "components.wallpaperSelector.collectionSpacing",
                  kind: "number",
                  label: I18n.tr("Stack spacing"),
                  help: I18n.tr("Vertical distance between stacked cards as a percentage of card size."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == collection",
                  perMode: true,
                  search: ["components.wallpaperSelector.collectionSpacing", "stack", "spacing", "number"] },
                { id: "components.wallpaperSelector.collectionCount",
                  key: "components.wallpaperSelector.collectionCount",
                  kind: "number",
                  label: I18n.tr("Visible cards"),
                  help: I18n.tr("Maximum number of cards in the stack."),
                  visibleWhen: "components.wallpaperSelector.displayMode == collection",
                  perMode: true,
                  search: ["components.wallpaperSelector.collectionCount", "visible", "cards", "number"] },
                { id: "components.wallpaperSelector.collectionTilt",
                  key: "components.wallpaperSelector.collectionTilt",
                  kind: "number",
                  label: I18n.tr("Stack tilt"),
                  help: I18n.tr("Tilt the stack away from you. Zero shows the cards face-on."),
                  unit: I18n.tr("°"),
                  visibleWhen: "components.wallpaperSelector.displayMode == collection",
                  perMode: true,
                  search: ["components.wallpaperSelector.collectionTilt", "stack", "tilt", "number"] },
                { id: "components.wallpaperSelector.collectionCorners",
                  key: "components.wallpaperSelector.collectionCorners",
                  kind: "number",
                  label: I18n.tr("Corner radius"),
                  help: I18n.tr("Round the card corners. Zero keeps square corners."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == collection",
                  perMode: true,
                  search: ["components.wallpaperSelector.collectionCorners", "corner", "radius", "px", "number"] },
                { id: "components.wallpaperSelector.collectionSpeed",
                  key: "components.wallpaperSelector.collectionSpeed",
                  kind: "number",
                  label: I18n.tr("Motion speed"),
                  help: I18n.tr("Speed of navigation and opening or closing a card. Higher values move faster."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == collection",
                  perMode: true,
                  search: ["components.wallpaperSelector.collectionSpeed", "motion", "speed", "number"] },
                { id: "components.wallpaperSelector.handRibbonAxis",
                  key: "components.wallpaperSelector.handRibbonAxis",
                  kind: "chips",
                  label: I18n.tr("Cut direction"),
                  help: "",
                  options: [{ value: "rows", label: I18n.tr("Rows") }, { value: "columns", label: I18n.tr("Columns") }],
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handRibbonAxis", "cut", "direction", "rows", "columns", "chips"] },
                { id: "components.wallpaperSelector.handRibbons",
                  key: "components.wallpaperSelector.handRibbons",
                  kind: "number",
                  label: I18n.tr("Ribbons"),
                  help: I18n.tr("Number of ribbons per card, 2 to 14."),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handRibbons", "ribbons", "number"] },
                { id: "components.wallpaperSelector.handCut",
                  key: "components.wallpaperSelector.handCut",
                  kind: "chips",
                  label: I18n.tr("Cut angle"),
                  help: "",
                  options: [{ value: "straight", label: I18n.tr("Straight") }, { value: "slant", label: I18n.tr("Slant") }, { value: "steep", label: I18n.tr("Steep") }],
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handCut", "cut", "angle", "straight", "slant", "steep", "chips"] },
                { id: "components.wallpaperSelector.handCutVariance",
                  key: "components.wallpaperSelector.handCutVariance",
                  kind: "chips",
                  label: I18n.tr("Cut variance"),
                  help: I18n.tr("Randomise ribbon widths and angles per card."),
                  options: [{ value: "none", label: I18n.tr("Even") }, { value: "soft", label: I18n.tr("Soft") }, { value: "wild", label: I18n.tr("Wild") }],
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handCutVariance", "cut", "variance", "none", "even", "soft", "wild", "chips"] },
                { id: "components.wallpaperSelector.handGhosts",
                  key: "components.wallpaperSelector.handGhosts",
                  kind: "toggle",
                  label: I18n.tr("Ghost trails"),
                  help: I18n.tr("Blurred, brightened copies trail each card while dealing."),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handGhosts", "ghost", "trails", "toggle"] },
                { id: "components.wallpaperSelector.handBackdrop",
                  key: "components.wallpaperSelector.handBackdrop",
                  kind: "toggle",
                  label: I18n.tr("Blurred backdrop"),
                  help: I18n.tr("Fill the screen with a dark, blurred copy of the selected wallpaper behind the hand."),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handBackdrop", "blurred", "backdrop", "toggle"] },
                { id: "components.wallpaperSelector.handBackdropBlur",
                  key: "components.wallpaperSelector.handBackdropBlur",
                  kind: "number",
                  label: I18n.tr("Backdrop blur"),
                  help: I18n.tr("Blur radius of the backdrop, 100 = default."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handBackdropBlur", "backdrop", "blur", "number"] },
                { id: "components.wallpaperSelector.handBob",
                  key: "components.wallpaperSelector.handBob",
                  kind: "toggle",
                  label: I18n.tr("Idle bob"),
                  help: I18n.tr("Cards drift gently while the picker is open. This keeps the picker animating, so it costs GPU time while idle."),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handBob", "idle", "bob", "toggle"] },
                { id: "components.wallpaperSelector.handRevealFill",
                  key: "components.wallpaperSelector.handRevealFill",
                  kind: "toggle",
                  label: I18n.tr("Preview fills the frame"),
                  help: I18n.tr("When the hand flips to the preview, the cards stretch to tile a full-size picture. Off keeps every card at its own width and height and scales the row to fit."),
                  visibleWhen: "components.wallpaperSelector.displayMode == hand",
                  perMode: true,
                  search: ["components.wallpaperSelector.handRevealFill", "preview", "fills", "frame", "toggle"] },
                { id: "components.wallpaperSelector.sliceHeight",
                  key: "components.wallpaperSelector.sliceHeight",
                  kind: "number",
                  label: I18n.tr("Slice height"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.sliceHeight", "slice", "height", "number"] },
                { id: "components.wallpaperSelector.visibleCount",
                  key: "components.wallpaperSelector.visibleCount",
                  kind: "number",
                  label: I18n.tr("Visible items"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.visibleCount", "visible", "items", "number"] },
                { id: "components.wallpaperSelector.expandedWidth",
                  key: "components.wallpaperSelector.expandedWidth",
                  kind: "number",
                  label: I18n.tr("Selected width"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.expandedWidth", "selected", "width", "number"] },
                { id: "components.wallpaperSelector.sliceWidth",
                  key: "components.wallpaperSelector.sliceWidth",
                  kind: "number",
                  label: I18n.tr("Slice width"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.sliceWidth", "slice", "width", "number"] },
                { id: "components.wallpaperSelector.sliceSpacing",
                  key: "components.wallpaperSelector.sliceSpacing",
                  kind: "number",
                  label: I18n.tr("Gap"),
                  help: I18n.tr("Gap between skewed slices at their vertical midpoint. 0 makes edges touch; negative values overlap."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.sliceSpacing", "gap", "px", "number"] },
                { id: "components.wallpaperSelector.skewOffset",
                  key: "components.wallpaperSelector.skewOffset",
                  kind: "number",
                  label: I18n.tr("Skew"),
                  help: "",
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.skewOffset", "skew", "number"] },
                { id: "components.wallpaperSelector.sliceEdgeTilt",
                  key: "components.wallpaperSelector.sliceEdgeTilt",
                  kind: "number",
                  label: I18n.tr("Edge tilt"),
                  help: I18n.tr("Slant the top and bottom edges. Positive values raise the right edge; negative values raise the left edge."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.sliceEdgeTilt", "edge", "tilt", "px", "number"] },
                { id: "components.wallpaperSelector.sliceParallax",
                  key: "components.wallpaperSelector.sliceParallax",
                  kind: "toggle",
                  label: I18n.tr("Image parallax"),
                  help: I18n.tr("Shift artwork inside each card as it moves across the view. The image keeps moving through the visible edges."),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.sliceParallax", "image", "parallax", "toggle"] },
                { id: "components.wallpaperSelector.sliceShadows",
                  key: "components.wallpaperSelector.sliceShadows",
                  kind: "toggle",
                  label: I18n.tr("Card shadows"),
                  help: I18n.tr("Draw a shadow behind each card."),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.sliceShadows", "card", "shadows", "toggle"] },
                { id: "components.wallpaperSelector.sliceWobble",
                  key: "components.wallpaperSelector.sliceWobble",
                  kind: "toggle",
                  label: I18n.tr("Wobble"),
                  help: I18n.tr("Cards bend in the scroll direction and spring back when scrolling stops. Faster movement also separates the colour channels."),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.sliceWobble", "wobble", "toggle"] },
                { id: "components.wallpaperSelector.sliceWobbleStrength",
                  key: "components.wallpaperSelector.sliceWobbleStrength",
                  kind: "number",
                  label: I18n.tr("Wobble strength"),
                  help: I18n.tr("A value of 100 is the default. A value of 200 doubles the bend and colour separation."),
                  unit: I18n.tr("%"),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.sliceWobbleStrength", "wobble", "strength", "number"] },
                { id: "components.wallpaperSelector.roundCorners",
                  key: "components.wallpaperSelector.roundCorners",
                  kind: "toggle",
                  label: I18n.tr("Round corners"),
                  help: I18n.tr("Apply a corner radius to slice edges."),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.roundCorners", "round", "corners", "toggle"] },
                { id: "components.wallpaperSelector.cornerTL",
                  key: "components.wallpaperSelector.cornerTL",
                  kind: "number",
                  label: I18n.tr("Top-left"),
                  help: I18n.tr("Top-left corner radius. 0 = square."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.cornerTL", "top", "left", "corner", "px", "number"] },
                { id: "components.wallpaperSelector.cornerTR",
                  key: "components.wallpaperSelector.cornerTR",
                  kind: "number",
                  label: I18n.tr("Top-right"),
                  help: I18n.tr("Top-right corner radius. 0 = square."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.cornerTR", "top", "right", "corner", "px", "number"] },
                { id: "components.wallpaperSelector.cornerBR",
                  key: "components.wallpaperSelector.cornerBR",
                  kind: "number",
                  label: I18n.tr("Bottom-right"),
                  help: I18n.tr("Bottom-right corner radius. 0 = square."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.cornerBR", "bottom", "right", "corner", "px", "number"] },
                { id: "components.wallpaperSelector.cornerBL",
                  key: "components.wallpaperSelector.cornerBL",
                  kind: "number",
                  label: I18n.tr("Bottom-left"),
                  help: I18n.tr("Bottom-left corner radius. 0 = square."),
                  unit: I18n.tr("px"),
                  visibleWhen: "components.wallpaperSelector.displayMode == slices",
                  perMode: true,
                  search: ["components.wallpaperSelector.cornerBL", "bottom", "left", "corner", "px", "number"] }
            ]
        },
        {
            title: I18n.tr("Cards & previews"),
            subtitle: "",
            controls: [
                { id: "selector.livePreview",
                  key: "selector.livePreview",
                  kind: "toggle",
                  label: I18n.tr("Preview themes on hover"),
                  help: I18n.tr("Recolour the picker from the wallpaper under the pointer. The current theme returns when the pointer leaves, unless you apply."),
                  search: ["selector.livePreview", "preview", "themes", "hover", "toggle"] },
                { id: "components.wallpaperSelector.showTypeBadges",
                  key: "components.wallpaperSelector.showTypeBadges",
                  kind: "toggle",
                  label: I18n.tr("Show type badges"),
                  help: I18n.tr("Mark wallpaper cards as Pic, Vid, or WE so the file type is visible without opening the card."),
                  search: ["components.wallpaperSelector.showTypeBadges", "show", "type", "badges", "toggle"] },
                { id: "videoPreview.enabled",
                  key: "videoPreview.enabled",
                  kind: "toggle",
                  label: I18n.tr("Enable video preview"),
                  help: I18n.tr("Animate the video itself on hover/selection instead of a static thumbnail."),
                  search: ["videoPreview.enabled", "enable", "video", "preview", "toggle"] },
                { id: "videoPreview.delayMs",
                  key: "videoPreview.delayMs",
                  kind: "number",
                  label: I18n.tr("Preview delay"),
                  help: I18n.tr("Wait this long on hover/selection before the preview starts (ms)."),
                  unit: I18n.tr("ms"),
                  search: ["videoPreview.delayMs", "preview", "delay", "ms", "number"] }
            ]
        },
        {
            title: I18n.tr("Tag panel"),
            subtitle: I18n.tr("Search panel / tag cloud"),
            controls: [
                { id: "components.wallpaperSelector.tagCloudWidth",
                  key: "components.wallpaperSelector.tagCloudWidth",
                  kind: "number",
                  label: I18n.tr("Width"),
                  help: I18n.tr("Width of the search panel."),
                  unit: I18n.tr("px"),
                  search: ["components.wallpaperSelector.tagCloudWidth", "width", "search", "panel", "px", "number"] },
                { id: "components.wallpaperSelector.tagCloudRows",
                  key: "components.wallpaperSelector.tagCloudRows",
                  kind: "dropdown",
                  label: I18n.tr("Clickable tag rows"),
                  help: I18n.tr("How many rows of clickable suggestions open below the search field."),
                  options: [{ value: "1", label: I18n.tr("1 row") }, { value: "2", label: I18n.tr("2 rows") }, { value: "3", label: I18n.tr("3 rows") }],
                  search: ["components.wallpaperSelector.tagCloudRows", "clickable", "tag", "rows", "1", "2", "3", "dropdown"] }
            ]
        },
        {
            title: I18n.tr("Controls"),
            subtitle: "",
            controls: [
                { id: "keys.select",
                  key: "keys.select",
                  kind: "keybind",
                  label: I18n.tr("Select, then apply"),
                  help: "",
                  action: "Select",
                  search: ["keys.select", "click", "select", "then", "apply", "keybind", "text", "shortcut"] },
                { id: "keys.apply",
                  key: "keys.apply",
                  kind: "keybind",
                  label: I18n.tr("Apply wallpaper"),
                  help: "",
                  action: "Apply",
                  search: ["keys.apply", "enter", "apply", "wallpaper", "keybind", "text", "shortcut"] },
                { id: "keys.flip",
                  key: "keys.flip",
                  kind: "keybind",
                  label: I18n.tr("Flip card for details"),
                  help: "",
                  action: "Flip",
                  search: ["keys.flip", "right-click", "flip", "card", "for", "details", "keybind", "text", "shortcut"] },
                { id: "keys.reveal",
                  key: "keys.reveal",
                  kind: "keybind",
                  label: I18n.tr("Flip the hand to preview"),
                  help: "",
                  action: "Reveal",
                  search: ["keys.reveal", "v", "flip", "the", "hand", "to", "preview", "keybind", "text", "reveal", "shortcut"] },
                { id: "keys.favourite",
                  key: "keys.favourite",
                  kind: "keybind",
                  label: I18n.tr("Favourite card"),
                  help: "",
                  action: "Favourite",
                  search: ["keys.favourite", "f", "favourite", "card", "keybind", "text", "shortcut"] },
                { id: "keys.effects",
                  key: "keys.effects",
                  kind: "keybind",
                  label: I18n.tr("Choose displays"),
                  help: "",
                  action: "Effects",
                  search: ["keys.effects", "ctrl+click", "choose", "displays", "keybind", "text", "effects", "shortcut"] },
                { id: "keys.studio",
                  key: "keys.studio",
                  kind: "keybind",
                  label: I18n.tr("Effects studio"),
                  help: "",
                  action: "Studio",
                  search: ["keys.studio", "shift+right-click", "effects", "studio", "keybind", "text", "shortcut"] },
                { id: "keys.sceneProperties",
                  key: "keys.sceneProperties",
                  kind: "keybind",
                  label: I18n.tr("Scene properties"),
                  help: "",
                  action: "SceneProperties",
                  search: ["keys.sceneProperties", "shift+w", "scene", "properties", "keybind", "text", "sceneproperties", "shortcut"] },
                { id: "keys.playlists",
                  key: "keys.playlists",
                  kind: "keybind",
                  label: I18n.tr("Toggle playlists"),
                  help: "",
                  action: "Playlists",
                  search: ["keys.playlists", "p", "toggle", "playlists", "keybind", "text", "shortcut"] },
                { id: "keys.settings",
                  key: "keys.settings",
                  kind: "keybind",
                  label: I18n.tr("Settings panel"),
                  help: "",
                  action: "Settings",
                  search: ["keys.settings", "shift+s", "settings", "panel", "keybind", "text", "shortcut"] },
                { id: "keys.help",
                  key: "keys.help",
                  kind: "keybind",
                  label: I18n.tr("Shortcut sheet"),
                  help: "",
                  action: "Help",
                  search: ["keys.help", "?", "shortcut", "sheet", "keybind", "text", "help"] },
                { id: "keys.themePanel",
                  key: "keys.themePanel",
                  kind: "keybind",
                  label: I18n.tr("Colour panel"),
                  help: "",
                  action: "ThemePanel",
                  search: ["keys.themePanel", "c", "colour", "panel", "keybind", "text", "themepanel", "shortcut"] },
                { id: "keys.downloads",
                  key: "keys.downloads",
                  kind: "keybind",
                  label: I18n.tr("Toggle downloads"),
                  help: "",
                  action: "Downloads",
                  search: ["keys.downloads", "ctrl+d", "toggle", "downloads", "keybind", "text", "shortcut"] },
                { id: "keys.tagCloud",
                  key: "keys.tagCloud",
                  kind: "keybind",
                  label: I18n.tr("Toggle search"),
                  help: "",
                  action: "TagCloud",
                  search: ["keys.tagCloud", "shift+down", "toggle", "search", "keybind", "text", "tagcloud", "shortcut"] },
                { id: "keys.tagMode",
                  key: "keys.tagMode",
                  kind: "keybind",
                  label: I18n.tr("Multi-tag select mode"),
                  help: "",
                  action: "TagMode",
                  search: ["keys.tagMode", "t", "multi", "tag", "select", "mode", "keybind", "text", "tagmode", "shortcut"] },
                { id: "keys.filterBar",
                  key: "keys.filterBar",
                  kind: "keybind",
                  label: I18n.tr("Show/hide filter bar"),
                  help: "",
                  action: "FilterBar",
                  search: ["keys.filterBar", "shift+up", "show", "hide", "filter", "bar", "keybind", "text", "filterbar", "shortcut"] },
                { id: "keys.colorPrev",
                  key: "keys.colorPrev",
                  kind: "keybind",
                  label: I18n.tr("Cycle colour filter left"),
                  help: "",
                  action: "ColorPrev",
                  search: ["keys.colorPrev", "shift+left", "cycle", "colour", "filter", "left", "keybind", "text", "colorprev", "shortcut"] },
                { id: "keys.colorNext",
                  key: "keys.colorNext",
                  kind: "keybind",
                  label: I18n.tr("Cycle colour filter right"),
                  help: "",
                  action: "ColorNext",
                  search: ["keys.colorNext", "shift+right", "cycle", "colour", "filter", "right", "keybind", "text", "colornext", "shortcut"] },
                { id: "keys.typePrev",
                  key: "keys.typePrev",
                  kind: "keybind",
                  label: I18n.tr("Previous wallpaper type"),
                  help: "",
                  action: "TypePrev",
                  search: ["keys.typePrev", "shift+tab", "previous", "wallpaper", "type", "keybind", "text", "typeprev", "shortcut"] },
                { id: "keys.typeNext",
                  key: "keys.typeNext",
                  kind: "keybind",
                  label: I18n.tr("Next wallpaper type"),
                  help: "",
                  action: "TypeNext",
                  search: ["keys.typeNext", "tab", "next", "wallpaper", "type", "keybind", "text", "typenext", "shortcut"] },
                { id: "keys.sortPrev",
                  key: "keys.sortPrev",
                  kind: "keybind",
                  label: I18n.tr("Previous sort"),
                  help: "",
                  action: "SortPrev",
                  search: ["keys.sortPrev", "alt+left", "previous", "sort", "keybind", "text", "sortprev", "shortcut"] },
                { id: "keys.sortNext",
                  key: "keys.sortNext",
                  kind: "keybind",
                  label: I18n.tr("Next sort"),
                  help: "",
                  action: "SortNext",
                  search: ["keys.sortNext", "alt+right", "next", "sort", "keybind", "text", "sortnext", "shortcut"] },
                { id: "keys.randomRotate",
                  key: "keys.randomRotate",
                  kind: "keybind",
                  label: I18n.tr("Toggle random rotation"),
                  help: "",
                  action: "RandomRotate",
                  search: ["keys.randomRotate", "ctrl+r", "toggle", "random", "rotation", "keybind", "text", "randomrotate", "shortcut"] },
                { id: "keys.searchMode",
                  key: "keys.searchMode",
                  kind: "keybind",
                  label: I18n.tr("Switch between Tags and Describe"),
                  help: "",
                  action: "SearchMode",
                  search: ["keys.searchMode", "ctrl+tab", "switch", "between", "tags", "and", "describe", "keybind", "text", "searchmode", "shortcut"] },
                { id: "keys.folderPrev",
                  key: "keys.folderPrev",
                  kind: "keybind",
                  label: I18n.tr("Previous folder"),
                  help: "",
                  action: "FolderPrev",
                  search: ["keys.folderPrev", "ctrl+left", "previous", "folder", "keybind", "text", "folderprev", "shortcut"] },
                { id: "keys.folderNext",
                  key: "keys.folderNext",
                  kind: "keybind",
                  label: I18n.tr("Next folder"),
                  help: "",
                  action: "FolderNext",
                  search: ["keys.folderNext", "ctrl+right", "next", "folder", "keybind", "text", "foldernext", "shortcut"] },
                { id: "keys.folderToggle",
                  key: "keys.folderToggle",
                  kind: "keybind",
                  label: I18n.tr("Toggle All/Main"),
                  help: "",
                  action: "FolderToggle",
                  search: ["keys.folderToggle", "ctrl+m", "toggle", "all", "main", "keybind", "text", "foldertoggle", "shortcut"] },
                { id: "keys.hiddenFolders",
                  key: "keys.hiddenFolders",
                  kind: "keybind",
                  label: I18n.tr("Show/hide hidden folders"),
                  help: "",
                  action: "HiddenFolders",
                  search: ["keys.hiddenFolders", "ctrl+h", "show", "hide", "hidden", "folders", "keybind", "text", "hiddenfolders", "shortcut"] },
                { id: "keys.navLeft",
                  key: "keys.navLeft",
                  kind: "keybind",
                  label: I18n.tr("Navigate left"),
                  help: "",
                  action: "NavLeft",
                  search: ["keys.navLeft", "left", "navigate", "keybind", "text", "navleft", "shortcut"] },
                { id: "keys.navRight",
                  key: "keys.navRight",
                  kind: "keybind",
                  label: I18n.tr("Navigate right"),
                  help: "",
                  action: "NavRight",
                  search: ["keys.navRight", "right", "navigate", "keybind", "text", "navright", "shortcut"] },
                { id: "keys.navUp",
                  key: "keys.navUp",
                  kind: "keybind",
                  label: I18n.tr("Navigate up"),
                  help: "",
                  action: "NavUp",
                  search: ["keys.navUp", "up", "navigate", "keybind", "text", "navup", "shortcut"] },
                { id: "keys.navDown",
                  key: "keys.navDown",
                  kind: "keybind",
                  label: I18n.tr("Navigate down"),
                  help: "",
                  action: "NavDown",
                  search: ["keys.navDown", "down", "navigate", "keybind", "text", "navdown", "shortcut"] },
                { id: "keys.autocomplete",
                  key: "keys.autocomplete",
                  kind: "keybind",
                  label: I18n.tr("Complete tag"),
                  help: "",
                  action: "Autocomplete",
                  search: ["keys.autocomplete", "tab", "complete", "tag", "keybind", "text", "autocomplete", "shortcut"] },
                { id: "keys.sourceWallhaven",
                  key: "keys.sourceWallhaven",
                  kind: "keybind",
                  label: I18n.tr("Switch to Wallhaven"),
                  help: "",
                  action: "SourceWallhaven",
                  search: ["keys.sourceWallhaven", "1", "switch", "to", "wallhaven", "keybind", "text", "sourcewallhaven", "shortcut"] },
                { id: "keys.sourceSteam",
                  key: "keys.sourceSteam",
                  kind: "keybind",
                  label: I18n.tr("Switch to Steam Workshop"),
                  help: "",
                  action: "SourceSteam",
                  search: ["keys.sourceSteam", "2", "switch", "to", "steam", "workshop", "keybind", "text", "sourcesteam", "shortcut"] },
                { id: "keys.sourceUnsplash",
                  key: "keys.sourceUnsplash",
                  kind: "keybind",
                  label: I18n.tr("Switch to Unsplash"),
                  help: "",
                  action: "SourceUnsplash",
                  search: ["keys.sourceUnsplash", "3", "switch", "to", "unsplash", "keybind", "text", "sourceunsplash", "shortcut"] },
                { id: "keys.sourcePexels",
                  key: "keys.sourcePexels",
                  kind: "keybind",
                  label: I18n.tr("Switch to Pexels"),
                  help: "",
                  action: "SourcePexels",
                  search: ["keys.sourcePexels", "4", "switch", "to", "pexels", "keybind", "text", "sourcepexels", "shortcut"] },
                { id: "keys.sourceYoutube",
                  key: "keys.sourceYoutube",
                  kind: "keybind",
                  label: I18n.tr("Switch to YouTube"),
                  help: "",
                  action: "SourceYoutube",
                  search: ["keys.sourceYoutube", "5", "switch", "to", "youtube", "keybind", "text", "sourceyoutube", "shortcut"] },
                { id: "keys.sourceBing",
                  key: "keys.sourceBing",
                  kind: "keybind",
                  label: I18n.tr("Switch to Bing Daily"),
                  help: "",
                  action: "SourceBing",
                  search: ["keys.sourceBing", "6", "switch", "to", "bing", "daily", "keybind", "text", "sourcebing", "shortcut"] },
                { id: "keybinds.conflict.N",
                  key: null,
                  kind: "static",
                  label: I18n.tr("⚠ Conflict"),
                  help: I18n.tr("%1 and %2 both use %3. The first one wins; rebind one of them."),
                  args: ["first", "second", "binding"],
                  search: ["conflict", "static"] },
                { id: "keybinds.fixed.escape",
                  key: null,
                  kind: "static",
                  label: I18n.tr("Escape"),
                  help: I18n.tr("Close the current panel, go back, or quit"),
                  search: ["escape", "close", "panel", "back", "quit", "static"] },
                { id: "keybinds.fixed.scroll",
                  key: null,
                  kind: "static",
                  label: I18n.tr("Scroll"),
                  help: I18n.tr("Browse wallpapers / scroll panels"),
                  search: ["scroll", "browse", "wallpapers", "panels", "static"] },
                { id: "keybinds.fixed.hover",
                  key: null,
                  kind: "static",
                  label: I18n.tr("Hover"),
                  help: I18n.tr("Preview videos"),
                  search: ["hover", "preview", "videos", "static"] },
                { id: "keybinds.reset.action",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Reset to defaults"),
                  help: I18n.tr("Restore every binding to its built-in key or click."),
                  action: "ResetKeybinds",
                  search: ["reset", "defaults", "controls", "action"] }
            ]
        }
    ]
}
