import QtQuick
import Ryoku.Ui.Singletons

FolioTabData {
    tabKey: "playback"
    title: I18n.tr("Playback")
    note: I18n.tr("Control video, Wallpaper Engine, sound, and presentation.")
    sections: [
        {
            title: I18n.tr("Display"),
            subtitle: "",
            controls: [
                { id: "display.fillMode",
                  key: "display.fillMode",
                  kind: "chips",
                  label: I18n.tr("Fill mode"),
                  help: I18n.tr("How the wallpaper is fitted to the screen. Applies to images and videos."),
                  options: [{ value: "fill", label: I18n.tr("Fill") }, { value: "fit", label: I18n.tr("Fit") }, { value: "stretch", label: I18n.tr("Stretch") }, { value: "center", label: I18n.tr("Centre") }, { value: "tile", label: I18n.tr("Tile") }],
                  store: "shell",
                  search: ["display.fillMode", "fill", "mode", "fit", "stretch", "center", "centre", "tile", "chips"] }
            ]
        },
        {
            title: I18n.tr("Video"),
            subtitle: "",
            controls: [
                { id: "wallpaper.video_engine",
                  key: "wallpaper.video_engine",
                  kind: "chips",
                  label: I18n.tr("Video engine"),
                  help: I18n.tr("Ryoku plays videos with its own GPU player by default. The in-shell engine keeps audio inside the desktop."),
                  options: [{ value: "ryogami", label: I18n.tr("Ryoku") }, { value: "in_shell", label: I18n.tr("Ryoku in-shell") }],
                  store: "shell",
                  search: ["wallpaper.video_engine", "video", "engine", "in-shell", "chips"] },
                { id: "playback.overviewOnly",
                  key: "playback.overviewOnly",
                  kind: "toggle",
                  label: I18n.tr("Animate only in the overview"),
                  help: I18n.tr("Pauses animated wallpapers while the overview is closed."),
                  visibleWhen: "cap.overviewState",
                  search: ["animate", "only", "in", "overview", "toggle"] },
                { id: "wallpaper.video_enabled",
                  key: "wallpaper.video_enabled",
                  kind: "toggle",
                  label: I18n.tr("Video wallpapers"),
                  help: I18n.tr("Play video wallpapers. Off shows their still frame instead."),
                  store: "shell",
                  search: ["video", "still"] },
                { id: "features.videoAutoScale",
                  key: "features.videoAutoScale",
                  kind: "toggle",
                  label: I18n.tr("Scale videos to the display"),
                  help: I18n.tr("Decode videos at the display's size instead of their full resolution."),
                  search: ["video", "scale"] },
                { id: "wallpaper.video_transcode",
                  key: "wallpaper.video_transcode",
                  kind: "toggle",
                  label: I18n.tr("Cache a lighter copy"),
                  help: I18n.tr("Re-encode each video once at the size and frame rate below, then play the lighter copy."),
                  store: "shell",
                  search: ["transcode", "re-encode", "video"] },
                { id: "wallpaper.video_transcode_fps",
                  key: "wallpaper.video_transcode_fps",
                  kind: "number",
                  label: I18n.tr("Copy frame rate"),
                  help: I18n.tr("Frame rate of the cached copy."),
                  unit: I18n.tr("fps"),
                  visibleWhen: "wallpaper.video_transcode",
                  store: "shell",
                  search: ["transcode", "fps"] },
                { id: "wallpaper.video_transcode_width",
                  key: "wallpaper.video_transcode_width",
                  kind: "number",
                  label: I18n.tr("Copy width"),
                  help: I18n.tr("Width of the cached copy."),
                  unit: I18n.tr("px"),
                  visibleWhen: "wallpaper.video_transcode",
                  store: "shell",
                  search: ["transcode", "width"] }
            ]
        },
        {
            title: I18n.tr("Audio"),
            subtitle: "",
            controls: [
                { id: "wallpaperMute",
                  key: "wallpaperMute",
                  kind: "toggle",
                  label: I18n.tr("Mute wallpaper audio"),
                  help: I18n.tr("Silence video and Wallpaper Engine audio output."),
                  search: ["wallpaperMute", "mute", "wallpaper", "audio", "toggle"] },
                { id: "wallpaperVolume",
                  key: "wallpaperVolume",
                  kind: "number",
                  label: I18n.tr("Wallpaper volume"),
                  help: I18n.tr("Playback volume for video and Wallpaper Engine audio (0-100). Has no effect while audio is muted."),
                  unit: I18n.tr("%"),
                  search: ["wallpaperVolume", "wallpaper", "volume", "number"] },
                { id: "playback.muteOnOtherAudio",
                  key: "playback.muteOnOtherAudio",
                  kind: "toggle",
                  label: I18n.tr("Pause wallpaper audio while other apps play sound"),
                  help: I18n.tr("Silence video and Wallpaper Engine audio whenever another application is playing sound, and bring it back about a second after it stops. Needs PipeWire or PulseAudio with the pactl command. Mute and volume settings stay as they are."),
                  search: ["playback.muteOnOtherAudio", "pause", "wallpaper", "audio", "other", "apps", "toggle"] }
            ]
        },
        {
            title: I18n.tr("Workshop rendering"),
            subtitle: "",
            controls: [
                { id: "paper.loadTimeoutSeconds",
                  key: "paper.loadTimeoutSeconds",
                  kind: "number",
                  label: I18n.tr("Scene load timeout"),
                  help: I18n.tr("Allow more time for large scenes to load before they start. This does not change animation speed."),
                  unit: I18n.tr("s"),
                  search: ["paper.loadTimeoutSeconds", "scene", "wallpaper", "load", "timeout", "number"] },
                { id: "weRender.fps",
                  key: "weRender.fps",
                  kind: "number",
                  label: I18n.tr("FPS cap"),
                  help: I18n.tr("Maximum frames per second. Lower values reduce CPU/GPU load."),
                  search: ["weRender.fps", "fps", "cap", "number"] },
                { id: "weRender.scaling",
                  key: "weRender.scaling",
                  kind: "dropdown",
                  label: I18n.tr("Default scaling"),
                  help: I18n.tr("How Workshop scenes fit each monitor. Default follows the global fill mode."),
                  options: [{ value: "default", label: I18n.tr("Global default") }, { value: "fill", label: I18n.tr("Fill") }, { value: "fit", label: I18n.tr("Fit") }, { value: "stretch", label: I18n.tr("Stretch") }, { value: "center", label: I18n.tr("Centre") }, { value: "tile", label: I18n.tr("Tile") }, { value: "span", label: I18n.tr("Span") }],
                  search: ["weRender.scaling", "default", "scaling", "global", "fill", "fit", "stretch", "center", "centre", "tile", "span", "dropdown"] },
                { id: "weRender.disableParticles",
                  key: "weRender.disableParticles",
                  kind: "toggle",
                  label: I18n.tr("Disable particles"),
                  help: I18n.tr("Skip particle layers in scenes that use them. This can reduce GPU work, but those scenes will lose part of their animation."),
                  search: ["weRender.disableParticles", "disable", "particles", "toggle"] }
            ]
        },
        {
            title: I18n.tr("Pause"),
            subtitle: "",
            controls: [
                { id: "playback.processEnabled",
                  key: "playback.processEnabled",
                  kind: "toggle",
                  label: I18n.tr("Pause when applications are running"),
                  help: I18n.tr("Pause all displays while a listed process is running."),
                  search: ["playback.processEnabled", "pause", "when", "applications", "are", "running", "toggle"] },
                { id: "playback.processes.choose",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Processes"),
                  help: I18n.tr("See the targets that pause wallpapers and add a running process."),
                  action: "ChooseRunningProcess",
                  search: ["playback.processes.choose", "processes", "action"] },
                { id: "playback.fullscreen",
                  key: "playback.fullscreen",
                  kind: "toggle",
                  label: I18n.tr("Pause on fullscreen"),
                  help: I18n.tr("Pause while a fullscreen window is visible. Requires compositor support."),
                  search: ["playback.fullscreen", "pause", "on", "fullscreen", "toggle"] },
                { id: "playback.maximized",
                  key: "playback.maximized",
                  kind: "toggle",
                  label: I18n.tr("Pause on maximised windows"),
                  help: I18n.tr("Pause when the compositor reports a maximised window."),
                  search: ["playback.maximized", "pause", "on", "maximised", "windows", "toggle"] },
                { id: "playback.fullWidthPause",
                  key: "playback.fullWidthPause",
                  kind: "toggle",
                  label: I18n.tr("Pause on full-width columns"),
                  help: I18n.tr("Pause when the active tiled column covers at least 90% of its display width. Other workspaces do not count."),
                  visibleWhen: "cap.columnFill",
                  search: ["pause", "on", "full", "width", "columns", "toggle"] },
                { id: "playback.fullscreenScope",
                  key: "playback.fullscreenScope",
                  kind: "dropdown",
                  label: I18n.tr("Window pause displays"),
                  help: I18n.tr("Choose whether a window pause condition pauses its display or every display."),
                  options: [{ value: "all", label: I18n.tr("All displays") }, { value: "display", label: I18n.tr("Display containing the window") }],
                  search: ["playback.fullscreenScope", "window", "pause", "displays", "all", "display", "containing", "the", "dropdown"] },
                { id: "playback.resumeDelay",
                  key: "playback.resumeDelay",
                  kind: "number",
                  label: I18n.tr("Resume delay"),
                  help: I18n.tr("Wait after the last automatic pause condition clears. Manual pause stays in effect."),
                  unit: I18n.tr("s"),
                  search: ["playback.resumeDelay", "resume", "delay", "number"] },
                { id: "paper.idlePauseSeconds",
                  key: "paper.idlePauseSeconds",
                  kind: "number",
                  label: I18n.tr("Idle pause"),
                  help: I18n.tr("Pause video decode and audio after this many seconds without input (0 disables). Resumes instantly on activity."),
                  unit: I18n.tr("s"),
                  search: ["paper.idlePauseSeconds", "idle", "pause", "number"] }
            ]
        }
    ]
}
