import QtQuick
import Ryoku.Ui.Singletons

FolioTabData {
    tabKey: "sources"
    title: I18n.tr("Sources")
    note: I18n.tr("Choose where new wallpapers can be found and downloaded.")
    sections: [
        {
            title: I18n.tr("Source providers"),
            subtitle: "",
            controls: [
                { id: "features.wallhaven",
                  key: "features.wallhaven",
                  kind: "toggle",
                  label: I18n.tr("Wallhaven browser"),
                  help: I18n.tr("Browse and download wallpapers from wallhaven.cc."),
                  details: "source.wallhaven",
                  search: ["features.wallhaven", "wallhaven", "browser", "toggle"] },
                { id: "wallhaven.apiKey",
                  key: "wallhaven.apiKey",
                  kind: "text",
                  variant: "secret",
                  label: I18n.tr("API key"),
                  help: I18n.tr("Enter a Wallhaven API key to access account features and NSFW results."),
                  placeholder: I18n.tr("Wallhaven API key (for NSFW)"),
                  details: "source.wallhaven",
                  search: ["wallhaven.apiKey", "api", "key", "text"] },
                { id: "wallhaven.username",
                  key: "wallhaven.username",
                  kind: "text",
                  label: I18n.tr("Username"),
                  help: I18n.tr("Enter your Wallhaven username to browse and download from your collections."),
                  placeholder: I18n.tr("Wallhaven username"),
                  details: "source.wallhaven",
                  search: ["wallhaven.username", "username", "text"] },
                { id: "components.wallpaperSelector.wallhavenColumns",
                  key: "components.wallpaperSelector.wallhavenColumns",
                  kind: "number",
                  label: I18n.tr("Columns"),
                  help: I18n.tr("Number of thumbnails per row."),
                  details: "source.wallhaven",
                  search: ["components.wallpaperSelector.wallhavenColumns", "columns", "number"] },
                { id: "components.wallpaperSelector.wallhavenRows",
                  key: "components.wallpaperSelector.wallhavenRows",
                  kind: "number",
                  label: I18n.tr("Rows"),
                  help: I18n.tr("Number of rows visible at once."),
                  details: "source.wallhaven",
                  search: ["components.wallpaperSelector.wallhavenRows", "rows", "number"] },
                { id: "components.wallpaperSelector.wallhavenThumbWidth",
                  key: "components.wallpaperSelector.wallhavenThumbWidth",
                  kind: "number",
                  label: I18n.tr("Width"),
                  help: I18n.tr("Thumbnail width in pixels."),
                  unit: I18n.tr("px"),
                  details: "source.wallhaven",
                  search: ["components.wallpaperSelector.wallhavenThumbWidth", "width", "number"] },
                { id: "components.wallpaperSelector.wallhavenThumbHeight",
                  key: "components.wallpaperSelector.wallhavenThumbHeight",
                  kind: "number",
                  label: I18n.tr("Height"),
                  help: I18n.tr("Thumbnail height in pixels."),
                  unit: I18n.tr("px"),
                  details: "source.wallhaven",
                  search: ["components.wallpaperSelector.wallhavenThumbHeight", "height", "number"] },
                { id: "sources.wallhaven.showApplyButton",
                  key: "sources.wallhaven.showApplyButton",
                  kind: "toggle",
                  label: I18n.tr("Show Apply button"),
                  help: I18n.tr("Show an Apply button for this source. Change several filters, then press Apply or Enter to send one search request. When off, each filter change searches immediately."),
                  details: "source.wallhaven",
                  search: ["sources.wallhaven.showApplyButton", "show", "apply", "button", "toggle"] },
                { id: "wallhaven.defaults.sort",
                  key: "wallhaven.defaults.sort",
                  kind: "dropdown",
                  label: I18n.tr("Default sort order"),
                  help: I18n.tr("Start each new browser session with these filters. Changes made while browsing last until the browser closes."),
                  options: [{ value: "toplist", label: I18n.tr("Top") }, { value: "hot", label: I18n.tr("Hot") }, { value: "date_added", label: I18n.tr("New") }, { value: "relevance", label: I18n.tr("Relevant") }, { value: "views", label: I18n.tr("Views") }, { value: "favorites", label: I18n.tr("Favourites") }, { value: "random", label: I18n.tr("Random") }],
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.sort", "default", "sort", "order", "toplist", "top", "hot", "date_added", "new", "relevance", "relevant", "views", "favorites", "favourites", "random", "dropdown"] },
                { id: "wallhaven.defaults.topRange",
                  key: "wallhaven.defaults.topRange",
                  kind: "dropdown",
                  label: I18n.tr("Default time range"),
                  help: "",
                  options: [{ value: "1d", label: I18n.tr("Day") }, { value: "3d", label: I18n.tr("3 days") }, { value: "1w", label: I18n.tr("Week") }, { value: "1M", label: I18n.tr("Month") }, { value: "3M", label: I18n.tr("3 months") }, { value: "6M", label: I18n.tr("6 months") }, { value: "1y", label: I18n.tr("Year") }],
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.topRange", "default", "time", "range", "1d", "day", "3d", "days", "1w", "week", "1m", "month", "3m", "months", "6m", "1y", "year", "dropdown"] },
                { id: "wallhaven.defaults.atleast",
                  key: "wallhaven.defaults.atleast",
                  kind: "dropdown",
                  label: I18n.tr("Minimum resolution"),
                  help: "",
                  options: [{ value: "", label: I18n.tr("Any") }, { value: "1920x1080", label: I18n.tr("1080p") }, { value: "2560x1440", label: I18n.tr("2K") }, { value: "3840x2160", label: I18n.tr("4K") }, { value: "5120x2880", label: I18n.tr("5K") }, { value: "7680x4320", label: I18n.tr("8K") }],
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.atleast", "minimum", "resolution", "any", "1920x1080", "1080p", "2560x1440", "2k", "3840x2160", "4k", "5120x2880", "5k", "7680x4320", "8k", "dropdown"] },
                { id: "wallhaven.defaults.atmost",
                  key: "wallhaven.defaults.atmost",
                  kind: "dropdown",
                  label: I18n.tr("Maximum resolution"),
                  help: "",
                  options: [{ value: "", label: I18n.tr("Any") }, { value: "1920x1080", label: I18n.tr("1080p") }, { value: "2560x1440", label: I18n.tr("2K") }, { value: "3840x2160", label: I18n.tr("4K") }, { value: "5120x2880", label: I18n.tr("5K") }, { value: "7680x4320", label: I18n.tr("8K") }],
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.atmost", "maximum", "resolution", "any", "1920x1080", "1080p", "2560x1440", "2k", "3840x2160", "4k", "5120x2880", "5k", "7680x4320", "8k", "dropdown"] },
                { id: "wallhaven.defaults.ratios",
                  key: "wallhaven.defaults.ratios",
                  kind: "dropdown",
                  label: I18n.tr("Default aspect ratio"),
                  help: "",
                  options: [{ value: "", label: I18n.tr("Any") }, { value: "16x9", label: I18n.tr("16:9") }, { value: "16x10", label: I18n.tr("16:10") }, { value: "21x9", label: I18n.tr("21:9") }, { value: "32x9", label: I18n.tr("32:9") }, { value: "4x3", label: I18n.tr("4:3") }],
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.ratios", "default", "aspect", "ratio", "any", "16x9", "16", "16x10", "10", "21x9", "21", "32x9", "32", "4x3", "dropdown"] },
                { id: "wallhaven.defaults.general",
                  key: "wallhaven.defaults.general",
                  kind: "toggle",
                  label: I18n.tr("General"),
                  help: I18n.tr("Include this category when opening Wallhaven. If none are selected, General is used."),
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.general", "general", "toggle"] },
                { id: "wallhaven.defaults.anime",
                  key: "wallhaven.defaults.anime",
                  kind: "toggle",
                  label: I18n.tr("Anime"),
                  help: I18n.tr("Include this category when opening Wallhaven. If none are selected, General is used."),
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.anime", "anime", "toggle"] },
                { id: "wallhaven.defaults.people",
                  key: "wallhaven.defaults.people",
                  kind: "toggle",
                  label: I18n.tr("People"),
                  help: I18n.tr("Include this category when opening Wallhaven. If none are selected, General is used."),
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.people", "people", "toggle"] },
                { id: "wallhaven.defaults.sfw",
                  key: "wallhaven.defaults.sfw",
                  kind: "toggle",
                  label: I18n.tr("SFW"),
                  help: I18n.tr("Include this content when opening the source. Wallhaven uses SFW if no content levels are selected."),
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.sfw", "sfw", "toggle"] },
                { id: "wallhaven.defaults.sketchy",
                  key: "wallhaven.defaults.sketchy",
                  kind: "toggle",
                  label: I18n.tr("Sketchy"),
                  help: I18n.tr("Include this content when opening the source. Wallhaven uses SFW if no content levels are selected."),
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.sketchy", "sketchy", "toggle"] },
                { id: "wallhaven.defaults.nsfw",
                  key: "wallhaven.defaults.nsfw",
                  kind: "toggle",
                  label: I18n.tr("NSFW"),
                  help: I18n.tr("Include this content when opening the source. Wallhaven uses SFW if no content levels are selected."),
                  details: "source.wallhaven",
                  search: ["wallhaven.defaults.nsfw", "nsfw", "toggle"] },
                { id: "sources.unsplash.showApplyButton",
                  key: "sources.unsplash.showApplyButton",
                  kind: "toggle",
                  label: I18n.tr("Show Apply button"),
                  help: I18n.tr("Show an Apply button for this source. Change several filters, then press Apply or Enter to send one search request. When off, each filter change searches immediately."),
                  details: "source.unsplash",
                  search: ["sources.unsplash.showApplyButton", "show", "apply", "button", "toggle"] },
                { id: "sources.unsplash.enabled",
                  key: "sources.unsplash.enabled",
                  kind: "toggle",
                  label: I18n.tr("Enable Unsplash"),
                  help: I18n.tr("Show Unsplash in the download source picker."),
                  details: "source.unsplash",
                  search: ["sources.unsplash.enabled", "enable", "unsplash", "toggle"] },
                { id: "sources.unsplash.accessKey",
                  key: "sources.unsplash.accessKey",
                  kind: "text",
                  label: I18n.tr("Access key"),
                  help: I18n.tr("Your Unsplash application Access Key. Photographer credit and the required download ping are handled automatically."),
                  placeholder: I18n.tr("Unsplash Access Key"),
                  details: "source.unsplash",
                  search: ["sources.unsplash.accessKey", "access", "key", "text"] },
                { id: "sources.pexels.showApplyButton",
                  key: "sources.pexels.showApplyButton",
                  kind: "toggle",
                  label: I18n.tr("Show Apply button"),
                  help: I18n.tr("Show an Apply button for this source. Change several filters, then press Apply or Enter to send one search request. When off, each filter change searches immediately."),
                  details: "source.pexels",
                  search: ["sources.pexels.showApplyButton", "show", "apply", "button", "toggle"] },
                { id: "sources.pexels.enabled",
                  key: "sources.pexels.enabled",
                  kind: "toggle",
                  label: I18n.tr("Enable Pexels"),
                  help: I18n.tr("Show Pexels in the download source picker."),
                  details: "source.pexels",
                  search: ["sources.pexels.enabled", "enable", "pexels", "toggle"] },
                { id: "sources.pexels.apiKey",
                  key: "sources.pexels.apiKey",
                  kind: "text",
                  variant: "secret",
                  label: I18n.tr("API key"),
                  help: I18n.tr("Your Pexels API key. Photographer credit is shown automatically as Pexels requires."),
                  placeholder: I18n.tr("Pexels API Key"),
                  details: "source.pexels",
                  search: ["sources.pexels.apiKey", "api", "key", "text"] },
                { id: "sources.bing.enabled",
                  key: "sources.bing.enabled",
                  kind: "toggle",
                  label: I18n.tr("Enable Bing"),
                  help: I18n.tr("Show Bing Daily in the download source picker."),
                  details: "source.bing",
                  search: ["sources.bing.enabled", "enable", "bing", "toggle"] },
                { id: "sources.bing.market",
                  key: "sources.bing.market",
                  kind: "text",
                  label: I18n.tr("Market"),
                  help: I18n.tr("Bing market/region code, e.g. en-US, en-GB, ja-JP."),
                  placeholder: I18n.tr("en-US"),
                  details: "source.bing",
                  search: ["sources.bing.market", "market", "text"] },
                { id: "features.steam",
                  key: "features.steam",
                  kind: "toggle",
                  label: I18n.tr("Steam Workshop browser"),
                  help: I18n.tr("Browse and install Wallpaper Engine items from Steam Workshop."),
                  details: "source.workshop",
                  search: ["features.steam", "steam", "workshop", "browser", "toggle"] },
                { id: "steam.backend",
                  key: "steam.backend",
                  kind: "dropdown",
                  label: I18n.tr("Method"),
                  help: I18n.tr("Choose whether downloads use the running Steam client or steamcmd. Restart the wallpaper service after changing this."),
                  options: [{ value: "steam", label: I18n.tr("Steam client (Steam running)") }, { value: "steamcmd", label: I18n.tr("steamcmd (no Steam client; needs a one-time login)") }],
                  details: "source.workshop",
                  search: ["steam.backend", "method", "steam", "client", "needs", "steamworks", "and", "running", "steamcmd", "no", "one", "time", "login", "dropdown"] },
                { id: "steam.username",
                  key: "steam.username",
                  kind: "text",
                  label: I18n.tr("Username"),
                  help: I18n.tr("Only used by steamcmd. Enter the Steam account that owns Wallpaper Engine."),
                  placeholder: I18n.tr("Steam username (for steamcmd)"),
                  details: "source.workshop",
                  search: ["steam.username", "username", "text"] },
                { id: "steam.apiKey",
                  key: "steam.apiKey",
                  kind: "text",
                  variant: "secret",
                  label: I18n.tr("API key"),
                  help: I18n.tr("Only needed when steamcmd is used for browsing. The Steam client method browses through the running client without a key."),
                  placeholder: I18n.tr("Steam API key"),
                  details: "source.workshop",
                  search: ["steam.apiKey", "api", "key", "text"] },
                { id: "paths.steamWorkshop",
                  key: "paths.steamWorkshop",
                  kind: "text",
                  variant: "path",
                  label: I18n.tr("Workshop directory"),
                  help: I18n.tr("Where Steam stores Workshop content."),
                  placeholder: I18n.tr("Steam Workshop content path"),
                  details: "source.workshop",
                  search: ["paths.steamWorkshop", "workshop", "directory", "text"] },
                { id: "paths.steamWeAssets",
                  key: "paths.steamWeAssets",
                  kind: "text",
                  variant: "path",
                  label: I18n.tr("WE assets directory"),
                  help: I18n.tr("Wallpaper Engine assets path."),
                  placeholder: I18n.tr("Wallpaper Engine assets path"),
                  details: "source.workshop",
                  search: ["paths.steamWeAssets", "we", "assets", "directory", "text"] },
                { id: "paths.steam",
                  key: "paths.steam",
                  kind: "text",
                  variant: "path",
                  label: I18n.tr("Steam directory"),
                  help: I18n.tr("Steam install root."),
                  placeholder: I18n.tr("Steam install path"),
                  details: "source.workshop",
                  search: ["paths.steam", "steam", "directory", "text"] },
                { id: "components.wallpaperSelector.steamColumns",
                  key: "components.wallpaperSelector.steamColumns",
                  kind: "number",
                  label: I18n.tr("Columns"),
                  help: I18n.tr("Number of thumbnails per row."),
                  details: "source.workshop",
                  search: ["components.wallpaperSelector.steamColumns", "columns", "number"] },
                { id: "components.wallpaperSelector.steamRows",
                  key: "components.wallpaperSelector.steamRows",
                  kind: "number",
                  label: I18n.tr("Rows"),
                  help: I18n.tr("Number of rows visible at once."),
                  details: "source.workshop",
                  search: ["components.wallpaperSelector.steamRows", "rows", "number"] },
                { id: "components.wallpaperSelector.steamThumbWidth",
                  key: "components.wallpaperSelector.steamThumbWidth",
                  kind: "number",
                  label: I18n.tr("Width"),
                  help: I18n.tr("Thumbnail width in pixels."),
                  unit: I18n.tr("px"),
                  details: "source.workshop",
                  search: ["components.wallpaperSelector.steamThumbWidth", "width", "number"] },
                { id: "components.wallpaperSelector.steamThumbHeight",
                  key: "components.wallpaperSelector.steamThumbHeight",
                  kind: "number",
                  label: I18n.tr("Height"),
                  help: I18n.tr("Thumbnail height in pixels."),
                  unit: I18n.tr("px"),
                  details: "source.workshop",
                  search: ["components.wallpaperSelector.steamThumbHeight", "height", "number"] },
                { id: "sources.steam.showApplyButton",
                  key: "sources.steam.showApplyButton",
                  kind: "toggle",
                  label: I18n.tr("Show Apply button"),
                  help: I18n.tr("Show an Apply button for this source. Change several filters, then press Apply or Enter to send one search request. When off, each filter change searches immediately."),
                  details: "source.workshop",
                  search: ["sources.steam.showApplyButton", "show", "apply", "button", "toggle"] },
                { id: "steam.defaults.sort",
                  key: "steam.defaults.sort",
                  kind: "dropdown",
                  label: I18n.tr("Default sort order"),
                  help: I18n.tr("Start each new browser session with these filters. Changes made while browsing last until the browser closes."),
                  options: [{ value: "3", label: I18n.tr("Trend") }, { value: "0", label: I18n.tr("Top") }, { value: "1", label: I18n.tr("New") }, { value: "21", label: I18n.tr("Updated") }, { value: "9", label: I18n.tr("Subscribers") }],
                  details: "source.workshop",
                  search: ["steam.defaults.sort", "default", "sort", "order", "3", "trend", "0", "top", "1", "new", "21", "updated", "9", "subscribers", "dropdown"] },
                { id: "steam.defaults.trendDays",
                  key: "steam.defaults.trendDays",
                  kind: "dropdown",
                  label: I18n.tr("Default time range"),
                  help: "",
                  options: [{ value: "1", label: I18n.tr("1 day") }, { value: "3", label: I18n.tr("3 days") }, { value: "7", label: I18n.tr("7 days") }],
                  details: "source.workshop",
                  search: ["steam.defaults.trendDays", "default", "time", "range", "1", "day", "3", "days", "7", "dropdown"] },
                { id: "steam.defaults.type",
                  key: "steam.defaults.type",
                  kind: "dropdown",
                  label: I18n.tr("Default wallpaper type"),
                  help: "",
                  options: [{ value: "", label: I18n.tr("Scene + Video") }, { value: "Scene", label: I18n.tr("Scene") }, { value: "Video", label: I18n.tr("Video") }],
                  details: "source.workshop",
                  search: ["steam.defaults.type", "default", "wallpaper", "type", "scene", "video", "dropdown"] },
                { id: "steam.defaults.resolution",
                  key: "steam.defaults.resolution",
                  kind: "dropdown",
                  label: I18n.tr("Default resolution"),
                  help: "",
                  options: [{ value: "", label: I18n.tr("Any") }, { value: "1920 x 1080", label: I18n.tr("1080p") }, { value: "2560 x 1440", label: I18n.tr("2K") }, { value: "3840 x 2160", label: I18n.tr("4K") }, { value: "2560 x 1080", label: I18n.tr("UW") }, { value: "3440 x 1440", label: I18n.tr("UWQHD") }, { value: "3840 x 1080", label: I18n.tr("Dual") }],
                  details: "source.workshop",
                  search: ["steam.defaults.resolution", "default", "resolution", "any", "1920 x 1080", "1080p", "2560 x 1440", "2k", "3840 x 2160", "4k", "2560 x 1080", "uw", "3440 x 1440", "uwqhd", "3840 x 1080", "dual", "dropdown"] },
                { id: "steam.defaults.category",
                  key: "steam.defaults.category",
                  kind: "dropdown",
                  label: I18n.tr("Default category"),
                  help: "",
                  options: [{ value: "", label: I18n.tr("All") }, { value: "Abstract", label: I18n.tr("Abstract") }, { value: "Animal", label: I18n.tr("Animal") }, { value: "Anime", label: I18n.tr("Anime") }, { value: "CGI", label: I18n.tr("CGI") }, { value: "Cyberpunk", label: I18n.tr("Cyberpunk") }, { value: "Fantasy", label: I18n.tr("Fantasy") }, { value: "Game", label: I18n.tr("Game") }, { value: "Girls", label: I18n.tr("Girls") }, { value: "Guys", label: I18n.tr("Guys") }, { value: "Landscape", label: I18n.tr("Landscape") }, { value: "Medieval", label: I18n.tr("Medieval") }, { value: "Music", label: I18n.tr("Music") }, { value: "Nature", label: I18n.tr("Nature") }, { value: "Pixel art", label: I18n.tr("Pixel art") }, { value: "Relaxing", label: I18n.tr("Relaxing") }, { value: "Retro", label: I18n.tr("Retro") }, { value: "Sci-Fi", label: I18n.tr("Sci-Fi") }, { value: "Technology", label: I18n.tr("Technology") }, { value: "Vehicle", label: I18n.tr("Vehicle") }],
                  details: "source.workshop",
                  search: ["steam.defaults.category", "default", "category", "all", "abstract", "animal", "anime", "cgi", "cyberpunk", "fantasy", "game", "girls", "guys", "landscape", "medieval", "music", "nature", "pixel art", "pixel", "art", "relaxing", "retro", "sci-fi", "sci", "fi", "technology", "vehicle", "dropdown"] },
                { id: "steam.defaults.nsfw",
                  key: "steam.defaults.nsfw",
                  kind: "toggle",
                  label: I18n.tr("NSFW"),
                  help: I18n.tr("Include this content when opening the source. Wallhaven uses SFW if no content levels are selected."),
                  details: "source.workshop",
                  search: ["steam.defaults.nsfw", "nsfw", "toggle"] },
                { id: "sources.youtube.showApplyButton",
                  key: "sources.youtube.showApplyButton",
                  kind: "toggle",
                  label: I18n.tr("Show Apply button"),
                  help: I18n.tr("Show an Apply button for this source. Change several filters, then press Apply or Enter to send one search request. When off, each filter change searches immediately."),
                  details: "source.youtube",
                  search: ["sources.youtube.showApplyButton", "show", "apply", "button", "toggle"] },
                { id: "sources.youtube.enabled",
                  key: "sources.youtube.enabled",
                  kind: "toggle",
                  label: I18n.tr("Enable YouTube"),
                  help: I18n.tr("Show YouTube in the download source picker."),
                  details: "source.youtube",
                  search: ["sources.youtube.enabled", "enable", "youtube", "toggle"] },
                { id: "sources.youtube.maxHeight",
                  key: "sources.youtube.maxHeight",
                  kind: "number",
                  label: I18n.tr("Max height"),
                  help: I18n.tr("Cap the downloaded resolution. Lower means smaller files and lighter playback."),
                  unit: I18n.tr("px"),
                  details: "source.youtube",
                  search: ["sources.youtube.maxHeight", "max", "height", "number"] },
                { id: "sources.youtube.maxMinutes",
                  key: "sources.youtube.maxMinutes",
                  kind: "number",
                  label: I18n.tr("Clip length"),
                  help: I18n.tr("YouTube loops are often hours long. Download only this many minutes; each video can override this before download. 0 downloads everything."),
                  unit: I18n.tr("min"),
                  details: "source.youtube",
                  search: ["sources.youtube.maxMinutes", "clip", "length", "number"] }
            ]
        }
    ]
}
