import QtQuick
import Ryoku.Ui.Singletons

FolioTabData {
    tabKey: "theme"
    title: I18n.tr("Theme")
    note: I18n.tr("Choose how wallpaper colours are applied to the rest of the desktop.")
    sections: [
        {
            title: I18n.tr("App themes"),
            subtitle: I18n.tr("Recolour supported desktop apps from the wallpaper palette."),
            controls: [
                { id: "app-theme.{appId}",
                  key: null,
                  kind: "appTheme",
                  label: I18n.tr("Apps that follow your colours"),
                  help: I18n.tr("Choose which apps follow your colours. Turning an app off restores its previous theme setup."),
                  args: ["app.name"],
                  action: "SetAppTheme(index, enabled)",
                  search: ["app themes", "app", "follow", "colours", "appTheme"] },
                { id: "action.refreshAppThemes",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Find apps"),
                  help: I18n.tr("Check again after installing an app or changing its configuration."),
                  action: "RefreshAppThemes",
                  search: ["app themes", "find", "apps", "scan", "refresh", "action"] }
            ]
        },
        {
            title: I18n.tr("Behaviour"),
            subtitle: "",
            controls: [
                { id: "theme.policy",
                  key: "theme.policy",
                  kind: "dropdown",
                  label: I18n.tr("Palette behaviour"),
                  help: I18n.tr("Follow wallpaper recolours from each applied wallpaper. Fixed palette uses one chosen palette. Keep current colours leaves the theme alone."),
                  options: [{ value: "wallpaper", label: I18n.tr("Follow wallpaper") }, { value: "fixed", label: I18n.tr("Fixed palette") }, { value: "off", label: I18n.tr("Keep current colours") }],
                  search: ["theme.policy", "palette", "behaviour", "wallpaper", "fixed", "off", "dropdown"] }
            ]
        },
        {
            title: I18n.tr("Palette"),
            subtitle: "",
            controls: [
                { id: "theme.staticTheme",
                  key: "theme.staticTheme",
                  kind: "dropdown",
                  label: I18n.tr("Theme"),
                  help: I18n.tr("Choose a built-in palette, one you saved in the designer, or Custom seeds to generate one from your own colours."),
                  options: [{ value: "custom", label: I18n.tr("Custom seeds") }],
                  dynamic: "themes",
                  visibleWhen: "theme.policy == fixed",
                  search: ["theme.staticTheme", "theme", "palette", "custom", "seeds", "dropdown"] },
                { id: "action.openThemeDesigner.fixed",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Theme designer"),
                  help: I18n.tr("Edit each interface colour on a colour wheel and check the result in a live preview. Saved palettes join the Theme list above."),
                  visibleWhen: "theme.policy == fixed",
                  action: "OpenThemeDesigner",
                  search: ["theme designer", "open", "action"] },
                { id: "theme.customColors",
                  key: "theme.customColors",
                  kind: "text",
                  label: I18n.tr("Custom seed colours"),
                  help: I18n.tr("Comma-separated hex colours, for example #1e1e2e, #89b4fa. Used only with Custom seeds and expanded into a full palette."),
                  placeholder: I18n.tr("#1e1e2e, #89b4fa, #f5c2e7"),
                  visibleWhen: "theme.policy == fixed",
                  search: ["theme.customColors", "custom", "seed", "colours", "hex", "text"] }
            ]
        },
        {
            title: I18n.tr("Palette designer"),
            subtitle: "",
            controls: [
                { id: "action.openThemeDesigner.wallpaper",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Theme designer"),
                  help: I18n.tr("Edit each interface colour on a colour wheel and check the result in a live preview. Saved palettes join the Theme list above."),
                  visibleWhen: "theme.policy == wallpaper",
                  action: "OpenThemeDesigner",
                  search: ["theme designer", "open", "colour wheel", "action"] }
            ]
        },
        {
            title: I18n.tr("Appearance (Matugen)"),
            subtitle: "",
            controls: [
                { id: "matugen.schemeType",
                  key: "matugen.schemeType",
                  kind: "dropdown",
                  label: I18n.tr("Colour character"),
                  help: I18n.tr("The Material 3 scheme used for templates and the interface palette. Smart lets Matugen choose a scheme from the image’s colourfulness. Smart requires Matugen 4.2 or newer."),
                  options: [{ value: "scheme-content", label: I18n.tr("Content") }, { value: "scheme-expressive", label: I18n.tr("Expressive") }, { value: "scheme-fidelity", label: I18n.tr("Fidelity") }, { value: "scheme-fruit-salad", label: I18n.tr("Fruit salad") }, { value: "scheme-monochrome", label: I18n.tr("Monochrome") }, { value: "scheme-neutral", label: I18n.tr("Neutral") }, { value: "scheme-rainbow", label: I18n.tr("Rainbow") }, { value: "scheme-tonal-spot", label: I18n.tr("Tonal spot") }, { value: "scheme-vibrant", label: I18n.tr("Vibrant") }, { value: "scheme-smart", label: I18n.tr("Smart") }],
                  visibleWhen: "theme.policy == wallpaper",
                  search: ["matugen.schemeType", "colour", "character", "material", "smart", "dropdown"] },
                { id: "theme.mode@matugen",
                  key: "theme.mode",
                  kind: "dropdown",
                  label: I18n.tr("Variant"),
                  help: I18n.tr("Auto follows the wallpaper's measured brightness. Smart lets Matugen choose light or dark from the image. Smart requires Matugen 4.2 or newer. Sun follows your real sunrise and sunset instead of the wallpaper."),
                  options: [{ value: "dark", label: I18n.tr("Dark") }, { value: "light", label: I18n.tr("Light") }, { value: "auto", label: I18n.tr("Auto (from wallpaper)") }, { value: "smart", label: I18n.tr("Smart") }, { value: "sun", label: I18n.tr("Sun (follows sunrise/sunset)") }],
                  visibleWhen: "theme.policy == wallpaper",
                  search: ["theme.mode", "variant", "dark", "light", "auto", "smart", "sun", "sunrise", "sunset", "day", "dropdown"] },
                { id: "matugen.colorIndex",
                  key: "matugen.colorIndex",
                  kind: "dropdown",
                  label: I18n.tr("Source colour index"),
                  help: I18n.tr("Which palette slot to use as the seed colour."),
                  options: [{ value: "0", label: I18n.tr("0 (Primary)") }, { value: "1", label: I18n.tr("1") }, { value: "2", label: I18n.tr("2") }, { value: "3", label: I18n.tr("3") }],
                  visibleWhen: "theme.policy == wallpaper",
                  search: ["matugen.colorIndex", "source", "colour", "index", "primary", "dropdown"] },
                { id: "matugen.contrast",
                  key: "matugen.contrast",
                  kind: "text",
                  label: I18n.tr("Contrast"),
                  help: I18n.tr("Matugen contrast. Range -1.0 to 1.0 (0 = standard)."),
                  placeholder: I18n.tr("0.00"),
                  visibleWhen: "theme.policy == wallpaper",
                  search: ["matugen.contrast", "contrast", "text"] },
                { id: "matugen.videoFrame",
                  key: "matugen.videoFrame",
                  kind: "number",
                  label: I18n.tr("Video colour frame"),
                  help: I18n.tr("Which second of a video wallpaper the colours are taken from."),
                  unit: I18n.tr("s"),
                  search: ["video", "frame", "colour"] }
            ]
        },
        {
            title: I18n.tr("Matugen command"),
            subtitle: "",
            controls: [
                { id: "features.matugen",
                  key: "features.matugen",
                  kind: "toggle",
                  label: I18n.tr("Matugen"),
                  help: I18n.tr("Use Matugen for wallpaper colours. Turning this off uses built-in Iris."),
                  search: ["features.matugen", "matugen", "feature", "iris", "toggle"] },
                { id: "defaultMatugenConfig",
                  key: "defaultMatugenConfig",
                  kind: "text",
                  label: I18n.tr("Config path"),
                  help: I18n.tr("Path to an external matugen config file."),
                  placeholder: I18n.tr("/path/to/matugen.config.toml"),
                  search: ["defaultMatugenConfig", "matugen", "config", "path", "text"] },
                { id: "externalMatugenCommand",
                  key: "externalMatugenCommand",
                  kind: "text",
                  label: I18n.tr("Command"),
                  help: I18n.tr("Command used to run Matugen. You can insert %config%, %path%, %scheme%, %mode%, and %index% as placeholders."),
                  placeholder: I18n.tr("matugen -c %config% image %path%"),
                  search: ["externalMatugenCommand", "matugen", "command", "placeholders", "text"] }
            ]
        },
        {
            title: I18n.tr("Theme outputs"),
            subtitle: "",
            controls: [
                { id: "integrations.{idx}.enabled",
                  key: "integrations.{idx}.enabled",
                  kind: "toggle",
                  label: I18n.tr("Run custom output"),
                  help: I18n.tr("Generate this output and run its reload command when colours change. Keep this off after switching to managed theming."),
                  details: "app-themes.custom",
                  search: ["integrations.enabled", "run", "custom", "output", "toggle"] },
                { id: "integrations.{idx}.name",
                  key: "integrations.{idx}.name",
                  kind: "text",
                  label: I18n.tr("Name"),
                  help: I18n.tr("Stable identifier for this integration."),
                  placeholder: I18n.tr("kitty"),
                  details: "app-themes.custom",
                  search: ["integrations.name", "name", "identifier", "text"] },
                { id: "integrations.{idx}.template",
                  key: "integrations.{idx}.template",
                  kind: "text",
                  label: I18n.tr("Template"),
                  help: I18n.tr("Template file rendered by Matugen."),
                  placeholder: I18n.tr("kitty.toml"),
                  details: "app-themes.custom",
                  search: ["integrations.template", "template", "text"] },
                { id: "integrations.{idx}.output",
                  key: "integrations.{idx}.output",
                  kind: "text",
                  label: I18n.tr("Output"),
                  help: I18n.tr("Path where the rendered output is written."),
                  placeholder: I18n.tr("~/.config/kitty/colors.toml"),
                  details: "app-themes.custom",
                  search: ["integrations.output", "output", "path", "text"] },
                { id: "integrations.{idx}.reload",
                  key: "integrations.{idx}.reload",
                  kind: "text",
                  label: I18n.tr("Reload"),
                  help: I18n.tr("Optional shell command to run after the output is written."),
                  placeholder: I18n.tr("kill -SIGUSR1 $(pgrep kitty)"),
                  details: "app-themes.custom",
                  search: ["integrations.reload", "reload", "command", "text"] },
                { id: "integrations.{idx}.livePreview",
                  key: "integrations.{idx}.livePreview",
                  kind: "toggle",
                  label: I18n.tr("Live preview"),
                  help: I18n.tr("Recolour Wall while you hover wallpapers. Turn this off to change colours only after a wallpaper is applied."),
                  details: "app-themes.custom",
                  search: ["integrations.livePreview", "live", "preview", "hover", "toggle"] },
                { id: "action.removeIntegration.{idx}",
                  key: null,
                  kind: "action",
                  label: "",
                  help: I18n.tr("Delete this entry."),
                  action: "RemoveIntegration(idx)",
                  details: "app-themes.custom",
                  search: ["remove", "integration", "delete", "action"] },
                { id: "action.addIntegration",
                  key: null,
                  kind: "action",
                  label: I18n.tr("Add integration"),
                  help: I18n.tr("Add an empty integration, then set its template, output file, and optional reload command."),
                  action: "AddIntegration",
                  details: "app-themes.custom",
                  search: ["add", "integration", "action"] }
            ]
        }
    ]
}
