package main

var settingsSchema = []settingSpec{
	{Key: "components.wallpaperSelector.collectionCorners", Type: "number", Default: float64(2), Min: fp(0.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.collectionCount", Type: "number", Default: float64(7), Min: fp(3.0), Max: fp(11.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.collectionShadows", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.collectionSize", Type: "number", Default: float64(42), Min: fp(15.0), Max: fp(65.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.collectionSpacing", Type: "number", Default: float64(17), Min: fp(5.0), Max: fp(30.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.collectionSpeed", Type: "number", Default: float64(100), Min: fp(25.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.collectionTilt", Type: "number", Default: float64(52), Min: fp(0.0), Max: fp(75.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.cornerBL", Type: "number", Default: float64(18), Min: fp(0.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.cornerBR", Type: "number", Default: float64(18), Min: fp(0.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.cornerTL", Type: "number", Default: float64(18), Min: fp(0.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.cornerTR", Type: "number", Default: float64(18), Min: fp(0.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.depthCorners", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.depthCount", Type: "number", Default: float64(5), Min: fp(3.0), Max: fp(21.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.depthFalloffFactor", Type: "number", Default: 0.05, Min: fp(0.0), Max: fp(1.0)},
	{Key: "components.wallpaperSelector.depthHeight", Type: "number", Default: float64(520), Min: fp(100.0), Max: fp(1600.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.depthNavigationMs", Type: "number", Default: float64(1000), Min: fp(35.0), Max: fp(8000.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.depthSelectionFrame", Type: "bool", Default: false},
	{Key: "components.wallpaperSelector.depthShadows", Type: "bool", Default: false},
	{Key: "components.wallpaperSelector.depthSkew", Type: "number", Default: float64(0), Min: fp(-200.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.depthSpacingPx", Type: "number", Default: float64(280), Min: fp(0.0), Max: fp(4000.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.depthWidthPx", Type: "number", Default: float64(280), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.displayMode", Type: "enum", Default: "slices", Options: []string{"slices", "depth", "hex", "wall", "sandy", "hand", "collection"}},
	{Key: "components.wallpaperSelector.expandedWidth", Type: "number", Default: float64(720), DefaultSmall: float64(500), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.flipBackReveal", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.flipDurationMs", Type: "number", Default: float64(1500), Min: fp(100.0), Max: fp(5000.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.flipEffect", Type: "enum", Default: "Ignite", Options: []string{"Ignite", "Edge Fracture", "Tonal Wipe", "Ash", "Depth Parallax", "Bokeh Bloom", "Light Streaks", "Voxel Extrude", "Pixel Sort", "Rack Focus", "Topographic", "Tonal Layers"}},
	{Key: "components.wallpaperSelector.flipShader", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.gridBorderWidth", Type: "number", Default: float64(2), Min: fp(0.0), Max: fp(20.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridColumns", Type: "number", Default: float64(6), DefaultSmall: float64(4), Min: fp(1.0), Max: fp(24.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridCornerRadius", Type: "number", Default: float64(6), Min: fp(0.0), Max: fp(128.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridCylinderBend", Type: "number", Default: float64(65), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridCylinderRadius", Type: "number", Default: float64(720), Min: fp(150.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridFilterBarOffsetX", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridFilterBarOffsetY", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridFlowFrequency", Type: "number", Default: float64(1), Min: fp(0.1), Max: fp(10.0), Step: fp(0.1)},
	{Key: "components.wallpaperSelector.gridFlowWave", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridGapX", Type: "number", Default: float64(8), Min: fp(0.0), Max: fp(256.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridGapY", Type: "number", Default: float64(8), Min: fp(0.0), Max: fp(256.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridLayout", Type: "enum", Default: "uniform", Options: []string{"uniform", "brick", "masonry", "justified", "editorial", "cylinder"}},
	{Key: "components.wallpaperSelector.gridRoundCorners", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.gridRows", Type: "number", Default: float64(3), Min: fp(1.0), Max: fp(24.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridScaleVariance", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridScatter", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridSearchPanelOffsetX", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridSearchPanelOffsetY", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridSelectedScale", Type: "number", Default: float64(100), Min: fp(10.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridStageDepthAngle", Type: "number", Default: float64(0), Min: fp(-90.0), Max: fp(90.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridStagePerspective", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(4000.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridStageRotation", Type: "number", Default: float64(0), Min: fp(-180.0), Max: fp(180.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridStageScale", Type: "number", Default: float64(100), Min: fp(10.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridStageShearX", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridStageShearY", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridStageX", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridStageY", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridStagger", Type: "number", Default: float64(50), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridThumbHeight", Type: "number", Default: float64(169), DefaultSmall: float64(124), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.gridThumbWidth", Type: "number", Default: float64(300), DefaultSmall: float64(220), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handArch", Type: "number", Default: float64(20), Min: fp(-200.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handBackdrop", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.handBackdropBlur", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handBob", Type: "bool", Default: false},
	{Key: "components.wallpaperSelector.handCardHeight", Type: "number", Default: float64(432), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handCardWidth", Type: "number", Default: float64(168), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handCornerRadius", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handCount", Type: "number", Default: float64(5), Min: fp(2.0), Max: fp(16.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handCut", Type: "enum", Default: "straight", Options: []string{"straight", "slant", "steep"}},
	{Key: "components.wallpaperSelector.handCutVariance", Type: "enum", Default: "none", Options: []string{"none", "soft", "wild"}},
	{Key: "components.wallpaperSelector.handFanAngle", Type: "number", Default: float64(12), Min: fp(-60.0), Max: fp(60.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handFanRoll", Type: "number", Default: 8.5, Min: fp(-45.0), Max: fp(45.0)},
	{Key: "components.wallpaperSelector.handGhosts", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.handMove", Type: "enum", Default: "cycle", Options: []string{"cycle", "random"}},
	{Key: "components.wallpaperSelector.handMoveCascade", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.handMoveCorkscrew", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.handMoveRibbon", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.handMoveShuffle", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.handMoveSpiral", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.handPerspective", Type: "number", Default: float64(1700), Min: fp(400.0), Max: fp(6000.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handRevealFill", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.handRibbonAxis", Type: "enum", Default: "rows", Options: []string{"rows", "columns"}},
	{Key: "components.wallpaperSelector.handRibbons", Type: "number", Default: float64(6), Min: fp(2.0), Max: fp(14.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handSkew", Type: "number", Default: float64(0), Min: fp(-200.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handSpeed", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handSpread", Type: "number", Default: float64(126), Min: fp(0.0), Max: fp(600.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handStageX", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handStageY", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.handTilt", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexArc", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.hexArcIntensity", Type: "number", Default: 1.2, Min: fp(0.0), Max: fp(5.0), Step: fp(0.05)},
	{Key: "components.wallpaperSelector.hexArcIntensityX10", Type: "number", Default: float64(12), Min: fp(0.0), Max: fp(50.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexAspect", Type: "number", Default: float64(100), Min: fp(10.0), Max: fp(400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexCols", Type: "number", Default: float64(7), DefaultSmall: float64(5), Min: fp(1.0), Max: fp(24.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexCurve", Type: "enum", Default: "arc", Options: []string{"flat", "arc", "wave", "s", "cylinder"}},
	{Key: "components.wallpaperSelector.hexCurveFrequency", Type: "number", Default: float64(1), Min: fp(0.25), Max: fp(6.0)},
	{Key: "components.wallpaperSelector.hexFilterBarOffsetX", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexFilterBarOffsetY", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexGapX", Type: "number", Default: float64(6), Min: fp(-100.0), Max: fp(256.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexGapY", Type: "number", Default: float64(6), Min: fp(-100.0), Max: fp(256.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexLens", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(360.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexLensRadius", Type: "number", Default: float64(620), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexOrbit", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(360.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexOrbitRadius", Type: "number", Default: float64(620), Min: fp(100.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexParallax", Type: "bool", Default: false},
	{Key: "components.wallpaperSelector.hexRadius", Type: "number", Default: float64(140), DefaultSmall: float64(100), Min: fp(20.0), Max: fp(800.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexRows", Type: "number", Default: float64(3), Min: fp(1.0), Max: fp(24.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexScatter", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexScrollStep", Type: "number", Default: float64(1), Min: fp(1.0), Max: fp(24.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexSearchPanelOffsetX", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexSearchPanelOffsetY", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexShape", Type: "enum", Default: "hexagon", Options: []string{"triangle", "hexagon", "diamond", "rhombus"}},
	{Key: "components.wallpaperSelector.hexStageDepthAngle", Type: "number", Default: float64(0), Min: fp(-90.0), Max: fp(90.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexStagePerspective", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(4000.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexStageRotation", Type: "number", Default: float64(0), Min: fp(-180.0), Max: fp(180.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexStageScale", Type: "number", Default: float64(100), Min: fp(10.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexStageShearX", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexStageShearY", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexStageX", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexStageY", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexStagger", Type: "number", Default: float64(50), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.hexTwist", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(360.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.lastAppliedKey", Type: "string", Default: ""},
	{Key: "components.wallpaperSelector.presetDraftName", Type: "string", Default: ""},
	{Key: "components.wallpaperSelector.roundCorners", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.sandyArc", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyBlend", Type: "number", Default: float64(700), Min: fp(100.0), Max: fp(4000.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyCenter", Type: "number", Default: float64(440), DefaultSmall: float64(330), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyDuration", Type: "number", Default: float64(1250), Min: fp(200.0), Max: fp(6000.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyEdgeSpeed", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyFan", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyFilterBarOffsetX", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyFilterBarOffsetY", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyFront", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyGrain", Type: "number", Default: float64(3), Min: fp(1.0), Max: fp(32.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyLod", Type: "number", Default: float64(2), Min: fp(1.0), Max: fp(4.0)},
	{Key: "components.wallpaperSelector.sandyLodAuto", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.sandyOrbit", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyOutgoingLive", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.sandyResScale", Type: "number", Default: float64(100), Min: fp(25.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyRingBlend", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyRingHold", Type: "number", Default: float64(200), Min: fp(0.0), Max: fp(3000.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyRingSize", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyRingSoft", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyRingSpin", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyRingWave", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandySearchPanelOffsetX", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandySearchPanelOffsetY", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandySkew", Type: "number", Default: float64(12), DefaultSmall: float64(8), Min: fp(-90.0), Max: fp(90.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandySliceHeight", Type: "number", Default: float64(180), DefaultSmall: float64(130), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandySliceWidth", Type: "number", Default: float64(96), DefaultSmall: float64(68), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandySpacing", Type: "number", Default: float64(26), DefaultSmall: float64(20), Min: fp(0.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyStageX", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyStageY", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyStrands", Type: "number", Default: float64(22), DefaultSmall: float64(18), Min: fp(4.0), Max: fp(64.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandySwapLoop", Type: "bool", Default: false},
	{Key: "components.wallpaperSelector.sandySwapStyle", Type: "enum", Default: "vortex", Options: []string{"vortex", "hourglass", "castle", "saltation", "pour", "orbit", "burst", "weave", "bloom", "flock", "ring"}},
	{Key: "components.wallpaperSelector.sandyTurbulence", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyTwist", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sandyWaist", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.showTypeBadges", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.shadowDistance", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.shadowStrength", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.skewOffset", Type: "number", Default: float64(0), DefaultSmall: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceEdgeTilt", Type: "number", Default: float64(0), Min: fp(-240.0), Max: fp(240.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceFilterBarOffsetX", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceFilterBarOffsetY", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceHeight", Type: "number", Default: float64(520), DefaultSmall: float64(360), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceParallax", Type: "bool", Default: false},
	{Key: "components.wallpaperSelector.sliceSearchPanelOffsetX", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceSearchPanelOffsetY", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceShadows", Type: "bool", Default: true},
	{Key: "components.wallpaperSelector.sliceSpacing", Type: "number", Default: float64(20), Min: fp(0.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceStageX", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceStageY", Type: "number", Default: float64(0), Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceWidth", Type: "number", Default: float64(170), DefaultSmall: float64(110), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.sliceWobble", Type: "bool", Default: false},
	{Key: "components.wallpaperSelector.sliceWobbleStrength", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(300.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.startPosition", Type: "enum", Default: "beginning", Options: []string{"beginning", "applied", "browsing"}},
	{Key: "components.wallpaperSelector.steamColumns", Type: "number", Default: float64(6), Min: fp(1.0), Max: fp(24.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.steamRows", Type: "number", Default: float64(3), Min: fp(1.0), Max: fp(24.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.steamThumbHeight", Type: "number", Default: float64(169), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.steamThumbWidth", Type: "number", Default: float64(300), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.tagCloudHeight", Type: "number", Default: float64(168), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.tagCloudOffsetX", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.tagCloudOffsetY", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.tagCloudRows", Type: "enum", Default: "2", Options: []string{"1", "2", "3"}},
	{Key: "components.wallpaperSelector.tagCloudWidth", Type: "number", Default: float64(760), DefaultSmall: float64(540), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.visibleCount", Type: "number", Default: float64(12), DefaultSmall: float64(8), Min: fp(2.0), Max: fp(48.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.wallhavenColumns", Type: "number", Default: float64(6), Min: fp(1.0), Max: fp(24.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.wallhavenRows", Type: "number", Default: float64(3), Min: fp(1.0), Max: fp(24.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.wallhavenThumbHeight", Type: "number", Default: float64(169), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "components.wallpaperSelector.wallhavenThumbWidth", Type: "number", Default: float64(300), Min: fp(40.0), Max: fp(2400.0), Step: fp(1.0)},
	{Key: "defaultMatugenConfig", Type: "string", Default: ""},
	{Key: "display.fillMode", Type: "enum", Default: "fill", Options: []string{"fill", "fit", "stretch", "center", "tile"}, Store: "shell", StoreKey: "wallpaper.content_fit"},
	{Key: "display.fillModes.<output>", Type: "enum", Default: "(inherits display.fillMode)", Options: []string{"fill", "fit", "stretch", "center", "tile", "(inherits display.fillMode)"}},
	{Key: "display.outputLocks.<output>", Type: "bool", Default: false},
	{Key: "display.themeOutput", Type: "string", Default: ""},
	{Key: "effects.autoRecolor", Type: "bool", Default: false},
	{Key: "effects.autoTheme", Type: "string", Default: "Catppuccin"},
	{Key: "externalMatugenCommand", Type: "string", Default: "matugen -c %config% image %path% -t %scheme% -m %mode% --source-color-index %index%"},
	{Key: "features.matugen", Type: "bool", Default: true},
	{Key: "features.steam", Type: "bool", Default: true},
	{Key: "features.videoAutoScale", Type: "bool", Default: true},
	{Key: "features.wallhaven", Type: "bool", Default: true},
	{Key: "filterBar.defaultFolder", Type: "string", Default: "*"},
	{Key: "filterBar.last.showHiddenFolders", Type: "bool", Default: true},
	{Key: "filterBar.offsetX", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "filterBar.offsetY", Type: "number", Default: float64(0), Min: fp(-1200.0), Max: fp(1200.0), Step: fp(1.0)},
	{Key: "filterBar.orientation", Type: "enum", Default: "horizontal", Options: []string{"horizontal", "vertical"}},
	{Key: "filterBar.resolutionPresets", Type: "list", Default: []interface{}{}},
	{Key: "filterBar.show.colors", Type: "bool", Default: true},
	{Key: "filterBar.show.download", Type: "bool", Default: true},
	{Key: "filterBar.show.favourites", Type: "bool", Default: true},
	{Key: "filterBar.show.folder", Type: "bool", Default: true},
	{Key: "filterBar.show.orient", Type: "bool", Default: true},
	{Key: "filterBar.show.playlists", Type: "bool", Default: true},
	{Key: "filterBar.show.random", Type: "bool", Default: true},
	{Key: "filterBar.show.resolution", Type: "bool", Default: true},
	{Key: "filterBar.show.sort.color", Type: "bool", Default: true},
	{Key: "filterBar.show.sort.date", Type: "bool", Default: true},
	{Key: "filterBar.show.sort.minimalist", Type: "bool", Default: true},
	{Key: "filterBar.show.sort.pop", Type: "bool", Default: true},
	{Key: "filterBar.show.sort.recent", Type: "bool", Default: true},
	{Key: "filterBar.show.sort.res", Type: "bool", Default: true},
	{Key: "filterBar.show.sort.richness", Type: "bool", Default: true},
	{Key: "filterBar.show.tagcloud", Type: "bool", Default: true},
	{Key: "filterBar.show.tagging", Type: "bool", Default: true},
	{Key: "filterBar.show.theme", Type: "bool", Default: true},
	{Key: "filterBar.show.type.all", Type: "bool", Default: true},
	{Key: "filterBar.show.type.static", Type: "bool", Default: true},
	{Key: "filterBar.show.type.video", Type: "bool", Default: true},
	{Key: "filterBar.show.type.we", Type: "bool", Default: true},
	{Key: "filterBar.sticky", Type: "bool", Default: false},
	{Key: "filterBar.visualStyle", Type: "enum", Default: "match", Options: []string{"match", "slices", "hex", "wall"}},
	{Key: "general.applyOnPickerMonitor", Type: "bool", Default: false},
	{Key: "general.closeOnSelection", Type: "bool", Default: false},
	{Key: "general.filterBarAlwaysVisible", Type: "bool", Default: true},
	{Key: "general.language", Type: "string", Default: "", Store: "shell", StoreKey: "language"},
	{Key: "general.locale", Type: "string", Default: ""},
	{Key: "general.maxFps", Type: "number", Default: float64(120), Min: fp(1.0), Max: fp(1000.0), Step: fp(1.0)},
	{Key: "general.notifyOnWallpaperChange", Type: "bool", Default: true},
	{Key: "general.openFadeFrom", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "general.randomIncludeFavourites", Type: "bool", Default: true},
	{Key: "general.randomIncludeStatic", Type: "bool", Default: true},
	{Key: "general.randomIncludeVideo", Type: "bool", Default: true},
	{Key: "general.randomIncludeWE", Type: "bool", Default: true},
	{Key: "general.randomInterval", Type: "number", Default: float64(300), Min: fp(5.0), Max: fp(86400.0), Step: fp(1.0)},
	{Key: "general.randomRotate", Type: "bool", Default: false},
	{Key: "general.selectorBackdropOpacity", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "general.uiScale", Type: "number", Default: float64(1), Min: fp(0.5), Max: fp(2.0), Step: fp(0.05)},
	{Key: "general.weatherMatch", Type: "bool", Default: false},
	{Key: "integrations", Type: "list", Default: []interface{}{}},
	{Key: "keys.apply", Type: "string", Default: "enter"},
	{Key: "keys.autocomplete", Type: "string", Default: "tab"},
	{Key: "keys.colorNext", Type: "string", Default: "shift+right"},
	{Key: "keys.colorPrev", Type: "string", Default: "shift+left"},
	{Key: "keys.downloads", Type: "string", Default: "ctrl+d"},
	{Key: "keys.effects", Type: "string", Default: "ctrl+click"},
	{Key: "keys.favourite", Type: "string", Default: "f"},
	{Key: "keys.filterBar", Type: "string", Default: "shift+up"},
	{Key: "keys.flip", Type: "string", Default: "right-click"},
	{Key: "keys.folderNext", Type: "string", Default: "ctrl+right"},
	{Key: "keys.folderPrev", Type: "string", Default: "ctrl+left"},
	{Key: "keys.folderToggle", Type: "string", Default: "ctrl+m"},
	{Key: "keys.help", Type: "string", Default: "?"},
	{Key: "keys.hiddenFolders", Type: "string", Default: "ctrl+h"},
	{Key: "keys.navDown", Type: "string", Default: "down"},
	{Key: "keys.navLeft", Type: "string", Default: "left"},
	{Key: "keys.navRight", Type: "string", Default: "right"},
	{Key: "keys.navUp", Type: "string", Default: "up"},
	{Key: "keys.playlists", Type: "string", Default: "p"},
	{Key: "keys.randomRotate", Type: "string", Default: "ctrl+r"},
	{Key: "keys.reveal", Type: "string", Default: "v"},
	{Key: "keys.sceneProperties", Type: "string", Default: "shift+w"},
	{Key: "keys.searchMode", Type: "string", Default: "ctrl+tab"},
	{Key: "keys.select", Type: "string", Default: "click"},
	{Key: "keys.settings", Type: "string", Default: "shift+s"},
	{Key: "keys.sortNext", Type: "string", Default: "alt+right"},
	{Key: "keys.sortPrev", Type: "string", Default: "alt+left"},
	{Key: "keys.sourceBing", Type: "string", Default: "6"},
	{Key: "keys.sourcePexels", Type: "string", Default: "4"},
	{Key: "keys.sourceSteam", Type: "string", Default: "2"},
	{Key: "keys.sourceUnsplash", Type: "string", Default: "3"},
	{Key: "keys.sourceWallhaven", Type: "string", Default: "1"},
	{Key: "keys.sourceYoutube", Type: "string", Default: "5"},
	{Key: "keys.studio", Type: "string", Default: "shift+right-click"},
	{Key: "keys.tagCloud", Type: "string", Default: "shift+down"},
	{Key: "keys.tagMode", Type: "string", Default: "t"},
	{Key: "keys.themePanel", Type: "string", Default: "c"},
	{Key: "keys.typeNext", Type: "string", Default: "tab"},
	{Key: "keys.typePrev", Type: "string", Default: "shift+tab"},
	{Key: "launch.animation", Type: "enum", Default: "fade", Options: []string{"none", "fade", "rise", "zoom"}},
	{Key: "library.pollingFallback", Type: "bool", Default: false},
	{Key: "library.pollingIntervalSeconds", Type: "number", Default: float64(60), Min: fp(15.0), Max: fp(3600.0), Step: fp(1.0)},
	{Key: "matugen.colorIndex", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(3.0), Store: "hub"},
	{Key: "matugen.contrast", Type: "number", Default: float64(0), Store: "hub", Min: fp(-100.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "matugen.mode", Type: "string", Default: "dark"},
	{Key: "matugen.schemeType", Type: "enum", Default: "scheme-fidelity", Options: []string{"scheme-content", "scheme-expressive", "scheme-fidelity", "scheme-fruit-salad", "scheme-monochrome", "scheme-neutral", "scheme-rainbow", "scheme-tonal-spot", "scheme-vibrant", "scheme-smart"}, Store: "hub"},
	{Key: "matugen.videoFrame", Type: "number", Default: float64(1), Min: fp(0.0), Max: fp(10.0), Step: fp(1.0)},
	{Key: "monitor", Type: "string", Default: ""},
	{Key: "motion.fastMs", Type: "number", Default: float64(180), Min: fp(35.0), Max: fp(2000.0), Step: fp(1.0)},
	{Key: "motion.filterSwapSpeed", Type: "enum", Default: "slow", Options: []string{"fast", "standard", "slow"}},
	{Key: "motion.launchSpeed", Type: "enum", Default: "standard", Options: []string{"fast", "standard", "slow"}},
	{Key: "motion.slowMs", Type: "number", Default: float64(450), Min: fp(35.0), Max: fp(4000.0), Step: fp(1.0)},
	{Key: "motion.standardMs", Type: "number", Default: float64(250), Min: fp(35.0), Max: fp(2000.0), Step: fp(1.0)},
	{Key: "overviewBackdrop.autoTheme", Type: "bool", Default: false},
	{Key: "overviewBackdrop.blur", Type: "number", Default: float64(20), Min: fp(0.0), Max: fp(200.0), Step: fp(1.0)},
	{Key: "overviewBackdrop.blurEnabled", Type: "bool", Default: true},
	{Key: "overviewBackdrop.dim", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "overviewBackdrop.enabled", Type: "bool", Default: true},
	{Key: "overviewBackdrop.followWallpaper", Type: "bool", Default: true},
	{Key: "overviewBackdrop.path", Type: "string", Default: ""},
	{Key: "overviewBackdrop.theme", Type: "string", Default: ""},
	{Key: "paletteBridgeSource", Type: "string", Default: ""},
	{Key: "paper.idlePauseSeconds", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(3600.0), Step: fp(1.0)},
	{Key: "paper.loadTimeoutSeconds", Type: "number", Default: float64(3), Min: fp(3.0), Max: fp(60.0), Step: fp(1.0)},
	{Key: "paper.performanceMode", Type: "bool", Default: false},
	{Key: "paths.steam", Type: "string", Default: ""},
	{Key: "paths.steamWeAssets", Type: "string", Default: ""},
	{Key: "paths.steamWorkshop", Type: "string", Default: ""},
	{Key: "paths.videoWallpaper", Type: "string", Default: ""},
	{Key: "paths.wallpaper", Type: "string", Default: ""},
	{Key: "performance.autoCleanVideoCache", Type: "bool", Default: true},
	{Key: "performance.autoDeleteImageTrash", Type: "bool", Default: false},
	{Key: "performance.autoOptimizeImages", Type: "bool", Default: false},
	{Key: "performance.batteryFps", Type: "number", Default: float64(60), Min: fp(0.0), Max: fp(360.0), Step: fp(1.0)},
	{Key: "performance.batterySaver", Type: "bool", Default: true},
	{Key: "performance.batteryVideoIdleSeconds", Type: "number", Default: float64(120), Min: fp(0.0), Max: fp(3600.0), Step: fp(1.0)},
	{Key: "performance.batteryWallpaperPerformance", Type: "bool", Default: false},
	{Key: "performance.gpuDevice", Type: "string", Default: "auto"},
	{Key: "performance.gpuPreference", Type: "enum", Default: "auto", Options: []string{"auto", "low", "high", "none"}},
	{Key: "performance.imageOptimizePreset", Type: "enum", Default: "balanced", Options: []string{"light", "balanced", "quality"}},
	{Key: "performance.imageOptimizeResolution", Type: "enum", Default: "2k", Options: []string{"1080p", "2k", "4k"}},
	{Key: "performance.imageTrashDays", Type: "number", Default: float64(7), Min: fp(0.0), Max: fp(3650.0), Step: fp(1.0)},
	{Key: "performance.maxThumbJobs", Type: "number", Default: float64(16), Min: fp(1.0), Max: fp(32.0), Step: fp(1.0)},
	{Key: "performance.releaseAfterHideSeconds", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(86400.0), Step: fp(1.0)},
	{Key: "performance.videoCacheDays", Type: "number", Default: float64(30), Min: fp(0.0), Max: fp(3650.0), Step: fp(1.0)},
	{Key: "performance.videoConvertPreset", Type: "enum", Default: "balanced", Options: []string{"light", "balanced", "quality"}},
	{Key: "performance.videoConvertResolution", Type: "enum", Default: "4k", Options: []string{"1080p", "2k", "4k"}},
	{Key: "pickOnlyMode", Type: "bool", Default: false},
	{Key: "playback.fullWidthPause", Type: "bool", Default: false},
	{Key: "playback.fullscreen", Type: "bool", Default: false},
	{Key: "playback.fullscreenScope", Type: "enum", Default: "all", Options: []string{"all", "display"}},
	{Key: "playback.maximized", Type: "bool", Default: false},
	{Key: "playback.muteOnOtherAudio", Type: "bool", Default: false},
	{Key: "playback.overviewOnly", Type: "bool", Default: false},
	{Key: "playback.processEnabled", Type: "bool", Default: false},
	{Key: "playback.processes", Type: "list", Default: []interface{}{}},
	{Key: "playback.resumeDelay", Type: "number", Default: float64(1), Min: fp(0.0), Max: fp(30.0), Step: fp(0.5)},
	{Key: "postProcessOnRestore", Type: "bool", Default: false},
	{Key: "postProcessing", Type: "list", Default: []interface{}{}},
	{Key: "resource_tier", Type: "enum", Default: "medium", Options: []string{"low", "medium", "high"}},
	{Key: "restoreOnStartup", Type: "bool", Default: true},
	{Key: "schedule.applyOnStart", Type: "bool", Default: true},
	{Key: "schedule.enabled", Type: "bool", Default: false},
	{Key: "schedule.latitude", Type: "string", Default: ""},
	{Key: "schedule.longitude", Type: "string", Default: ""},
	{Key: "selector.livePreview", Type: "bool", Default: true},
	{Key: "semantic.enabled", Type: "bool", Default: true},
	{Key: "semantic.indexProfile", Type: "enum", Default: "full", Options: []string{"full", "multiview"}},
	{Key: "semantic.manifest", Type: "string", Default: ""},
	{Key: "semantic.models", Type: "list", Default: []interface{}{}},
	{Key: "shell.hoverPreview", Type: "bool", Default: false},
	{Key: "sources.bing.enabled", Type: "bool", Default: false},
	{Key: "sources.bing.market", Type: "string", Default: "en-US"},
	{Key: "sources.pexels.apiKey", Type: "string", Default: ""},
	{Key: "sources.pexels.enabled", Type: "bool", Default: false},
	{Key: "sources.pexels.showApplyButton", Type: "bool", Default: false},
	{Key: "sources.repos", Type: "list", Default: []interface{}{}},
	{Key: "sources.steam.showApplyButton", Type: "bool", Default: false},
	{Key: "sources.unsplash.accessKey", Type: "string", Default: ""},
	{Key: "sources.unsplash.enabled", Type: "bool", Default: false},
	{Key: "sources.unsplash.showApplyButton", Type: "bool", Default: false},
	{Key: "sources.wallhaven.showApplyButton", Type: "bool", Default: false},
	{Key: "sources.youtube.enabled", Type: "bool", Default: false},
	{Key: "sources.youtube.maxHeight", Type: "number", Default: float64(2160), Min: fp(240.0), Max: fp(2160.0), Step: fp(1.0)},
	{Key: "sources.youtube.maxMinutes", Type: "number", Default: float64(3), Min: fp(1.0), Max: fp(60.0), Step: fp(1.0)},
	{Key: "sources.youtube.showApplyButton", Type: "bool", Default: false},
	{Key: "steam.apiKey", Type: "string", Default: ""},
	{Key: "steam.backend", Type: "enum", Default: "steam", Options: []string{"steam", "steamcmd"}},
	{Key: "steam.defaults.category", Type: "enum", Default: "", Options: []string{"", "Abstract", "Animal", "Anime", "CGI", "Cyberpunk", "Fantasy", "Game", "Girls", "Guys", "Landscape", "Medieval", "Music", "Nature", "Pixel art", "Relaxing", "Retro", "Sci-Fi", "Technology", "Vehicle"}},
	{Key: "steam.defaults.nsfw", Type: "bool", Default: false},
	{Key: "steam.defaults.resolution", Type: "enum", Default: "", Options: []string{"", "1920 x 1080", "2560 x 1440", "3840 x 2160", "2560 x 1080", "3440 x 1440", "3840 x 1080"}},
	{Key: "steam.defaults.sort", Type: "enum", Default: "3", Options: []string{"3", "0", "1", "21", "9"}},
	{Key: "steam.defaults.trendDays", Type: "enum", Default: "7", Options: []string{"1", "3", "7"}},
	{Key: "steam.defaults.type", Type: "enum", Default: "", Options: []string{"", "Scene", "Video"}},
	{Key: "steam.username", Type: "string", Default: ""},
	{Key: "tagging.defaultSearchMode", Type: "enum", Default: "tags", Options: []string{"tags", "describe"}},
	{Key: "theme.customColors", Type: "string", Default: ""},
	{Key: "theme.mode", Type: "enum", Default: "dark", Options: []string{"dark", "light", "auto", "smart", "sun"}, Store: "hub"},
	{Key: "theme.policy", Type: "enum", Default: "wallpaper", Options: []string{"wallpaper", "fixed", "off"}},
	{Key: "theme.staticTheme", Type: "string", Default: "nord"},
	{Key: "transition.durationMs", Type: "number", Default: float64(600), Min: fp(50.0), Max: fp(10000.0), Step: fp(1.0)},
	{Key: "transition.enabled", Type: "bool", Default: true},
	{Key: "transition.family", Type: "enum", Default: "random", Options: []string{"random", "fade", "wipe", "warp", "break", "sand"}},
	{Key: "transition.fps", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(1000.0), Step: fp(1.0)},
	{Key: "transition.preview", Type: "bool", Default: true},
	{Key: "transition.previewFps", Type: "number", Default: float64(30), Min: fp(1.0), Max: fp(1000.0), Step: fp(1.0)},
	{Key: "transition.sandFps", Type: "number", Default: float64(0), Min: fp(0.0), Max: fp(240.0), Step: fp(1.0)},
	{Key: "transition.sandPrimary", Type: "string", Default: ""},
	{Key: "transition.sandQuality", Type: "enum", Default: "auto", Options: []string{"auto", "full", "low"}},
	{Key: "transition.sandScope", Type: "string", Default: "all"},
	{Key: "transition.sandSharp", Type: "bool", Default: false},
	{Key: "transition.shader", Type: "string", Default: "random"},
	{Key: "transition.shaderScopes", Type: "object", Default: map[string]interface{}{}},
	{Key: "videoPreview.delayMs", Type: "number", Default: float64(250), Min: fp(0.0), Max: fp(5000.0), Step: fp(1.0)},
	{Key: "videoPreview.enabled", Type: "bool", Default: true},
	{Key: "wallhaven.apiKey", Type: "string", Default: ""},
	{Key: "wallhaven.defaults.anime", Type: "bool", Default: true},
	{Key: "wallhaven.defaults.atleast", Type: "enum", Default: "", Options: []string{"", "1920x1080", "2560x1440", "3840x2160", "5120x2880", "7680x4320"}},
	{Key: "wallhaven.defaults.atmost", Type: "enum", Default: "", Options: []string{"", "1920x1080", "2560x1440", "3840x2160", "5120x2880", "7680x4320"}},
	{Key: "wallhaven.defaults.general", Type: "bool", Default: true},
	{Key: "wallhaven.defaults.nsfw", Type: "bool", Default: false},
	{Key: "wallhaven.defaults.people", Type: "bool", Default: true},
	{Key: "wallhaven.defaults.ratios", Type: "enum", Default: "", Options: []string{"", "16x9", "16x10", "21x9", "32x9", "4x3"}},
	{Key: "wallhaven.defaults.sfw", Type: "bool", Default: true},
	{Key: "wallhaven.defaults.sketchy", Type: "bool", Default: false},
	{Key: "wallhaven.defaults.sort", Type: "enum", Default: "toplist", Options: []string{"toplist", "hot", "date_added", "relevance", "views", "favorites", "random"}},
	{Key: "wallhaven.defaults.topRange", Type: "enum", Default: "1M", Options: []string{"1d", "3d", "1w", "1M", "3M", "6M", "1y"}},
	{Key: "wallhaven.username", Type: "string", Default: ""},
	{Key: "wallpaper.video_enabled", Type: "bool", Default: true, Store: "shell"},
	{Key: "wallpaper.video_engine", Type: "enum", Default: "ryogami", Options: []string{"ryogami", "in_shell"}, Store: "shell", StoreKey: "wallpaper.video_engine"},
	{Key: "wallpaper.video_transcode", Type: "bool", Default: false, Store: "shell"},
	{Key: "wallpaper.video_transcode_fps", Type: "number", Default: float64(24), Store: "shell", Min: fp(1.0), Max: fp(60.0), Step: fp(1.0)},
	{Key: "wallpaper.video_transcode_width", Type: "number", Default: float64(1920), Store: "shell", Min: fp(480.0), Max: fp(3840.0), Step: fp(1.0)},
	{Key: "wallpaperMute", Type: "bool", Default: true},
	{Key: "wallpaperVolume", Type: "number", Default: float64(100), Min: fp(0.0), Max: fp(100.0), Step: fp(1.0)},
	{Key: "weRender.clamp", Type: "string", Default: "clamp"},
	{Key: "weRender.disableParticles", Type: "bool", Default: false},
	{Key: "weRender.fps", Type: "number", Default: float64(30), Min: fp(1.0), Max: fp(240.0), Step: fp(1.0)},
	{Key: "weRender.scaling", Type: "enum", Default: "default", Options: []string{"default", "fill", "fit", "stretch", "center", "tile", "span"}},
}
